### ISSUE TITLE
Crash because of empty /var/cache/libdnf5/temporary_files.toml file?

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#1001]
I just tried my routine `dnf5 update --refresh`:

```
...
After this operation 66 KiB will be used (install 781 MiB, remove 781 MiB).
Is this ok [y/N]: y
Failed to download packages
 An error occurred when parsing the temporary files memory file at '/var/cache/libdnf5/temporary_files.toml': [error] toml::value::as_array(): bad_cast to array
 --> unknown file
   |
 1 | unknown line
   |  the actual type is empty
```

It was reproducible, and work-around was to remove the `temporary_files.toml` file.  DNF tooling:

```
dnf5                 x86_64       5.1.6-20231106004845.10.g8598828e.fc40  copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf5-unstable                 1.3 MiB
dnf5-plugins         x86_64       5.1.6-20231106004845.10.g8598828e.fc40  copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf5-unstable               578.9 KiB
libdnf5              x86_64       5.1.6-20231106004845.10.g8598828e.fc40  copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf5-unstable                 2.5 MiB
libdnf5-cli          x86_64       5.1.6-20231106004845.10.g8598828e.fc40  copr:copr.fedorainfracloud.org:rpmsoftwaremanagement:dnf5-unstable               530.1 KiB
```

**Comment by j-mracek** [comment]
Do you now how the empty file was created?

**Comment by j-mracek** [comment]
The issue is reproducible by creating the empty file using touch.

**Comment by jan-kolarik** [comment]
Briefly looking into the code, I couldn't find a reason for the file to be empty. Nevertheless, I believe we should change the behavior to avoid throwing an exception when the memory file has an invalid format. Instead, we should simply ignore it and delete the file in such cases.

**Comment by praiskup** [comment]
> Do you now how the empty file was created?

No :-( I don't even know what is it's purpose.

**Comment by j-mracek** [comment]
I am also curious how it happened. The question is whether we should recover from the situation.
If `toml::format(toml::value({{FILE_PATHS_TOML_KEY, files}}))` can  return an empty string then it would be possible to experience the situation. I was unable to figure from code and from documentation whether it is possible.

What about to modify following line?
```
utils::fs::File(temporary_path, "w").write(toml::format(toml::value({{FILE_PATHS_TOML_KEY, files}})));
```
We could add a test - if `toml::format(toml::value({{FILE_PATHS_TOML_KEY, files}}))` returns an empty string, then log the event as an error and log the content of `const std::vector<std::string> & paths`.
