### ISSUE TITLE
Print details when failed to resolve modules

### ISSUE THREAD

**Issue by pkratoch** [rpm-software-management/dnf5#1029]
Right now, dnf just prints "Failed to resolve modules.", but dnf4 printed the specific problems that caused the failure.

**Comment by ppisar** [comment]
I confirm this issue (dnf5-5.1.7-20231116005017.18.g2d77952d.fc40.x86_64).

**Comment by pkratoch** [comment]
Closing as duplicate of https://github.com/rpm-software-management/dnf5/issues/1021
