### ISSUE TITLE
WITH_MODULEMD CMake Option Is Not Excluding Compilation With modulemd-2.0

### ISSUE THREAD

**Issue by sameluch** [rpm-software-management/dnf5#1031]
When trying to build `dnf5` from the dnf5.spec in this repository, I am running into an issue where I cannot compile without `modulemd`. I am building with most all of the extras outside of the core package turned off (modulemd, zchunk, perl, ruby, etc) to get the "leanest" version possible. I am currently working on version 5.0.14, though it doesn't appear to have any difference in the includes vs the current version.

Is `modulemd-2.0` meant to be an optional package or a build requirement for libdnf5? hardcoded #includes are in the `libdnf5/module` directory forcing a dependency on this.

I found that there is a `WITH_MODULEMD` cmake option that doesn't seem to serve any functional purpose, at least when compared to `WITH_COMPS` or `WITH_ZCHUNK` which exclude the CMake requirement of these packages specifically.

**Comment by jan-kolarik** [comment]
Hi, you're right. It appears that there was originally an intention to make the `modulemd` dependency optional, but currently, it remains in an unfinished state.

@j-mracek, please do you have an estimate of the effort required to complete this? Briefly looking into the code, it seems that the modules are scattered in many places, indicating a non-trivial amount of work.

**Comment by j-mracek** [comment]
I agree that the work is not trivial but not too difficult, but it will require maintenance because modularity is still under development.

The compilation without `modulemd-2.0` is important for distributions that never used modules therefore they have no libmodulemd in distribution.

The feature might be interesting for containers where we don't have to support modules. The support of modules will be not required in Fedora 41 (Fedora 40 requires a support of modules due to upgrade path from Fedora 38).

@mcurlej May I ask you for your opinion?

**Comment by mcurlej** [comment]
In DNF5 we implement Modularity for legacy reasons mostly. The feature set is limited to basic commands and nothing else. Currently not all of the basic commands are yet implemented. To be able to build DNF5 without `modulemd` is a valid request. But it is not a high priority.

**Comment by sameluch** [comment]
@j-mracek While the changes are non-trivial, do you know what they entail? I am considering making a temporary set of changes until the feature is implemented. Is this mostly limiting the scope of building the `libdnf5/module` folder in CMake and adding directives to the locations that reference any of the produced objects? Or am I missing a critical component here?

**Comment by kontura** [comment]
I have created a [PR](https://github.com/rpm-software-management/dnf5/pull/1521) that should make building with `-DWITH_LIBMODULEMD=OFF` work.

**Comment by kontura** [comment]
This should be now working.
