### ISSUE TITLE
bash autocompletion doesn't work in chroot

### ISSUE THREAD

**Issue by nuqleo** [rpm-software-management/dnf5#1055]
If I try bash autocompletion in chroot I get an error
```
# chroot rawhide
# dnf5 upbash: /dev/fd/63: No such file or directory
```
No problem with dnf4
```
# dnf up
up               update           updateinfo       update-minimal   update-to        upgrade          upgrade-minimal  upgrade-to       upif             up-min
```

**Comment by jan-kolarik** [comment]
Hi, this is a general problem with the `chroot` environment, not directly related to `dnf5`. You can find a solution in [this article](https://devicetests.com/fix-dev-fd-63-error-ubuntu-chroot). Following the steps outlined there, you can resolve the issue by making the host `/dev` and `/proc` directory content available in chroot like this:

```
mount --bind /dev /your_chroot/dev/
mount --bind /proc /your_chroot/proc/
```

**Comment by nuqleo** [comment]
But dnf4 and rpm autocompletion works without mounting /dev /proc
```
# rpm -ivh --nod
--nodeps    --nodigest
```

**Comment by jan-kolarik** [comment]
This is because dnf4 and rpm use different internal implementations of autocompletion. In dnf5, process substitution is involved, utilizing `/dev/fd/<n>` files. See the dnf5 code [here](https://github.com/rpm-software-management/dnf5/blob/main/dnf5/bash-completion/dnf5#L7).

**Comment by jan-kolarik** [comment]
I will raise this topic during our team meeting and see if there are any other reasonable possibilites how to make this working in chroot by default. But still I see the solution with binding the host directories easy enough or is there any specific problem with that?

**Comment by nuqleo** [comment]
mount binding can do only root user but this is impossible if instead of chroot used unshare started by non-root user.

**Comment by jrohel** [comment]
I replaced "Process Substitution" with "Command Substitution". This fixed the problem in my test chroot. PR https://github.com/rpm-software-management/dnf5/pull/1078

**Comment by nuqleo** [comment]
After applying patch autocompletion works inside unshare -R.
