### ISSUE TITLE
Change the message shown after running system-upgrade download

### ISSUE THREAD

**Issue by Oneechan69** [rpm-software-management/dnf5#1059]
I wrote this as suggested by someone [here](https://discussion.fedoraproject.org/t/shouldnt-it-be-made-clear-the-dnf-system-upgrade-clean-deletes-update-files-after-running-dnf-system-upgrade-download/97935). I ran `dnf system-upgrade clean` thinking that it would remove misc junk or cache files and not the upgrade files themselves. In DNF 4 this is the current message shown after running `system-upgrade download`:

>Download complete! Use `dnf system-upgrade reboot` to start the upgrade.  
>To remove cached metadata and transaction use `dnf system-upgrade clean`  
>The downloaded packages were saved in cache until the next successful transaction.  
>You can remove cached packages by executing `dnf clean packages.`

The 2nd line should be rephrased to "To remove the downloaded upgrade file, use `dnf system-upgrade clean`" or something more comprehensive.

**Comment by kontura** [comment]
Thanks for the report, we can indeed clarify the message.
I have linked the issue to our `system-upgrade` issue:  https://github.com/rpm-software-management/dnf5/issues/1052

**Comment by kontura** [comment]
The message has been changed to:
```
Transaction stored to be performed offline. Run `dnf5 offline reboot` to reboot and run the transaction. To cancel the transaction and delete the downloaded files, use `dnf5 offline clean`.
```
