### ISSUE TITLE
Rework output header files

### ISSUE THREAD

**Issue by inknos** [rpm-software-management/dnf5#1072]
This issue originated from an internal discussion about this PR https://github.com/rpm-software-management/dnf5/pull/1070

There are a couple of issues related to how we use header files for output functions. First of all, header files are useful only because template functions are defined there.

Also, many times the `static` keyword is used, but it does not really serve any purpose.

- [x] drop `static` and/or `inline` keywords
- [x] move non-templatefunctions to cpp files

**Comment by inknos** [comment]
@j-mracek is there anything I am missing?

**Comment by jan-kolarik** [comment]
> Frankly, I don't like the way the outputs are written.
> 
> * Too much code in templates and header files.
> * Exposed "libsmartcols"
> 
> I prefer to rework it. But that would mean changing the API.

I've been just started working on https://github.com/rpm-software-management/dnf5/issues/867 and realized that the JSON output from libsmartcols is not sufficient and very friendly. We'd probably need a different library for the json output, so it makes sense separating of filling the output from the actual output implementation.

**Comment by jan-kolarik** [comment]
@jrohel Can we consider this done? Or is anything related missing?
