### ISSUE TITLE
`Base.setup()` cannot create `/usr/lib/sysimage/libdnf5` with non-root user

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/dnf5#1080]
As of 5.1.9 in Fedora Rawhide, libdnf5 fails to `.setup()` a Base object on a fresh system as a non-root user. It apparently tries to create `/usr/lib/sysimage/libdnf5` which does not exist on a fresh system and which a regular user does not have permissions to create:

```
>>> import libdnf5
>>> base = libdnf5.base.Base()
>>> base.load_config_from_file()
>>> base.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.12/site-packages/libdnf5/base.py", line 492, in setup
    return _base.Base_setup(self)
           ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: filesystem error: cannot create directories: Permission denied [/usr/lib/sysimage/libdnf5]
```

Other `dnf5` commands fail with the same error:

``` console
$ dnf5 makecache
filesystem error: cannot create directories: Permission denied [/usr/lib/sysimage/libdnf5]
```

**Comment by jan-kolarik** [comment]
Agree, reproducible on Rawhide by simply installing the dnf5 package and running `dnf5 makecache`.

**Comment by kontura** [comment]
We have discussed with @jan-kolarik that this would ideally have a more proper fix that his quick [PR](https://github.com/rpm-software-management/dnf5/pull/1081). 
Given that I would like to work on it I am taking the issue, hopefully this is ok. :slightly_smiling_face:
