### ISSUE TITLE
filter_latest_evr returns more than one result

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#1090]
Reproducer script can be found here - https://bcl.fedorapeople.org/scripts/dupe-pkgs.py

According to the documentation for filter_latest_evr() it should return one package per arch.
But if there are multiple repositories with identical NEVRAs, and their priorities are
the same it will return more than one.

If the priorities are different, and I apply filter_priority() it will only return one -- but I cannot depend on the repos having different priorities, and it should just pick one and use it.

Example output:
```
[root@e7fca6659064 ~]# rpm -q python3-libdnf5
python3-libdnf5-5.1.9-1.fc40.x86_64
[root@e7fca6659064 ~]# python3 ./dupe-pkgs.py 
Directory walk started
Directory walk done - 3 packages
Temporary output repo path: /tmp/lorax.test.repo.l0tgv06x/.repodata/
Pool started (with 5 workers)
Pool finished
Directory walk started
Directory walk done - 2 packages
Temporary output repo path: /tmp/lorax.test.repo.4chelkto/.repodata/
Pool started (with 5 workers)
Pool finished
Added 'lorax-repo-0': /tmp/lorax.test.repo.l0tgv06x
Added 'lorax-repo-1': /tmp/lorax.test.repo.4chelkto
Fetching metadata...
Should print a single fake-milhouse
fake-milhouse-1.3.0-1.x86_64
Should print a single fake-marge but prints two
fake-marge-2.3.0-1.x86_64
fake-marge-2.3.0-1.x86_64
```

I've worked around this in Lorax by deduplicating the query results - https://github.com/weldr/lorax/commit/8b5d776d9c37aa0ad5cd0a1d4fa5fe90fdfba8b8

**Comment by j-mracek** [comment]
May I ask you for verification.

The situation is that there are two packages with the same NEVRA. The method to get the latest is `query.filter_latest_evr()`.

The documentation for the method:
`Group packages by `name` and `arch`. Then within each group, keep packages that correspond with up to `limit` of (all but) latest `evr`s in the group.`

The method has the same behavior like DNF query.filter(latest=1). It also returns all packages with the latest version.

May I ask you how did you resolve the issue with DNF4?

**Comment by bcl** [comment]
> May I ask you for verification.
> 
> The situation is that there are two packages with the same NEVRA. The method to get the latest is `query.filter_latest_evr()`.
> 
> The documentation for the method: `Group packages by `name`and`arch`. Then within each group, keep packages that correspond with up to `limit`of (all but) latest`evr`s in the group.`

But doesn't that mean it should return one package? They're the same name and arch. If it was two different arches then I could see it returning two. It doesn't say it groups then by repo, but that seems to be what it is doing.

> 
> The method has the same behavior like DNF query.filter(latest=1). It also returns all packages with the latest version.
> 
> May I ask you how did you resolve the issue with DNF4?

There's nothing in the dnf4 version of lorax that dealt with duplicate entries, they never seemed to be a problem.

**BUT** now that I rerun the dnf4 version (lorax v40.0-1) with two repos I do see that it is logging that it is returning 2 packages. Not sure why I never noticed that before. But actually installing them doesn't generate an error like it does with the dnf5 version.

With dnf5 if you try to run the transaction after adding a package twice I get:
```
2023-12-15 14:47:48,375 DEBUG pylorax.ltmpl: template line 78: run_pkg_transaction
2023-12-15 14:47:48,375 INFO pylorax.ltmpl: Checking dependencies
2023-12-15 14:49:09,641 ERROR pylorax.ltmpl: Dependency check failed: Debug data written to "/root/lorax-dnf5-bad/debugdata"
Problem 1: cannot install both fedora-release-40-0.20.noarch and fedora-release-40-0.20.noarch
  - conflicting requests
 Problem 2: cannot install both fedora-logos-38.1.0-2.fc39.noarch and fedora-logos-38.1.0-2.fc39.noarch
  - conflicting requests
 Problem 3: cannot install both anaconda-40.13-1.fc40.x86_64 and anaconda-40.13-1.fc40.x86_64
```
and with dnf4 it happily just installs things.

So maybe the problem is in how it dnf5 handles running a transaction with duplicate package NEVRAs added to the goal?

**Comment by j-mracek** [comment]
I looked in f37 `Lorax` code and I found only  following code that handles latest query results:
```
                # Get the latest package, or package matching the selected version
                pkgnames = self._pkgver(p)
                if not pkgnames:
                    raise dnf.exceptions.PackageNotFoundError("no package matched", p)

                # Apply excludes to the name only
                for exclude in excludes:
                    pkgnames = [pkg for pkg in pkgnames if not fnmatch.fnmatch(pkg.name, exclude)]

                # Convert to a sorted NVR list for installation
                pkgnvrs = sorted(["{}-{}-{}".format(pkg.name, pkg.version, pkg.release) for pkg in pkgnames])

                # If the request is a glob, expand it in the log
                if any(g for g in ['*','?','.'] if g in p):
                    logger.info("installpkg: %s expands to %s", p, ",".join(pkgnvrs))

                for pkgnvr in pkgnvrs:
                    try:
                        self.dbo.install(pkgnvr)
                    except Exception as e: # pylint: disable=broad-except
                        if required:
                            raise
                        # Not required, log it and continue processing pkgs
                        logger.error("installpkg %s failed: %s", pkgnvr, str(e))
```
`pkgnames = self._pkgver(p)` returns latest version of packages, then only name, version, release is used `pkgnvrs`. Then those strings are passed to `self.dbo.install(pkgnvr)` calls DNF and it does not report providing the same request twice as a problem.

**Comment by j-mracek** [comment]
I like the assume part from comment from Lorax
 ```
               ## REMOVE DUPLICATES
                ## If there are duplicate packages from different repositories with the same
                ## priority they will be listed more than once. This is especially bad with
                ## globs like *-firmware
                ##
                ## ASSUME the same nevra is the same package, no matter what repo it comes
                ## from.
```
This is a reason why DNF does not want to return a random package. `filter_latest_evr` returns number of versions not package objects.
I am happy to help, but I need to know what you would prefer.

I have 3 packages with the same NEVRA from 2 repositories. Do you want to pick a random package from the set and then the package send to solver `goal.add_rpm_install(p)`. Or send all of them to solver and solver will pick according to priority?

**Comment by bcl** [comment]
In the F37 version using dnf4 it actually does return duplicates, but the install/transaction run doesn't care. So if dnf5 could do the same thing I guess that would be the correct thing to do. I think what it should be doing with multiple identical requests is:

* Sort by repo priority first
* Check the checksums / signatures of the duplicates. Throw out bad signatures (or maybe quit with an error). If the remaining checksums don't all match, return an error.
* Pick the first one, since they are all the same it doesn't need to be random. Maybe sort by cost at this point and pick based on that.

**Comment by j-mracek** [comment]
What about to remove additional filters from Lorax (filter by priority), and modify `goal.add_rpm_install(p)` to `goal.add_rpm_install(p.get_full_nevra())`. It will automatically pick the package according to priority and there will be no issue with redundant requests.

**Comment by bcl** [comment]
I don't see how that would help. The duplicates are coming from the _pkgver() and even without using priority() I was getting more than 1 result. Also, why would passing p.get_full_nevra() do anything different? I'm already passing in p which is the package object and therefore already the full nevra.

**Comment by bcl** [comment]
Related to this, anaconda's nightly tests are now hitting a similar but different problem -- packages with different arches are trying to be installed at the same time: https://github.com/rhinstaller/kickstart-tests/actions/runs/7263835386/job/19790019961

```
Problem: cannot install both anaconda-install-img-deps-40.12-1.20231205144801720625.master.3.gd66b9912c5.fc40.noarch and anaconda-install-img-deps-40.15-1.20231219045442936819.master.0.gc6e2e850b8.fc40.x86_64
    - conflicting requests
```

**Comment by bcl** [comment]
I've filed #1111 since I think it is a separate bug.

**Comment by j-mracek** [comment]
> The duplicates are coming from the _pkgver() and even without using priority() I was getting more than 1 result. Also, why would passing p.get_full_nevra() do anything different? I'm already passing in p

There is a difference - install `goal.add_rpm_install(p)` force solver to install package object `p` and if you pass two different package objects with the same name (or NEVRA) then solver cannot perform the operation (conflict). If you use `goal.add_rpm_install(p.get_full_nevra())` it pass a string (NEVRA) to install and solver will pick one even if the same NEVRA is passed multiple times.

I consider the issue as resolved.

**Comment by bcl** [comment]
It seems odd to me that it would be treated differently. But thanks for the explanation, we can close this. You may want to document that behavior in `add_rpm_install` though.
