### ISSUE TITLE
Release dnf5-5.2.0.0

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#1091]
Since we need to do API and ABI changes we will have to make a new major version release update.

This issue should track all the required/planned changes:
 - [x] https://github.com/rpm-software-management/dnf5/issues/1025
 - [x] https://github.com/rpm-software-management/dnf5/pull/1085
 - [x] https://github.com/rpm-software-management/dnf5/pull/1087
 - [x] https://github.com/rpm-software-management/dnf5/pull/1216
 - [x] https://github.com/rpm-software-management/dnf5/issues/1189
 - [x] https://github.com/rpm-software-management/dnf5/issues/1072
 - [x] Drop deprecated API
   - [x] https://github.com/rpm-software-management/dnf5/pull/1294
   - [x] https://github.com/rpm-software-management/dnf5/issues/1322

Follow-ups:
- [x] https://github.com/rpm-software-management/dnf5/pull/1421

**Comment by voxik** [comment]
"Dnf5-6.0.0" sorry, I can't help, but this won't stop fascinating me.

**Comment by j-mracek** [comment]
I am proposing to add `use_glob{true}` to `ResolveSpecSettings`. Such a change will brake ABI.

**Comment by Conan-Kudo** [comment]
> "Dnf5-6.0.0" sorry, I can't help, but this won't stop fascinating me.

We should have just renamed the old project to "dnf4" and kept calling this "dnf" but here we are. :)

**Comment by kontura** [comment]
We are also considering changing the versioning to add one more number and keep the 5.
So the new breaking version would be `dnf5-5.2.0.0`.

The nevras still do compare correctly: `dnf5-5.2.0.0` > `dnf5-5.1.0`.

**Comment by jan-kolarik** [comment]
OK, I believe we can proceed with merging this to main.

**Comment by Conan-Kudo** [comment]
Do you think we have sufficient API coverage for me to implement a PackageKit backend using libdnf5 based on what we have for the current dnf backend? https://github.com/PackageKit/PackageKit/tree/main/backends/dnf

**Comment by jan-kolarik** [comment]
> Do you think we have sufficient API coverage for me to implement a PackageKit backend using libdnf5 based on what we have for the current dnf backend? https://github.com/PackageKit/PackageKit/tree/main/backends/dnf

I believe so, but I'll try to go through it this week to verify. However, I'm curious and a bit confused because I thought PackageKit is already only in maintenance mode, and new plugins for package manager frontends like GNOME Software, KDE, dnfdragora, etc., are now being developed using the dnf5daemon API.

**Comment by jan-kolarik** [comment]
> Do you think we have sufficient API coverage for me to implement a PackageKit backend using libdnf5 based on what we have for the current dnf backend? https://github.com/PackageKit/PackageKit/tree/main/backends/dnf

So, I went through the existing PackageKit backend for dnf, and I didn't find any features lacking in dnf5. However, it's possible I overlooked something as the codebase is pretty extensive. In any case, if you encounter any challenges implementing specific use cases with the DNF5 API, don't hesitate to reach out. :slightly_smiling_face:
