### ISSUE TITLE
RFE: allow listing protected packages under /usr

### ISSUE THREAD

**Issue by keszybz** [rpm-software-management/dnf5#1107]
Support for config under /usr was added in a bunch of places (https://github.com/rpm-software-management/dnf5/pull/813, https://github.com/rpm-software-management/dnf5/pull/820, https://github.com/rpm-software-management/dnf5/pull/882), but `config_main.cpp` has:
```C
protected_packages{resolve_globs("dnf5 glob:/etc/dnf/protected.d/*.conf")};
```

**Comment by j-mracek** [comment]
The `protected_packages` is a configuration option, therefore you can use standard configuration overrides. The problem is that this option is not append. What about to change the option to an append and then use standard configuration overrides in `usr` to extend the list of protected packages?

```
[main]
protected_packages = <my_new_protected_package>
```

**Comment by keszybz** [comment]
> The `protected_packages` is a configuration option, therefore you can use standard configuration overrides. The problem is that this option is not append. What about to change the option to an append and then use standard configuration overrides in `usr` to extend the list of protected packages?
> 
> ```
> [main]
> protected_packages = <my_new_protected_package>
> ```

Yeah, this would work. We'd need to update various packages to install a file with two lines instead of just one, but that's a very simple change to make. But we'd get the file move and easier overrides essentially for free.

**Comment by j-mracek** [comment]
I discovered an interesting thing. Protected packages setting is taken always from root system. Somehow I consider it as a not correct behavior, but I understand that it would be difficult to modify the behavior or change the workflow.

**Comment by j-mracek** [comment]
I have a good news. The patch (https://github.com/rpm-software-management/dnf5/pull/1110) is ready for testing.
