### ISSUE TITLE
Dnf5 Transaction failed

### ISSUE THREAD

**Issue by Its-Juice** [rpm-software-management/dnf5#1115]
This happens after installing all updated pacages:

Running` transaction

Transaction failed: Rpm transaction failed.
  - file /usr/lib64/gstreamer-1.0/libgstdvbsuboverlay.so from install of gstreamer1-plugins-bad-free-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-bad-freeworld-1:1.22.7-1.fc39.x86_64
  - file /usr/lib64/gstreamer-1.0/libgstsiren.so from install of gstreamer1-plugins-bad-free-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-bad-freeworld-1:1.22.7-1.fc39.x86_64
  - file /usr/lib64/gstreamer-1.0/libgstdtsdec.so from install of gstreamer1-plugins-bad-free-extras-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-bad-freeworld-1:1.22.7-1.fc39.x86_64
  - file /usr/lib64/gstreamer-1.0/libgstasf.so from install of gstreamer1-plugins-ugly-free-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-ugly-1:1.22.7-1.fc39.x86_64
  - file /usr/lib64/gstreamer-1.0/libgstdvdlpcmdec.so from install of gstreamer1-plugins-ugly-free-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-ugly-1:1.22.7-1.fc39.x86_64
  - file /usr/lib64/gstreamer-1.0/libgstdvdsub.so from install of gstreamer1-plugins-ugly-free-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-ugly-1:1.22.7-1.fc39.x86_64
  - file /usr/lib64/gstreamer-1.0/libgstrealmedia.so from install of gstreamer1-plugins-ugly-free-1.22.8-2.fc39.x86_64 conflicts with file from package gstreamer1-plugins-ugly-1:1.22.7-1.fc39.x86_64

**Comment by jan-kolarik** [comment]
Hi, what is the exact command you're running? Did you try adding the `--allowerasing` and/or `--best` options?

**Comment by j-mracek** [comment]
I believe that the problem is not in DNF5. 

`gstreamer1-plugins-bad-freeworld` and `gstreamer1-plugins-bad-free` provide the same file but they can be installed in different versions therefore file might differ. I believe that `dnf5 upgrade --best` should resolve the issue on your system. I recommend to open the issue on `gstreamer1-plugins` components to prevent installing `gstreamer1-plugins-bad-freeworld` and `gstreamer1-plugins-bad-free` in a different version. `Conflicts` or conditional `Requires` should help.

**Comment by ppisar** [comment]
This is not a bug in DNF5, but in gstreamer1-plugins-bad-freeworld package.

[gstreamer1-plugins-bad-free-1.22.8-2.fc39](https://koji.fedoraproject.org/koji/buildinfo?buildID=2336329) added the conflicting files on purpose. It's gstreamer1-plugins-bad-freeworld from RPMFusion which needs to adapt. And it will happen in [gstreamer1-plugins-bad-freeworld-1.22.8-1.fc39](https://koji.rpmfusion.org/koji/buildinfo?buildID=27502).
