### ISSUE TITLE
--forcearch is missing

### ISSUE THREAD

**Issue by berolinux** [rpm-software-management/dnf5#112]
dnf 4 has the --forcearch option, useful for installing foreign architecture chroots e.g. for use with qemu.

dnf5 doesn't have this option; and if an equivalent exists, it's hidden so well that it triggers a PBKAC with me ;)

**Comment by j-mracek** [comment]
`--forcearch` modify `arch` substitution or configuration and `ignorearch`.

```
        if self.conf.ignorearch:
            self._rpm_probfilter.add(rpm.RPMPROB_FILTER_IGNOREARCH)
```

We can implement the same option or we can use a setter for arch substitution, but it requires also handle rpm flag to ignore architecture.

The option is required for dependency check for repositories with a different architecture.

**Comment by praiskup** [comment]
This is used/needed by Mock too.
