### ISSUE TITLE
dnf5daemon missing GetGroups functionality (comps groups)

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1143]
Using dnf 4 daemon i could get the list of comps groups by using GetGroups method, now that seems to be missed into dnf5daemon.

dnfdragora uses that information to build a kind of "group" tree that helps the user to find packages by group contents.

BTW it seems that dnf5daemon client has an option for tnat though (**dnf5daemon-client group list**) even if it seems to returns some groups twice (some in the following picture).

![immagine](https://github.com/rpm-software-management/dnf5/assets/1303486/a8ce0c54-3df6-4a6e-b1cf-2110dca910d6)

**Comment by m-blaha** [comment]
This is a recurring issue. For libsolv, even packages with the same NEVRA (name, epoch, version, release, and architecture) but coming from different repositories are treated as different packages. And installed packages are essentially just another repository for libsolv (with repo id `@system`).

Similarly, installed groups (those from the @system repository) are distinct entities from groups from other repositories with the same ID. You can use the `installed` group attribute to distinguish these groups.

**Comment by anaselli** [comment]
It isn't clear to me sorry, do you mean i need to get the group from any installed packages (that iirc return always @System)? or dnf5daemon provides a method for getting installed group, and if which one and from which interface?

**Comment by Conan-Kudo** [comment]
What he's saying is that you're seeing the raw list of groups. Since composition groups can be provided by multiple repositories, it's possible to have multiple instances of it. Each repo could have a definition of the groups, and they all need to be read and merged together to give a comprehensive view of a particular group.

**Comment by Conan-Kudo** [comment]
To make it more concrete, it's possible for two repos to have a "multimedia" group, and the client (ie dnfdragora) needs to merge them into one and have a de-duplicated union of the package sets of the two groups.

**Comment by anaselli** [comment]
> To make it more concrete, it's possible for two repos to have a "multimedia" group, and the client (ie dnfdragora) needs to merge them into one and have a de-duplicated union of the package sets of the two groups.

That dnfdragora has to marge group contents is clear, but how can i get groups and their packages from repos?

**Comment by m-blaha** [comment]
I'd like to make the `Comps.list()` call more close to what `dnf5 group list` does.
1. add option `scope` to get either groups available in repositories (value `available`), or installed groups (value `installed`), or all of them (default, value `all`)
2. in case of `all` - current state is kind of confusing. The groups from all repositories with the same identifier are merged together, but installed groups are kept separately - thus duplicities in the output. dnf5 deals with this situation by skipping in the output all available groups with the same identifier as an installed group. I'd like to do the same in the daemon.
3. document Comps interface - it's missing in D-Bus API documentation.

**Comment by anaselli** [comment]
just a note, I liked the get_translated_name() method in libdnf5, even if the default one (without lang passed) does not work atm, so i kindly ask you to provide such attributes to the list call.
With my time i can do my part and try to help in documentation, is there a way to build the interface xml and/or info for html pages? Or writing on xml and others is enough?

**Comment by m-blaha** [comment]
Ah, the translations... Let me file a separate issue for them (https://github.com/rpm-software-management/dnf5/issues/1351).

As for the documentation - it's build from interface xml file. I have a PR to fix this - https://github.com/rpm-software-management/dnf5/pull/1352 which also contains first draft of the xml file.

**Comment by m-blaha** [comment]
PR https://github.com/rpm-software-management/dnf5/pull/1352 should enhance groups listing:

- adds Comps.Group interface to the doc (see https://dnf5.readthedocs.io/en/latest/dnf_daemon/dnf5daemon_dbus_api.8.html#org.rpm.dnf.v0.comps.Group)
- removes duplicities (installed/available in repo) from the output
- adds more filtering options (with_hidden, scope (all, installed, available), contains_pkgs)
