### ISSUE TITLE
dbus/interfaces/org.rpm.dnf.v0.Base.xml misnames repo_load_end signal

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1146]
according to what it's written on the comment and into dbus.hpp the signal should be named [download_end](https://github.com/rpm-software-management/dnf5/blob/main/dnf5daemon-server/dbus/interfaces/org.rpm.dnf.v0.Base.xml#L97) into org.rpm.dnf.v0.Base.xml and not repo_load_end

**Comment by ppisar** [comment]
Yes. This is an omission from a7036588575e3e15e5e62d28d3517305154a8b0a commit.

**Comment by anaselli** [comment]
Sorry if i bother for this issue again, but i noticed that also return value error on comment and message into xml are different.
```
<!--
        download_end:
        @session_object_path: object path of the dnf5daemon session
        @download_id: unique id of downloaded object (repo or package)
        @status: libdnf5::repo::DownloadCallbacks::TransferStatus (0 - successful, 1 - already exists, 2 - error)
        @error: error message in case of failed download

        Downloading has ended.
    -->
   <signal name="download_end">
        <arg name="session_object_path" type="o" />
        <arg name="download_id" type="s" />
        <arg name="status" type="i" />
        <arg name="message" type="s" />
    </signal>
```

**Comment by anaselli** [comment]
And if i'm not mistaken there is another error:

`const char * const SIGNAL_DOWNLOAD_MIRROR_FAILURE = "download_mirror_failure";`

```
<!--
        mirror_failure:
        @session_object_path: object path of the dnf5daemon session
        @download_id: unique id of downloaded object (repo or package)
        @message: an error message
        @url: URL being downloaded
        @metadata: For repository metadata download contains metadata type

        Mirror failure during the download.
    -->
    <signal name="mirror_failure">
        <arg name="session_object_path" type="o" />
        <arg name="download_id" type="s" />
        <arg name="message" type="s" />
        <arg name="url" type="s" />
        <arg name="metadata" type="s" />
    </signal>
```
And if I may, I'd suggest to call message or error in both signal for consistency.

**Comment by m-blaha** [comment]
Thanks for reporting it!
I've checked it and all mentioned additional errors are already fixed. I've done some revising of introspection files lately.
