### ISSUE TITLE
Manual page for dnf.conf should document system_cachedir

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#1150]
https://dnf5.readthedocs.io/en/latest/misc/caching.7.html#caching-misc-ref-label

Relates: https://bugzilla.redhat.com/show_bug.cgi?id=2256945

**Comment by pkratoch** [comment]
Yes, it's missing in dnf5.conf: https://dnf5.readthedocs.io/en/latest/dnf5.conf.5.html#main-options
Also, the `cachedir` option says the default is `/var/cache/libdnf5`, which should be the default for `system_cachedir` instead.

**Comment by AdamWill** [comment]
Yes, this just beat me up pretty hard trying to figure out why Kiwi image builds fail with dnf5. Please fix.

**Comment by kontura** [comment]
The `system_cachedir` was added to dnf5.conf in https://github.com/rpm-software-management/dnf5/pull/1618.
