### ISSUE TITLE
dnf5-5.1.11 FTBFS in openSUSE due to msgmerge failure

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/dnf5#1158]
I tried to build dnf5-5.1.11, but it fails due to a msgmerge failure:

```
[   24s] [  1%] Generating sv.gmo
[   24s] cd /home/abuild/rpmbuild/BUILD/dnf5-5.1.11/build/libdnf5-cli/po && /usr/bin/msgmerge --quiet --update --backup=none -s /home/abuild/rpmbuild/BUILD/dnf5-5.1.11/build/libdnf5-cli/po/sv.po /home/abuild/rpmbuild/BUILD/dnf5-5.1.11/libdnf5-cli/po/libdnf5-cli.pot
[   24s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.11/build/libdnf5-cli/po/sv.po: warning: Charset "CHARSET" is not a portable encoding name.
[   24s]                                                                              Message conversion to user's charset might not work.
[   24s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.11/build/libdnf5-cli/po/sv.po:124: duplicate message definition...
[   24s] /home/abuild/rpmbuild/BUILD/dnf5-5.1.11/build/libdnf5-cli/po/sv.po:3: ...this is the location of the first definition
[   24s] /usr/bin/msgmerge: found 1 fatal error
[   24s] make[2]: *** [libdnf5-cli/po/CMakeFiles/translations_2.dir/build.make:84: libdnf5-cli/po/sv.gmo] Error 1
[   24s] make[2]: Leaving directory '/home/abuild/rpmbuild/BUILD/dnf5-5.1.11/build'
[   24s] make[1]: *** [CMakeFiles/Makefile2:1608: libdnf5-cli/po/CMakeFiles/translations_2.dir/all] Error 2
```

**Comment by Conan-Kudo** [comment]
Full build log: [dnf5-5.1.11-openSUSE_Factory-build.log.txt](https://github.com/rpm-software-management/dnf5/files/13907517/dnf5-5.1.11-openSUSE_Factory-build.log.txt)

Sources: https://build.opensuse.org/package/show/system:packagemanager:dnf/dnf5

**Comment by ppisar** [comment]
I confirm that libdnf5-cli/po/sv.po file is invalid since:

~~~~
commit 22be22bdf2296446db4ee59a5146f3188136d17d
Author: GitHub Workflow <github-actions@github.com>
Date:   Thu Jan 11 13:02:52 2024 +0000

    Update translations from weblate
~~~~

The broken file contains duplicate messages at the end.

**Comment by ppisar** [comment]
This broken file is copied from https://github.com/rpm-software-management/dnf5-l10n repository and there the libdnf5-cli/sv.po file was broken with:

~~~~
commit c035e03cb554497a16a79906a8427e03811984be
Author: Rafael Fontenelle <rafaelff@gnome.org>
Date:   Thu Jan 11 11:54:12 2024 +0100

    Added translation using Weblate (Swedish)
~~~~

Commits into dnf5-l10n repository are performed by <https://translate.fedoraproject.org/projects/dnf5/libdnf5-cli/sv/> web service. It seems that the service can produce files invalid from GNU gettext msgmerge point of view and we blindly accept all files.

**Comment by ppisar** [comment]
Something somewhere should run `msgfmt --check -o /dev/null libdnf5-cli/sv.po` to catch there errors.

**Comment by Conan-Kudo** [comment]
Probably should be done for _all_ locales so we don't hit this elsewhere.

**Comment by ppisar** [comment]
I uploaded a new file to the web service without any effect. Then I tried pushing to dnf5-cli repository, but I don't have the permissions.

@m-blaha, you are admin on Weblate. Can you fix it? We need this fix <https://github.com/rpm-software-management/dnf5-l10n/pull/1>.

**Comment by ppisar** [comment]
Indeed.

**Comment by inknos** [comment]
@Conan-Kudo, since you are building dnf5 in SUSE, would you like to have a new tarball or are you ok with patching downstream? I am patching dnf5 downstream, but I am also ok to rebase to a new release

**Comment by Conan-Kudo** [comment]
> @Conan-Kudo, since you are building dnf5 in SUSE, would you like to have a new tarball or are you ok with patching downstream? I am patching dnf5 downstream, but I am also ok to rebase to a new release

I would prefer a new release, please.

**Comment by Conan-Kudo** [comment]
@inknos I would prefer a new release please.
