### ISSUE TITLE
Fix string's plural forms in libdnf5 transaction

### ISSUE THREAD

**Issue by rffontenelle** [rpm-software-management/dnf5#1171]
https://github.com/rpm-software-management/dnf5/blob/b2eb54aaf17e8f92f93c103260812dcbc8c33052/libdnf5/base/transaction.cpp#L1053

The above sentence is available for translation in Fedira Weblate and the plural of `package(s)` in other languages might not be possible like that.

Please consider make use of ngettext to make a plural-form string.

Some references:
- [Plurals in GNOME Wiki](https://wiki.gnome.org/TranslationProject/DevGuidelines/Plurals)
- [Plural forms in GNU Gettext docs](https://www.gnu.org/software/gettext/manual/html_node/Plural-forms.html)

**Comment by ppisar** [comment]
This was partially improved with commit a889d098391430412c5d60c3f250ebf4fcb5327b. But the current code is still insufficient.
