### ISSUE TITLE
Suggestions for dnf5 results like `dnf.subject.Subject(pkg_spec).get_best_query(self.dbo.sack)`

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#1212]
So, we've run into a small glitch with the new dnf5 version of Lorax's package matching code (https://github.com/weldr/lorax/blob/master/src/pylorax/ltmpl.py#L214) when a package no longer has a matching name, just a provides. We hit this with the move from `wget` to `wget2-wget`. Currently I'm using `.filter_name` which of course doesn't find any matches.

There is also `.filter.provides` but that returns ALL of the the things providing the name, which causes problems for things like `curl` which also has `curl-minimal` providing `curl`.

In the old version of Lorax I was using `dnf.subject.Subject(pkg_spec).get_best_query(self.dbo.sack)` to find the packages which worked fine, preferring matching names to provides, but also falling back to a provide if the name wasn't found.

I could possibly do this manually, if `.filter_name` fails to return a result then try `.filter_provides`, but I am wondering if there is an actual recommendation for switching from the old API to the new  for this situation :)

**Comment by j-mracek** [comment]
I think that you are looking for:
```
    /// Resolve spec according to provided settings. It tests whether spec is NEVRA type, provide, file or binary.
    /// It returns only the first match type. If spec has a match as NEVRA and provide type it only keeps matches with
    /// the first tested type (NEVRA).
    // TODO(jmracek) return std::pair<bool, std::unique_ptr<libdnf5::rpm::Nevra>>
    // @replaces libdnf/sack/query.hpp:method:std::pair<bool, std::unique_ptr<Nevra>> filterSubject(const char * subject, HyForm * forms, bool icase, bool with_nevra, bool with_provides, bool with_filenames);
    std::pair<bool, libdnf5::rpm::Nevra> resolve_pkg_spec(
        const std::string & pkg_spec, const libdnf5::ResolveSpecSettings & settings, bool with_src);
```

**Comment by bcl** [comment]
Awesome! Thanks, that also lets me delete my special code for handling comparisons.
This function could use a bit more documentation, I somehow missed exactly how useful it could be in previous readings of the docs :)
