### ISSUE TITLE
Support separate cache directories for repodata and packages

### ISSUE THREAD

**Issue by DaanDeMeyer** [rpm-software-management/dnf5#1214]
`apt`, `zypper` and `pacman` all use separate cache directories for their repodata and packages. I'd like dnf to also support this. When building images, this allows me to give each image its own snapshot of the repodata while still having all of them share the package cache.

This could be solved by introducing a new option `package_cachedir` that is used to store packages.

**Comment by DaanDeMeyer** [comment]
This would be easier if the cache subdirectories were inverted. If instead of e.g. `/var/cache/libdnf5/fedora-xxx/packages` you had `/var/cache/libdnf5/packages/fedora-xxx` then relocating only that directory would be trivial.

**Comment by j-mracek** [comment]
May I ask you to try `destdir` configuration option. This path overrides package cache dir for all repositories.
`dnf --setopt=destdir=<path> install acpi`.

**Comment by DaanDeMeyer** [comment]
@j-mracek Hmm that would not maintain the rpms per repository anymore right? So if multiple repositories provided the same rpm they would override each other?

For now I'm using bind mounts to mount the packages directories from the shared cache into the snapshot directory so all rpms are still written to the shared cache.

**Comment by j-mracek** [comment]
Correct, then packages are not stored per repository. Anyway it is not difficult to map DNF/DNF5 cache panther to your requested pattern by a simple script. From your description I think that the issue has a low priority.

**Comment by DaanDeMeyer** [comment]
Yeah I can get by with bind mounts, let's close this
