### ISSUE TITLE
Running transactions CLI (storing transactions, replaying transactions, offline transactions)

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#1224]
In old [dnf](https://github.com/rpm-software-management/dnf) there was `offline-upgrade`, `history store` and `history replay`.
In dnf5 we would like to extend this functionality and make it more general, namely any transaction could be stored (not just history transactions) and replayed even offline.

The question is how should the CLI look like.

Proposed ideas:
- Any transaction could be stored using a `--store <path-to-file>` option.
- For running offline transactions a convenient `--offline`/`--postponed` option could be used. This would store the transaction internally and it would be automatically used after `dnf5 offline reboot` or perhaps the reboot would be done immediately?
- For replaying transactions stored to a file we could use something like `dnf5 do` or `dnf5 run` (Possibly related: https://github.com/rpm-software-management/dnf5/issues/1223). This command could also serve as a replacement for `dnf shell` as it would allow multiple operations per transaction. Alternatively simple `dnf5 replay <path-to-file>` could replay just a single file.

Any other ideas are welcome.

Related issues: https://github.com/rpm-software-management/dnf5/issues/258 https://github.com/rpm-software-management/dnf5/issues/999

**Comment by Conan-Kudo** [comment]
This is partly what the [txnupd libdnf plugin](https://code.opensuse.org/microos/libdnf-plugin-txnupd) did. It'd be nice to have more of that functionality integrated right into dnf5 so that the only thing that needs to be worked out in a plugin is the btrfs snapshot and retargeting part.

**Comment by evan-goode** [comment]
> Any transaction could be stored using a --store <path-to-file> option.

+1 

> For running offline transactions a convenient --offline/--postponed option could be used. This would store the transaction internally and it would be automatically used after dnf5 offline reboot or perhaps the reboot would be done immediately?

I like `--offline` better; `--postpone`/`--postponed` is a little unclear to me. "Offline updates" is what they are called by [systemd](https://www.freedesktop.org/software/systemd/man/latest/systemd.offline-updates.html).

I think it's also best to split the reboot step to a different command, like how system-upgrade currently works, in case the user doesn't want to update immediately. `--offline` should be roughly equivalent to setting `--store /usr/lib/sysimage/libdnf5/offline/offline-transaction.json` and `--setopt=cachedir=/usr/lib/sysimage/libdnf5/offline`. Any necessary RPMs would get downloaded to that directory and the transaction would be run with the `test` tsflag.

Right now, I'm imagining renaming the `system-upgrade` command (https://github.com/rpm-software-management/dnf5/issues/1052) to `offline` and making `system-upgrade` aliases to the `offline` commands. The flow would be:

```
dnf5 install --offline hello
dnf5 offline status # maybe implement this subcommand to show the currently-staged offline transaction?
dnf5 offline reboot
dnf5 offline upgrade # not run directly by the user, but by `dnf5-system-upgrade.service` in the "offline" environment. Could be renamed from "upgrade" to be more general.

dnf5 offline log   # view journald logs 
dnf5 offline clean # clean out /usr/lib/sysimage/libdnf5/offline
```

`dnf5 system-upgrade download` needs to have its own logic to (1) check that the user has specified a new `--releasever` and (2) to set the `target_releasever` and `system_releasever` variables in the offline-transaction state file. But the other `system-upgrade` subcommands can be aliases for a more general `offline` command.


> For replaying transactions stored to a file we could use something like dnf5 do or dnf5 run

I like `dnf5 run </path/to/transaction.json>`. `replay` implies that the transaction has already been "played" before, which may not be true. I think it's a separate but related issue how we might create serialized transactions that have multiple operations. The transaction could also be run offline: `dnf5 run --offline </path/to/transaction.json>`.

**Comment by ppisar** [comment]
> dnf5 install --offline hello
dnf5 offline status # maybe implement this subcommand to show the currently-staged offline transaction?

I guess "dnf5 install --offline" would replace any previously staged installation. That should be clearly communicated to the user when invoking the command for the second time.

**Comment by gregory-lee-bartholomew** [comment]
RFE: Have a config file option to make --offline updates use kexec (when possible) instead of doing a full hardware reset. (just my two cents)

**Comment by evan-goode** [comment]
> RFE: Have a config file option to make --offline updates use kexec (when possible) instead of doing a full hardware reset. (just my two cents)

Good suggestion, I think this may be as simple as calling `systemctl kexec` instead of `systemctl reboot` if I'm not mistaken?

**Comment by gregory-lee-bartholomew** [comment]
It might be slightly more complicated if what is being updated is the kernel and you want to reboot into the new one. In that case, you'd have to call `kexec -l ...` before calling `systemctl kexec`. I haven't used kexec since it was integrated into systemd, so I'm not sure of all the details myself.
