### ISSUE TITLE
dnf5 repolist/repoinfo: docs gaps

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#1225]
- "repolist" and "repoinfo" are not mentioned in dnf5 man page
- there are no dnf5-repolist and dnf5-repoinfo man pages
- these commands are probably obsoleted by "dnf5 repo list|info" but it's not mentioned anywhere
- missing info on https://dnf5.readthedocs.io/en/latest/changes.html (except of -v option of repolist)

**Comment by ppisar** [comment]
"repolist" and "repoinfo" and aliases. Now, we do not provide manual pages for aliases as aliases are usually deprecated forms of invocation. Though I recognize that changes page should list them.

**Comment by glum23** [comment]
The behavior of "repo list (repolist)" in dnf5 differs from dnf4. It used to provide "No repositories available" message on stderr when there were no repositories available while it does not provide anything now. If intended, it should be documented on the "changes" page.
