### ISSUE TITLE
do not infer $releasever from host when doing installroots

### ISSUE THREAD

**Issue by cgwalters** [rpm-software-management/dnf5#1238]
I switched something I was doing from CentOS7 to Fedora, and was really confused by why something I was looking at was really old, until I noticed it said `fc7`, i.e. I was pulling Fedora 7 content.

We should detect this an error unless the system has provided a releasver.

**Comment by j-mracek** [comment]
According to my investigation in code, the issue is not valid anymore. It is enough to set `dnf_context_get_install_root(DnfContext *context)` or override for detection - `const gchar *
dnf_context_get_source_root(DnfContext *context)`. 

I also believe that the issue is not valid for DNF5. 

see:
```
$ dnf5 --dump-variables 
$ dnf5 --dump-variables --installroot /tmp

```
