### ISSUE TITLE
libdnf doesn't respect DNF plugins' post transaction hooks

### ISSUE THREAD

**Issue by liferooter** [rpm-software-management/dnf5#1240]
### Description of problem
libdnf ignores DNF plugins such as dnf-plugin-snapper and dnf-plugin-post-transaction-actions. It is critical because PackageKit uses libdnf, so upgrades via PackageKit don't run user-defined post-transaction actions.

### Software versions
**OS:** Fedora Linux 34
**libdnf:** 0.62.0

**Comment by jan-kolarik** [comment]
This is now implemented by the libdnf actions plugin in dnf5. Closing this.
