### ISSUE TITLE
"dnf5 list" searches case-sensitively while dnf4 does not

### ISSUE THREAD

**Issue by ilikelinux69** [rpm-software-management/dnf5#1259]
Example:

`dnf5 list '*exif*'` does not display `perl-Image-ExifTool.noarch`

Is this intentional, as in dnf4 it gets listed?

I just think we should have a consistent output for same search schemes in all options like dnf search, dnf repolist etc. 

See discussion:
https://discussion.fedoraproject.org/t/dnf-list-howto-display-case-insensitive-packages/105730/4

**Comment by ppisar** [comment]
I would say it's on purpose. "dnf5 list" searches in package names and package names are case sensitive. It's a glob the same as shell glob for file names is also case sensitive. See dnf5-specs(5) manual page. Case insensitive search is provided in "dnf5 search" command which searches among more texts than the package name.

**Comment by ppisar** [comment]
I discussed this issue with other DNF5 developers, and the resolution is that "dnf5 list" should behave insensitively.
