### ISSUE TITLE
Adding additional command for Modularity

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#126]
- [x] #648
- [x] #649
- [x] #650

**Comment by pkratoch** [comment]
Related (already merged) PRs:
https://github.com/rpm-software-management/dnf5/pull/387 - modules: Change State to set and get the whole ModuleState
https://github.com/rpm-software-management/dnf5/pull/401 - modules: Add ModuleDB to store the runtime states of all modules
These are needed to manage module states to make modules enabled, disabled or neither.

**Comment by pkratoch** [comment]
Module enable PR: https://github.com/rpm-software-management/dnf5/pull/606

**Comment by j-mracek** [comment]
According to description the scope of the issue is resolved.
