### ISSUE TITLE
The download progress of multiple packages is flickering and not smooth

### ISSUE THREAD

**Issue by Rid1FZ** [rpm-software-management/dnf5#1263]
The progress always flickers which is causing eye pain. This is not an issue in dnf4. In dnf4, the update in progress is quite seamless.

**Comment by ppisar** [comment]
Could you describe when you observe the flickering? What command do you execute, what is being displayed (package download progessbar, transaction log), what temrinal do you use, what dnf5 version do you use? Can you record it with "script" tool ("script -T /tmp/timing /tmp/log", perform the command, exit, and send us the two files)?

I remember seeing the flickering, but that was a long time ago. For me "dnf5 download firefox" command in xterm with the latest developmental dnf5 in Fedora 41 does not show any flickerring. It redraws the download progressbar at 8-Hz frequency.

The flickering would either mean that your terminal is very slow, or DNF5 makes a long pause between erasing a line the printing the updated line.

Maybe simply deceasing the redraw frequency in DNF5 to 1 Hz could help.

**Comment by Rid1-fz-06** [comment]
@ppisar I ran the command to install Kmail. The flickering only happens during the download portion when the screen updates continuously ( the progressbar and the portion updates ). This is the same for any command that downloads any package ( like `dnf5 download`, `dnf5 upgrade`, `dnf5 install` ). I am running the latest dnf5 package from Fedora's repository. The output of the command `dnf5 --version` is given below:
```
dnf5 version 5.1.12
dnf5 plugin API version 1.0
libdnf5 version 5.1.12
libdnf5 plugin API version 1.0

Loaded dnf5 plugins:
  name: builddep
  version: 1.0.0
  API version: 1.0

  name: changelog
  version: 1.0.0
  API version: 1.0

  name: config-manager
  version: 0.1.0
  API version: 1.0

  name: copr
  version: 0.1.0
  API version: 1.0

  name: needs_restarting
  version: 1.0.0
  API version: 1.0

  name: repoclosure
  version: 1.0.0
  API version: 1.0
```

I am currently using Fedora Linux 39 ( Installed manually from netinst iso ). I am using alacritty terminal: `alacritty 0.13.1`. I am currently on KDE Plasma: `plasmashell 5.27.10`, But I noticed the same issue in Fedora Workstation with Gnome.

**Comment by ppisar** [comment]
Thanks for the details. I can reproduce it from the files you recorded in my xterm on my 60-Hz monitor. The flickering is visible when "large" amount (e.g. 10) of packages are downloaded in parallel. Then all the 10 lines are rewritten from the first column to the last one. With a default speed of replaying it's slightly disturbing. If I play it at 0.01 speed it becomes significantly visible.

I tried to replay it in Gnome terminal on Wayland on a better monitor and there the flickering is not visible at all at the normal playback speed.

Can you tell us what refresh frequency and response delay your monitor has? Maybe changing the setting could help you. Modern monitors have various improvement modes and some of them could mask the problem for you.

We will look at how to optimize redrawing the progress bar, but frankly, now it's not a top priority bug of among all the DNF5 bug reports.

**Comment by Rid1-fz-06** [comment]
@ppisar thanks for your concern. I will wait until Fedora 41 for this issue to be fixed. I think I should use dnf4 for now. Thanks again!!!
