### ISSUE TITLE
`std::format` is unavailable in GCC < 13 (breaks Mageia builds)

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/dnf5#1269]
Mageia 9 and Cauldron are at GCC 12 currently, and 2427a336a952f633307f4776a875dab06b10b2c6 introduced usage of `std::format`. Prior to inclusion in GCC 13, it was [available through Boost](https://www.boost.org/doc/libs/1_84_0/libs/format/doc/format.html).

If the minimum GCC version is raised, then this becomes unbuildable on Mageia. Alternatively, either the usage of `std::format` is removed or fall back to `boost::format` when `std::format` is not available.

**Comment by Conan-Kudo** [comment]
Alternatively, replace usage of `std::format` with `fmt` usage, which we already use elsewhere.

**Comment by ppisar** [comment]
I confirm GCC added the support in 13.1 <https://gcc.gnu.org/onlinedocs/libstdc++/manual/status.html#status.iso.2020>.
