### ISSUE TITLE
Document changes in dnf5-plugin-automatic files between DNF 4 and 5

### ISSUE THREAD

**Issue by seinolab** [rpm-software-management/dnf5#1289]
The following files included in `dnf-automatic` are not present in `dnf5-plugin-automatic`.

- /etc/dnf/automatic.conf
- /usr/lib/systemd/system/dnf-automatic-download.service
- /usr/lib/systemd/system/dnf-automatic-download.timer
- /usr/lib/systemd/system/dnf-automatic-install.service
- /usr/lib/systemd/system/dnf-automatic-install.timer
- /usr/lib/systemd/system/dnf-automatic-notifyonly.service
- /usr/lib/systemd/system/dnf-automatic-notifyonly.timer

**Comment by ppisar** [comment]
The differences are on purpose:

For automatic.conf location see 5b9325000cf5f65ba67e6b7a5670f7a33826e8a6.
For sysmted files, see 5b81769b799036aecfd869204bf2b1ef2f072dd9.

Do you have any functional problems with the new layout?

**Comment by ppisar** [comment]
I will assume there is no functional problem. I will change this issue into a request to document the difference between DNF4 and DNF5 in doc/changes.rst.

**Comment by ppisar** [comment]
@m-blaha, you ported the automatic plugin. Could you document the changes in doc/changes.rst?

**Comment by m-blaha** [comment]
> @m-blaha, you ported the automatic plugin. Could you document the changes in doc/changes.rst?

Yes, will do that.

**Comment by jan-kolarik** [comment]
Please also include information about how the existing dnf4 automatic configuration files can be migrated to the dnf5 layout.
