### ISSUE TITLE
Document replacement of alias command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#131]
**Command:** ```alias```
  - We have another way how to handle aliases in DNF therefore I am not sure whether it make sense to keep the command around

- [ ] Document how to use aliases in DNF5
- [ ] Document changes to DNF4

Allows the user to define and manage a list of aliases (in the form ```<name=value>```), which can be then used as dnf commands to abbreviate longer command sequences. For examples on using the alias command, see [Alias Examples](https://dnf.readthedocs.io/en/latest/command_ref.html#alias-examples-label). For examples on the alias processing, see [Alias Processing Examples](https://dnf.readthedocs.io/en/latest/command_ref.html#alias-processing-examples-label).

To use an alias (name=value), the name must be placed as the first “command” (e.g. the first argument that is not an option). It is then replaced by its value and the resulting sequence is again searched for aliases. The alias processing stops when the first found command is not a name of any alias.

In case the processing would result in an infinite recursion, the original arguments are used instead.

Also, like in shell aliases, if the result starts with a ```\```, the alias processing will stop.

All aliases are defined in configuration files in the ```/etc/dnf/aliases.d/``` directory in the [aliases] section, and aliases created by the alias command are written to the ```USER.conf``` file. In case of conflicts, the ```USER.conf``` has the highest priority, and alphabetical ordering is used for the rest of the configuration files.

Optionally, there is the ```enabled``` option in the ```[main]``` section defaulting to True. This can be set for each file separately in the respective file, or globally for all aliases in the ALIASES.conf file.

```dnf alias [options] [list] [\<name\>...]```

List aliases with their final result. The ```[<alias>...]``` parameter further limits the result to only those aliases matching it.
dnf alias [options] add <name=value>...

Create new aliases.
```dnf alias [options] delete <name>...```

Delete aliases.

**Alias Examples**

```dnf alias list```

Lists all defined aliases.

```dnf alias add rm=remove```

Adds a new command alias called rm which works the same as the remove command.

```dnf alias add upgrade="\upgrade --skip-broken --disableexcludes=all --obsoletes"```

Adds a new command alias called upgrade which works the same as the upgrade command, with additional options. Note that the original upgrade command is prefixed with a \ to prevent an infinite loop in alias processing.

**Alias Processing Examples**

If there are defined aliases ```in=install``` and ```FORCE="--skip-broken --disableexcludes=all"```:

- ```dnf FORCE in``` will be replaced with ```dnf --skip-broken --disableexcludes=all install```
- ```dnf in FORCE``` will be replaced with ```dnf install FORCE``` (which will fail)

If there is defined alias ```in=install```:

- ```dnf``` in will be replaced with ```dnf install```
- ```dnf --repo updates in``` will be replaced with ```dnf --repo updates in``` (which will fail)

**Comment by j-mracek** [comment]
We need to document how aliases are created in DNF5. The functionality is already implemented. See https://github.com/rpm-software-management/dnf5/blob/main/dnf5/config/usr/share/dnf5/aliases.d/compatibility.conf
