### ISSUE TITLE
bash-completion-2.12 changed API, breaking DNF5 completion: __reassemble_comp_words_by_ref: command not found

### ISSUE THREAD

**Issue by nuqleo** [rpm-software-management/dnf5#1326]
Broken bash autocompletion in dnf5-5.1.15-2.fc41.x86_64
```
# dnf5 -bash: __reassemble_comp_words_by_ref: command not found
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stoi
```

**Comment by ppisar** [comment]
What bash-completion package do you have installed?

**Comment by nuqleo** [comment]
bash-completion-2.12-1.fc41.noarch

**Comment by nuqleo** [comment]
After downgrading to bash-completion-2.11-15.fc41.noarch autocompletion works.

**Comment by evgnor86** [comment]
Hi! What about solution for bash-completion-2.12, it's realy to do?
Thanks a lot! dnf5 - the best!!!

**Comment by ppisar** [comment]
@jrohel, could you look at it? It's quite annoying.
