### ISSUE TITLE
Implement check command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#133]
- [ ] **Command:** ```check```

- [ ] ```--dependencies```
- [ ] ```--duplicates```
- [ ] ```--obsoleted```
- [ ] ```--provides```

```dnf [options] check [--dependencies] [--duplicates] [--obsoleted] [--provides]```

Checks the local packagedb and produces information on any problems it finds. You can limit the checks to be performed by using the ```--dependencies```, ```--duplicates```, ```--obsoleted``` and ```--provides``` options (the default is to check everything).

**Comment by j-mracek** [comment]
It would be interesting to investigate whether RPM is providing such tests. If the functionality is in RPM then direct usage without DNF will help to resolve the use case when DNF is broken. If RPM gets broken then there is no way how to resolve it.

**Comment by ppisar** [comment]
What does "dnf check" do?
If "dnf check --duplicates" reports packages which are installed in multiple versions, e.g. after a crashed RPM transaction when both PACKAGE-1 and PACKAGE-2 are left, then there must be more logic because of installonly (kernel) packages. Although "rpm --dupes" does not report "kernel" for me. Maybe it does something else.

**Comment by jrohel** [comment]
@ppisar 
`--duplicites` lists duplicate installed packages (same name and architecture), installonly packages should be excluded from the list.
An example on my intentionally damaged system:
```
# dnf check --duplicates 
pipewire-0.3.80-1.fc39.x86_64 is a duplicate with pipewire-0.3.84-3.fc39.x86_64
pipewire-pulseaudio-0.3.80-1.fc39.x86_64 is a duplicate with pipewire-pulseaudio-0.3.84-3.fc39.x86_64
Error: Check discovered 2 problem(s)
```

**Comment by jrohel** [comment]
I don't know what exactly the purpose of "--provides" is. It tests that the "provides" of the installed packages are really installed. Is the goal to detect errors in the implementation? Do we really want this test here?

**Comment by ppisar** [comment]
Maybe --provides attempts to check that your system does not have installed package A, and package B which provides A. Like a check for a packaging bug when package B is replacing package A, but the packager forgot to add "Obsoletes: A" to B.

**Comment by j-mracek** [comment]
I believe that the test with the option `--provides` is related to encoding in `Python2`, when provides contained a garbage. If it is the case then we don't to deliver it.

**Comment by j-mracek** [comment]
All scenarios in CI-DNF-STACK test for empty output with `check --provides` option. Therefore they are not much helpful.
