### ISSUE TITLE
Document --version option

### ISSUE THREAD

**Issue by ppisar** [rpm-software-management/dnf5#1337]
dnf5(8) manual is missing --version option. It should be mention that it lists successfully loaded modules (discovered in isse #1335). It should also be mention that it is a terminating option, i.e. the program exits without performing any commands.

**Comment by jan-kolarik** [comment]
Hi Petr, I have already covered this during working on #644. Will link this issue when publishing the PR, which should be tomorrow.

**Comment by glum23** [comment]
In addition to that, `dnf5 --version ` significantly differs from `dnf --version` so it'd be nice to document it in https://dnf5.readthedocs.io/en/latest/changes.html
