### ISSUE TITLE
dnf5 offline _execute should return 0 exit code if /system-update symlink does not point to DNF5 datadir

### ISSUE THREAD

**Issue by gnw3** [rpm-software-management/dnf5#1340]
dnf5 was installed from the `dnf5-unstable copr repo ` (just to see what options are available).

```
% journalctl -b -3 -g dnf5 --no-hostname |cat
Mar 21 20:25:12 systemd[1]: Starting dnf5-offline-transaction.service - Offline upgrades/transactions using DNF 5...
Mar 21 20:25:13 dnf5[784]: Error reading state: Error reading offline state file.: (2) - No such file or directory [/usr/lib/sysimage/libdnf5/offline/offline-transaction-state.toml]. Rerun the command you used to initiate the offline transaction, e.g. `dnf5 system-upgrade download [OPTIONS]`.
Mar 21 20:25:13 systemd[1]: dnf5-offline-transaction.service: Main process exited, code=exited, status=1/FAILURE
Mar 21 20:25:13 systemd[1]: dnf5-offline-transaction.service: Failed with result 'exit-code'.
Mar 21 20:25:13 systemd[1]: Failed to start dnf5-offline-transaction.service - Offline upgrades/transactions using DNF 5.
Mar 21 20:25:13 systemd[1]: dnf5-offline-transaction.service: Triggering OnFailure= dependencies.
Mar 21 20:25:13 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf5-offline-transaction comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
Mar 21 20:25:13 systemd[1]: Starting dnf5-offline-transaction-cleanup.service - Offline upgrade/transaction using DNF 5 failed...
Mar 21 20:25:13 systemd[1]: dnf5-offline-transaction-cleanup.service: Deactivated successfully.
Mar 21 20:25:13 systemd[1]: Finished dnf5-offline-transaction-cleanup.service - Offline upgrade/transaction using DNF 5 failed.
Mar 21 20:25:13 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf5-offline-transaction-cleanup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Mar 21 20:25:13 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=dnf5-offline-transaction-cleanup comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
```

A comment to [the Fedora Discussion Post](https://discussion.fedoraproject.org/t/dnf-system-upgrade-f38-to-f39-workstation-attempts-to-use-dnf5-and-fails/109219/):

"It looks like dnf5 didn’t implement the [systemd offline update protocol](https://www.freedesktop.org/software/systemd/man/latest/systemd.offline-updates.html) correctly, specifically:"

>5. As the first step, an update service should check if the `/system-update` or `/etc/system-update` symlink points to 
>the location used by that update service. In case it does not exist or points to a different location, the service must 
>exit without error. It is possible for multiple update services to be installed, and for multiple update services to be 
>launched in parallel, and only the one that corresponds to the tool that created the symlink before reboot should 
>perform any actions. It is unsafe to run multiple updates in parallel.

Removing dnf5 allowed the update to go thru.

**Comment by ppisar** [comment]
Support for system-upgrade was added to DNF5 in issue #1052 3 days ago. I guess you had dnf5 build older than commit e8c59014fd84929e392bae0291cae7b0d8c0c420.

Do you know what dnf5 build you used for the upgrade?

**Comment by ppisar** [comment]
I see. Thanks for pointing to the code. @evan-goode, can you look at it?

**Comment by evan-goode** [comment]
> I see. Thanks for pointing to the code. @evan-goode, can you look at it?

Yes, this will be fixed by https://github.com/rpm-software-management/dnf5/pull/1334.
