### ISSUE TITLE
libdnf actions plugin: possibility to modify per-repository configuration

### ISSUE THREAD

**Issue by t184256** [rpm-software-management/dnf5#1345]
It is possible to output `conf.<option_name>=<value>` from .actions to alter DNF configuration, but it'd also be nice to be able to override repository configuration that way, similarly to how it was possible to, say,

    for name, repo in self.base.repos.items():
        repo.<option_name> = <value>

Would probably also be useful to provide a `${repository_names}` to iterate over.

**Comment by jmontleon** [comment]
I am using and was looking at what it would take to rewrite this plugin. It's pretty straightforward, but I think this is the functionality that's missing to make it possible.

https://github.com/michel-ludwig/dnf-local-mirror-detection/blob/master/src/local-mirror-detection.py

**Comment by jrohel** [comment]
@t184256
I prepared a PR https://github.com/rpm-software-management/dnf5/pull/1539 which adds support for per-repository configuration modification.
Also adds `${conf.<repoid_pattern>.<option_name>[=<value_pattern>]}` substitution. This is much more powerful than the proposed `${repository_names}`.
More information in PR.

I'm also working on an even more flexible interface https://github.com/rpm-software-management/dnf5/issues/1538 . But currently this work has a low priority.
