### ISSUE TITLE
dnf5daemon: Advisory::list D-Bus method does not filter

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#1349]
I'd like to get only advisories, which are updates for the user, severity is critical and I do not care of bz nor CVE. In python (modified upgrades_with_severities.py):
```py
options = {
    "advisory_attrs": [
                "severity",
                "collections",
            ],
    "availability": "updates",
    "severity": "critical",
    "with_bz": False,
    "with_cve": False,
}
``` 

Issues:
* I get the full list, not only critical advisories
* the returned `severity` has upper-case first letter, aka `None`, `Low`, `Moderate`,... - it's confusing, because the filter value, which is "all lower case"
* there are also a lot of `'applicability': <'unrelated'>` attributes on the packages (maybe all of them, I do not know, my list is huge) - no idea what they mean, I thought it's a typo from the `availability` filter, but probably not.
* I also tried `"availability": "installed",` with the same effect; is this one meant to show already locally installed advisories? That's something I do not care of at the moment (thus I might misuse it) ;)

**Comment by m-blaha** [comment]
The `availability` filter basically follows `--all`, `--available`, `--installed`, and `--updates` options of `dnf5 advisory list` command. So see man dnf5-advisory for details.

There is a bug in the Advisory documentation - the option is actually called `severities` (in plural, as it accepts a list of strings). I will update the documentation accordingly.

Additionally, there is another bug related to case sensitivity - the severity value is stored in advisories in capitalized form. Although the filter is intended to accept lowercase values, it seems that it doesn't. I'll address this issue to ensure the filter works with any capitalization of the values.

To prevent similar issues in the future, I'll also add more tests for dnfdamon advisories.

**Comment by m-blaha** [comment]
So to get what you wanted, you need `severities: ["Critical"]` for now.

**Comment by mcrha** [comment]
It seems the `--updates` is the default. Maybe drop a note about it into the --help and the man page.

**Comment by m-blaha** [comment]
Default availability value is "available", and `--available` is also default for `dnf5 advisory list` command. I've added a note to the documentation.
I fixed the case sensitive filtering and enhanced the documentation in PR https://github.com/rpm-software-management/dnf5/pull/1380.
