### ISSUE TITLE
Implement clean command 

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#135]
- [x] **Command:** ```clean```

Performs cleanup of temporary files kept for repositories. This includes any such data left behind from disabled or removed repositories as well as for different distribution release versions.

- [x] ```dnf clean dbcache```

Removes cache files generated from the repository metadata. This forces DNF to regenerate the cache files the next time it is run.

- [x] ```dnf clean expire-cache```

Marks the repository metadata expired. DNF will re-validate the cache for each repository the next time it is used.

- [x] ```dnf clean metadata```

Removes repository metadata. Those are the files which DNF uses to determine the remote availability of packages. Using this option will make DNF download all the metadata the next time it is run.

- [x] ```dnf clean packages```

Removes any cached packages from the system.

- [x] ```dnf clean all```

Does all of the above.

**Comment by glum23** [comment]
'dnf5 clean <unknown-type>' aborts with core dumped
'dnf5 clean --help' does not provide list of known types
bug  https://bugzilla.redhat.com/show_bug.cgi?id=2192854 has been filed
