### ISSUE TITLE
Implement downgrade command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#137]
- [x] **Command:** ```downgrade```

- [x] **Aliases:** ```dg```
  - Priority low
  - Proposing to implement the alias

```dnf [options] downgrade <package-spec>...```

Downgrades the specified packages to the highest installable package of all known lower versions if possible. When version is given and is lower than version of installed package then it downgrades to target version.

**Comment by j-mracek** [comment]
All features were delivered

**Comment by glum23** [comment]
dnf5 vs. dnf4 difference: when download's argument package does not exist, dnf4 exits with 1 while dnf5 exits with 0, however, it provides a non-empty stderr message. Is it supposed to be OK?

**Comment by jan-kolarik** [comment]
> dnf5 vs. dnf4 difference: when download's argument package does not exist or it is not installed, dnf4 exits with 1 while dnf5 exits with 0, however, it provides a non-empty stderr message. Is it supposed to be OK?

I guess you meant `downgrade` instead of the `download`, but actually there is the same problem as I mentioned in this [comment](https://github.com/rpm-software-management/dnf5/issues/494#issuecomment-1522863111) :slightly_smiling_face: I will try to bring this up on the DNF5 planning meeting.
