### ISSUE TITLE
Implement info command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#141]
- [x] **Command:** ```info```

- [x] **Aliases:** ```if```
  - drop the alias - people must be not lazy to write additional two letters

```dnf [options] info [<package-file-spec>...]```

Lists description and summary information about installed and available packages.

The info command limits the displayed packages the same way as the [list command](https://dnf.readthedocs.io/en/latest/command_ref.html#list-command-label).

This command by default does not force a sync of expired metadata. See also [Metadata Synchronization](https://dnf.readthedocs.io/en/latest/command_ref.html#metadata-synchronization-label).

**Comment by m-blaha** [comment]
Implemented by https://github.com/rpm-software-management/dnf5/pull/298
