### ISSUE TITLE
Where is `<unknown>` coming from in the repository column?

### ISSUE THREAD

**Issue by long-walk** [rpm-software-management/dnf5#1410]
Where is `<unknown>` coming from in the repository column?

_Originally posted by @Conan-Kudo in https://github.com/rpm-software-management/dnf5/issues/1191#issuecomment-2054075767_

This is based from my testing in a virtual system normally you will see the new source.

**Comment by juhp** [comment]
I believe it covers roughly what dnf4 called `@System` or `@commandline` or for package from an disabled repo etc.
