### ISSUE TITLE
Implement install command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#142]
- [x] **Command:** ```install```

- [x] **Aliases:** ```in```
  - priority low

- [x] **Aliases for** [explicit NEVRA matching](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-nevra-matching-explicitly-label): ```install-n```, ```install-na```, ```install-nevra```
  - drop

- [x] **Deprecated aliases:** localinstall
  - drop

```dnf [options] install <spec>...```

Makes sure that the given packages and their dependencies are installed on the system. Each ```<spec>``` can be either a [<package-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-packages-label), or a @[<module-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-modules-label), or a @[<group-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-groups-label). See [Install Examples](https://dnf.readthedocs.io/en/latest/command_ref.html#install-examples-label). If a given package or provide cannot be (and is not already) installed, the exit code will be non-zero. If the ```<spec>``` matches both a @[<module-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-modules-label) and a @[<group-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-groups-label), only the module is installed.

When [<package-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-packages-label) to specify the exact version of the package is given, DNF will install the desired version, no matter which version of the package is already installed. The former version of the package will be removed in the case of non-installonly package.

On the other hand if [<package-spec>](https://dnf.readthedocs.io/en/latest/command_ref.html#specifying-packages-label) specifies only a name, DNF also takes into account packages obsoleting it when picking which package to install. This behaviour is specific to the install command. Note that this can lead to seemingly unexpected results if a package has multiple versions and some older version is being obsoleted. It creates a split in the upgrade-path and both ways are considered correct, the resulting package is picked simply by lexicographical order.

There are also a few specific install commands ```install-n```, ```install-na``` and ```install-nevra``` that allow the specification of an exact argument in the NEVRA format.

See also [Configuration Files Replacement Policy](https://dnf.readthedocs.io/en/latest/command_ref.html#configuration-files-replacement-policy-label).

**Install Examples**

```dnf install tito```

Install the tito package (tito is the package name).

- [x] ```dnf install ~/Downloads/tito-0.6.2-1.fc22.noarch.rpm```

Install a local rpm file tito-0.6.2-1.fc22.noarch.rpm from the ~/Downloads/ directory.

- [x] ```dnf install tito-0.5.6-1.fc22```

Install the package with a specific version. If the package is already installed it will automatically try to downgrade or upgrade to the specific version.

- [x] ```dnf --best install tito```

Install the latest available version of the package. If the package is already installed it will try to automatically upgrade to the latest version. If the latest version of the package cannot be installed, the installation will fail.

- [x] ```dnf install vim```

DNF will automatically recognize that vim is not a package name, but will look up and install a package that provides vim with all the required dependencies. Note: Package name match has precedence over package provides match.

- [x] #490

Install a package directly from a URL.

- [x] ```dnf install '@docker'```

Install all default profiles of module ‘docker’ and their RPMs. Module streams get enabled accordingly.

- [x] ```dnf install '@Web Server'```

Install the ‘Web Server’ environmental group.

- [x] ```dnf install /usr/bin/rpmsign```

Install a package that provides the /usr/bin/rpmsign file.

- [x] ```dnf -y install tito --setopt=install_weak_deps=False```

Install the ```tito``` package (tito is the package name) without weak deps. Weak deps are not required for core functionality of the package, but they enhance the original package (like extended documentation, plugins, additional functions, etc.).

- [x] ```dnf install --advisory=FEDORA-2018-b7b99fe852 \*```

Install all packages that belong to the “FEDORA-2018-b7b99fe852” advisory.

Moved into separate issue:

- [ ] #749

**Comment by Bavuett** [comment]
Hey! I'd like to work on this task: `Install a package directly from a URL`. Is it taken by anyone?

**Comment by j-mracek** [comment]
> Hey! I'd like to work on this task: `Install a package directly from a URL`. Is it taken by anyone?

I've created an issue from the task and you can take it - https://github.com/rpm-software-management/dnf5/issues/490.

**Comment by m-blaha** [comment]
Sorry, the functionality is already present in dnf5 - see https://github.com/rpm-software-management/dnf5/pull/225

**Comment by juhp** [comment]
> dnf install ~/Downloads/tito-0.6.2-1.fc22.noarch.rpm

Could you please allow relative filepaths also, like `dnf-3 localinstall` supports?
(For long lists of rpms, lists of absolute filepaths can get very long.)

I can open a separate issue for it, if desired.

**Comment by juhp** [comment]
It might be kind to support `localinstall` as an alias for `install` for backward compatibility.
Could it be put behind a deprecation warning?
"Deprecated alias" means it was already any alias in dnf-4?

**Comment by kontura** [comment]
> It might be kind to support still `localinstall` as an alias for `install` for backward compatibility. Could it be put behind a deprecation warning?
> 
> "Deprecated alias" means it was already any alias in dnf-4?

It was already [deprecated in dnf-4.](https://dnf.readthedocs.io/en/latest/command_ref.html?highlight=localinstall#install-command) 

But it was only documented I think there was no warning.
