### ISSUE TITLE
Implement mark command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#145]
**Command:** ```mark```

```dnf mark install <package-spec>...```

Marks the specified packages as installed by user. This can be useful if any package was installed as a dependency and is desired to stay on the system when [Autoremove Command](https://dnf.readthedocs.io/en/latest/command_ref.html#autoremove-command-label) or [Remove Command](https://dnf.readthedocs.io/en/latest/command_ref.html#remove-command-label) along with clean_requirements_on_remove configuration option set to ```True``` is executed.

```dnf mark remove <package-spec>...```

Unmarks the specified packages as installed by user. Whenever you as a user don’t need a specific package you can mark it for removal. The package stays installed on the system but will be removed when [Autoremove Command](https://dnf.readthedocs.io/en/latest/command_ref.html#autoremove-command-label) or [Remove Command](https://dnf.readthedocs.io/en/latest/command_ref.html#remove-command-label) along with clean_requirements_on_remove configuration option set to ```True``` is executed. You should use this operation instead of [Remove Command](https://dnf.readthedocs.io/en/latest/command_ref.html#remove-command-label) if you’re not sure whether the package is a requirement of other user installed packages on the system.

```dnf mark group <package-spec>...```

Marks the specified packages as installed by group. This can be useful if any package was installed as a dependency or a user and is desired to be protected and handled as a group member like during group remove.

**Comment by j-mracek** [comment]
I believe the command is completely implemented

**Comment by glum23** [comment]
Note: the description of this issue is significantly different from the current implementation of `dnf5 mark`. It is not properly documented yet, see  https://github.com/rpm-software-management/dnf5/issues/940 . Also, 'dnf5 mark group' does not work as expected, see https://github.com/rpm-software-management/dnf5/issues/935 .
