### ISSUE TITLE
add_install with group name has stopped working in 5.2 release

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#1451]
In osbuild-composer we use group names, `@Fedora Cloud Server`, this was discussed in #367 and has been working with libdnf5 < 5.2
I've tried out the 5.2 build from the side tag, as described here - https://bodhi.fedoraproject.org/updates/FEDORA-2024-8a41ea93a2 and with libdnf5-5.2.0.0-1.fc41 installed it won't install the group. If I use `@cloud-server-environment` it works fine. The test code looks like:

``` python
import libdnf5

base = libdnf5.base.Base()
#base.load_config_from_file()
base.load_config()
conf = base.get_config()
#conf.zchunk().set(False)
base.setup()

sack = base.get_repo_sack()
sack.create_repos_from_system_configuration()

repo_query = libdnf5.repo.RepoQuery(base)
repo_query.filter_enabled(True)
print("\n".join(list(r.get_name() for r in repo_query)))

print("update and load enabled repos...")
sack.update_and_load_enabled_repos(False)
print("done.")

goal = libdnf5.base.Goal(base)

settings = libdnf5.base.GoalJobSettings()
settings.group_with_name = True

## This does not work with libdnf5 5.2
goal.add_install("@Fedora Cloud Server", settings)

## These work
#goal.add_install("@^cloud-server-environment")
#goal.add_install("@cloud-server-environment")

# group works
#goal.add_install("@rpm-development-tools")

transaction = goal.resolve()
for tsi in transaction.get_transaction_packages():
        print(tsi.get_package().get_nevra())
```

**Comment by gotmax23** [comment]
> settings.group_with_name = True

The `group_with_name` property no longer exits. It was replaced by `get_group_with_name()` and `set_group_with_name()` methods.

**Comment by kontura** [comment]
Yes, sorry about that, we replaced several properties with getters/setters in `5.2.0.0`. Mainly to unify the API and make it more maintainable.

Most of the API changes should be in `GoalJobSettings()` and `ResolveSpecSettings`.

**Comment by bcl** [comment]
Alright, I'll make comments there.
