### ISSUE TITLE
String should be split into multiple strings for l10n

### ISSUE THREAD

**Issue by HarmfulBreeze** [rpm-software-management/dnf5#1471]
The following string can be hard to translate into some languages due to the first placeholder. https://github.com/rpm-software-management/dnf5/blob/e4502c2111ea95994f2c32d3bf2109bd415bf017/libdnf5/base/log_event.cpp#L154

I suggest making one translatable string per spec type, so one for packages, one for groups, one for environmental groups, and one for modules.

Also, I was unsure whether this issue should be reported here or on Weblate, please let me know if one is preferred over the other.

Thanks!

**Comment by ppisar** [comment]
This is the correct place for reporting problems with strings to be translated.

I can see the "No" can depend on the first placeholder. I will implement your suggestion.
