### ISSUE TITLE
Implement reinstall command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#148]
**Command:** ```reinstall``**`
Aliases:** ```rei```

```dnf [options] reinstall <package-spec>...```

Installs the specified packages, fails if some of the packages are either not installed or not available (i.e. there is no repository where to download the same RPM).

- [x] command reinstall
- [x] Alias `rei`
  - Shall we implement it or drop and document?
    - Proposing to add the alias
  - Priority low

**Comment by j-mracek** [comment]
All of the features were delivered

**Comment by glum23** [comment]
~~~
# dnf5 reinstall --skip-unavailable bash nosuchpkg
~~~
does not reinstall anything and exits with 1

version: dnf5-5.0.10-0.20230510005257.5.0.9+63.g4bafd1f9.fc38

bug filed:  https://bugzilla.redhat.com/show_bug.cgi?id=2196818
