### ISSUE TITLE
Handling of arch-specific provides

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#1487]
The following usage is not properly working for some cases: `dnf provides "gzip(x86-64)"`.

This is a follow-up to https://github.com/rpm-software-management/dnf5/issues/147.

**Comment by j-mracek** [comment]
I believe that it works according to expectations
```
$ dnf5 provides 'gzip(x86-64)' -q
gzip-1.12-6.fc39.x86_64 : GNU data compression program
Repo         : @System
Matched From : 
Provide      : gzip = 1.12-6.fc39

gzip-1.12-6.fc39.x86_64 : GNU data compression program
Repo         : fedora
Matched From : 
Provide      : gzip = 1.12-6.fc39
```

The only problem is related to highlighting matched string. Proposing to close it or provide detailed description what is wrong.
