### ISSUE TITLE
Implement remove command - core part

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#149]
- [x] **Command:** ```remove```

- [x] **Aliases:** ```rm```

- [x] ```dnf [options] remove <package-spec>...```

Removes the specified packages from the system along with any packages depending on the packages being removed. Each ```<spec>``` can be either a ```<package-spec>```, which specifies a package directly, or a ```@<group-spec>```, which specifies an (environment) group which contains it. If ```clean_requirements_on_remove``` is enabled (the default), also removes any dependencies that are no longer needed.

- [x] ```dnf [options] remove @<group-spec>``` 

### Features tracked in separate issues

- [ ] #758 
  - Proposing to drop
  - Priority low

- [ ] #759 
  - Proposing to drop
  - Priority low

- [ ] #760 
  - Priority low

Removes older versions of duplicate packages. To ensure the integrity of the system it reinstalls the newest package. In some cases the command cannot resolve conflicts. In such cases the [dnf shell](https://dnf.readthedocs.io/en/latest/command_ref.html#shell-command-label) command with ```remove --duplicates``` and ```upgrade``` dnf-shell sub-commands could help.

- [ ] #762 
  - Priority low

Removes old installonly packages, keeping only latest versions and version of running kernel.

There are also a few specific remove commands ```remove-n```, ```remove-na``` and ```remove-nevra``` that allow the specification of an exact argument in the NEVRA format.

Remove Examples

```dnf remove acpi tito```

Remove the ```acpi``` and ```tito``` packages.

```dnf remove $(dnf repoquery --extras --exclude=tito,acpi)```

Remove packages not present in any repository, but don’t remove the ```tito``` and ```acpi``` packages (they still might be removed if they depend on some of the removed packages).
Remove older versions of duplicated packages (an equivalent of yum’s package-cleanup –cleandups):

**Comment by jan-kolarik** [comment]
Removing by `@<group-spec>` is not working yet. I've added an item to the issue description.
