### ISSUE TITLE
Implement repoinfo command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#150]
- [x] **Command:** ```repoinfo```
  - command is implemented but it provides only limited information in comparison to DNF4
  - Priority medium

- [x] An alias for the [repolist](https://dnf.readthedocs.io/en/latest/command_ref.html#repolist-command-label) command that provides more detailed information like ```dnf repolist -v```.
  - Proposing to drop
  - Priority medium

Tracked in another issues:

- [ ] Unify the output with original dnf and create a possibility to add custom fields to the output ?
  - https://github.com/rpm-software-management/dnf5/issues/842

**Comment by glum23** [comment]
[RHEL related] When some repos are signed, dnf4 on RHEL is expected to import all required keys in one transaction and to provide info about it (dnf5 currently does not provide anything like that). In the example below, 2 repos (repo1 and repo2) are signed. See also RHEL bug 1781601.
~~~
# dnf -y repoinfo repo1
My Local Repo repo1                            26 kB/s | 659  B     00:00    
My Local Repo repo1                           2.3 MB/s | 2.3 kB     00:00    
Importing GPG key 0x9440AFDC:
 Userid     : "key1"
 Fingerprint: 5CE4 74FC 4EB6 8F1B D1D5 797E F5A2 5AB3 9440 AFDC
 From       : /tmp/tmp.dtiqa65REx/key1/key1-public
My Local Repo repo1                            57 kB/s | 1.0 kB     00:00    
My Local Repo repo2                            79 kB/s | 659  B     00:00    
My Local Repo repo2                           2.3 MB/s | 2.3 kB     00:00    
Importing GPG key 0xA701D86D:
 Userid     : "key2"
 Fingerprint: FC6E C162 F264 58B8 3726 FBC0 1C67 3F29 A701 D86D
 From       : /tmp/tmp.dtiqa65REx/key2/key2-public
My Local Repo repo2                            65 kB/s | 1.0 kB     00:00    
Repo-id            : repo1
Repo-name          : My Local Repo repo1
Repo-status        : enabled
Repo-revision      : 1682068598
Repo-updated       : Fri 21 Apr 2023 05:16:37 AM EDT
Repo-pkgs          : 2
Repo-available-pkgs: 2
Repo-size          : 13 k
Repo-baseurl       : file:///tmp/tmp.dtiqa65REx/repo1/
Repo-expire        : 172,800 second(s) (last: Fri 21 Apr 2023 05:17:10 AM EDT)
Repo-filename      : /etc/yum.repos.d/repo1.repo
Total packages: 2
~~~

**Comment by VladimirSlavik** [comment]
let's say I have a repo id and want the metalink. What is the available alternative to `dnf repoinfo` that shows the full metadata? Something using the API?

**Comment by kontura** [comment]
> let's say I have a repo id and want the metalink. What is the available alternative to `dnf repoinfo` that shows the full metadata? Something using the API?

Yea the `repo info` is still missing a bunch of data on output: https://github.com/rpm-software-management/dnf5/blob/main/include/libdnf5-cli/output/repo_info.hpp#L45

Through API you can do:
```python
import libdnf5

base = libdnf5.base.Base()

base.get_repo_sack().create_repos_from_system_configuration()

query = libdnf5.repo.RepoQuery(base)
query.filter_id("fedora")
for repo in query:
    print(repo.get_config().get_metalink_option().get_value())
```

For some more detailed description check out: https://dnf5.readthedocs.io/en/latest/tutorial/bindings/python3/index.html

**Comment by VladimirSlavik** [comment]
Wow, thank you @kontura! That's actually almost all that I needed... except for variable substitution in the resulting url, that is :(

BTW, the docs are pretty much useless. Half of what's in your snippet is just not there, at all. Not saying it's unexpected in this lifecycle phase or anyone's fault. It's just how it is.

**Comment by glum23** [comment]
there are docs issues, see https://github.com/rpm-software-management/dnf5/issues/1225
