### ISSUE TITLE
Implement repolist command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#151]
**Command:** ```repolist```

```dnf [options] repolist [--enabled|--disabled|--all]```

Depending on the exact command lists enabled, disabled or all known repositories. Lists all enabled repositories by default. Provides more detailed information when ```-v``` option is used.

This command by default does not force a sync of expired metadata. See also [Metadata Synchronization](https://dnf.readthedocs.io/en/latest/command_ref.html#metadata-synchronization-label).

- [x] repolist
- [x] --enabled|--disabled|--all
- [ ] Change output for `-v`
  - Proposing to drop
  - Document the change

**Comment by glum23** [comment]
there are docs issues, see https://github.com/rpm-software-management/dnf5/issues/1225
