### ISSUE TITLE
Implement search command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#152]
- [ ] **Command:** ```search```

- [ ] **Aliases:** ```se```
  - drop the alias

- [ ] ```dnf [options] search [--all] <keywords>...```

Search package metadata for keywords. Keywords are matched as case-insensitive substrings, globbing is supported. By default lists packages that match all requested keys (AND operation). Keys are searched in package names and summaries. If the “–all” option is used, lists packages that match at least one of the keys (an OR operation). In addition the keys are searched in the package descriptions and URLs. The result is sorted from the most relevant results to the least.

This command by default does not force a sync of expired metadata. See also [Metadata Synchronization](https://dnf.readthedocs.io/en/latest/command_ref.html#metadata-synchronization-label).

**Comment by jan-kolarik** [comment]
After merging the #202, the CI tests still need to be implemented for the command. Or maybe the existing DNF tests could be adjusted...

**Comment by frenzymadness** [comment]
I'm already testing dnf5 and the missing search command is currently the only big issue I have.

**Comment by jan-kolarik** [comment]
> I'm already testing dnf5 and the missing search command is currently the only big issue I have.

That's great, thanks for the report :slightly_smiling_face: The PR with search command already exists and I would like to have it finished and merged soon, in several days.
