### ISSUE TITLE
build-dep was renamed to builddep breaking backward compatibility

### ISSUE THREAD

**Issue by jakub-vavra-cz** [rpm-software-management/dnf5#1528]
The command was renamed and it is breaking backward compatibility, please make sure that scripts that were working with original dnf can work we dnf5 as well. We want our customers to have a seamless migration instead of burning additional effort on workarounds.

**Comment by jan-kolarik** [comment]
AFAIK, the command was actually originally named `builddep`, as it is also now in dnf5. Later, the `build-dep` alias was added based on the community request, see [here](https://github.com/rpm-software-management/dnf-plugins-core/blame/4.7.0/plugins/builddep.py#L42).

Anyway, I don't see a problem with adding this alias to dnf5 to make the migration smoother for affected systems, as you mentioned.
