### ISSUE TITLE
"dnf list --all"  Unknown argument "--all" for command "list". Add "--help" for more information about the arguments.

### ISSUE THREAD

**Issue by jakub-vavra-cz** [rpm-software-management/dnf5#1534]
Please fix for backward compatibility purposes.

**Comment by jakub-vavra-cz** [comment]
I expect the command tow work properly as before and recognize its parameters:
  --all                 show all packages (default)
  --available           show only available packages
  --installed           show only installed packages
  --extras              show only extras packages
  --updates             show only upgrades packages
  --upgrades            show only upgrades packages
  --autoremove          show only autoremove packages
  --recent              show only recently changed packages

**Comment by j-mracek** [comment]
`--all` option was added to DNF as a part compatibility with yum3 - RHEL7. It has no meaning - it does nothing in DNF. I believe that this is a good time to remove such an options. I an suggesting to only document the change.

**Comment by jan-kolarik** [comment]
I agree with Jarda. I've also checked that the change is [documented](https://dnf5.readthedocs.io/en/latest/changes.html), therefore closing this issue.
