### ISSUE TITLE
dnf config-manager  - Unknown argument "--add-repo"

### ISSUE THREAD

**Issue by jakub-vavra-cz** [rpm-software-management/dnf5#1537]
The original command no longer works breaking backward compatibility in scripts.
Unknown argument "--add-repo" for command "config-manager". Add "--help" for more information about the arguments.

**Comment by jan-kolarik** [comment]
Hi, as described in the https://github.com/rpm-software-management/dnf5/issues/405, this is actually an intended change. The config-manager API was reshaped and aligned with the other commands, therefore this is a backwards incompatible change.

I am closing the ticket. Users can either use the existing API using the `dnf-3 config-manager` command provided by the `python3-dnf` and `dnf-plugins-core` packages or migrate to the new dnf5 one.

**Comment by jakub-vavra-cz** [comment]
Well, users and their scripts would expect this to work without specifying dnf-3. 
If You insist on being backward incompatible, then leave dnf as a symlink to dnf-3 and let users use new syntax by invoking dnf5 explicitly.

We are using same scripts across various rhels, centos and fedoras and expect the code to work without branching everything for each of them. Unfortunately ansible core does not provide wrapper around dnf config-manager with addrepo functionality so we can not just use ansible to handle the differences.
