### ISSUE TITLE
Goal action string representations should be made translatable

### ISSUE THREAD

**Issue by HarmfulBreeze** [rpm-software-management/dnf5#1548]
The following strings should be made translatable: https://github.com/rpm-software-management/dnf5/blob/4a729aa5ac6fccd8e5cbf9130f0ec320ece58bf7/libdnf5/base/goal_elements.cpp#L344-L398

This would help fully translate this string: https://github.com/rpm-software-management/dnf5/blob/4a729aa5ac6fccd8e5cbf9130f0ec320ece58bf7/libdnf5/base/log_event.cpp#L158

**Comment by kontura** [comment]
Resolved by: https://github.com/rpm-software-management/dnf5/pull/1549
