### ISSUE TITLE
Implement updateinfo command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#155]
- [x] **Command:** ```updateinfo```

- [ ] **Aliases:** ```upif```
  - Not sure whether is it a good idea to keep it

- [x] **Deprecated aliases:** ```list-updateinfo```, ```list-security```, ```list-sec```, ```info-updateinfo```, ```info-security```, ```info-sec```, ```summary-updateinfo```
  - Proposing to not support those aliases

- [ ] Improve syntax - implement only options `--summary|--list|--info` but not positional arguments

- [x] implement support for security options `--security`, ...

```dnf [options] updateinfo [--summary|--list|--info] [<availability>] [<spec>...]```

Display information about update advisories.

Depending on the output type, DNF displays just counts of advisory types (omitted or ```--summary```), list of advisories (```--list```) or detailed information (```--info```). The ```-v``` option extends the output. When used with ```--info```, the information is even more detailed. When used with ```--list```, an additional column with date of the last advisory update is added.

```<availability>``` specifies whether advisories about newer versions of installed packages (omitted or ```--available```), advisories about equal and older versions of installed packages (```--installed```), advisories about newer versions of those installed packages for which a newer version is available (```--updates```) or advisories about any versions of installed packages (```--all```) are taken into account. Most of the time, ```--available``` and ```--updates``` displays the same output. The outputs differ only in the cases when an advisory refers to a newer version but there is no enabled repository which contains any newer version.

Note, that ```--available``` takes only the latest installed versions of packages into account. In case of the kernel packages (when multiple version could be installed simultaneously) also packages of the currently running version of kernel are added.

To print only advisories referencing a CVE or a bugzilla use ```--with-cve``` or ```--with-bz``` options. When these switches are used also the output of the ```--list``` is altered - the ID of the CVE or the bugzilla is printed instead of the one of the advisory.

If given and if neither ID, type (```bugfix```, ```enhancement```, ```security```/```sec```) nor a package name of an advisory matches ```<spec>```, the advisory is not taken into account. The matching is case-sensitive and in the case of advisory IDs and package names, globbing is supported.

Output of the ```--summary``` option is affected by the [autocheck_running_kernel](https://dnf.readthedocs.io/en/latest/conf_ref.html#autocheck-running-kernel-label) configuration option.

**Comment by kontura** [comment]
This has been implemented for a while.
There are some differences though. 
- `summary|list|info` are not options but sub-commands of the `updateinfo` command.
- `<spec>` argument to the commands is strictly matching against advisory ID. To select type there are options `--bugfix`, `--enhancement`, `--security`, `--newpackage`. To match packages in advisories there is `--contains-pkgs=PACKAGE_NAME,...`.
