### ISSUE TITLE
Cannot use `:` character in `username`

### ISSUE THREAD

**Issue by jrohel** [rpm-software-management/dnf5#1556]
The same problem is in the old libdnf (affects DNF4, microdnf, PackageKit, ...). Because both projects use librepo.
Librepo uses libcurl. To set the username and password librepo uses the old libcurl API option `CURLOPT_USERPWD`.

Suggested fix:
Extend librepo API. The new librepo API will use the new libcurl API options `CURLOPT_USERNAME` and `CURLOPT_PASSWORD`.
Modify dnf5 to use the new librepo API.

**Comment by ppisar** [comment]
Or you can enhance librepo to recognize "::" as literal ":", split on the single ":" and pass username and password to libcurl with separate calls.

**Comment by jrohel** [comment]
> Or you can enhance librepo to recognize "::" as literal ":", split on the single ":" and pass username and password to libcurl with separate calls.

`LRO_USERPWD` is not consistent with `LRO_PROXYUSERPWD`. And after the proposed modification, it would no longer be consistent with libcurl behavior either.

I prepared a PR https://github.com/rpm-software-management/librepo/pull/316 and added `LRO_USERNAME` and `LRO_PASSWORD` following the libcurl approach.
