### ISSUE TITLE
dnf5 has different groups then dnf-4

### ISSUE THREAD

**Issue by dschwoerer** [rpm-software-management/dnf5#1559]
I tried to install gnome with `dnf5` - but that fails:
```bash
fakeroot dnf5 group install "Fedora Workstation"
Updating and loading repositories:
Repositories loaded.
Failed to resolve the transaction:
No match for argument: Fedora Workstation
```

It does however succeed with `dnf-4`:
```bashfakeroot dnf group install "Fedora Workstation" 
Last metadata expiration check: 0:43:32 ago on Mon Jun 24 11:34:01 2024.
Dependencies resolved.
================================================================================
 Package                        Arch       Version            Repository   Size
================================================================================
Installing group/module packages:
[...]
```

I did not find anything related to why the group list is so much smaller in `dnf-4` compared to `dnf5`.

This was done on `fedora:40`

**Comment by jan-kolarik** [comment]
Hi, the mentioned `Fedora Workstation` group is actually the Environment Group. These could be managed with `dnf5 environment` command or installed also with the common install command with `dnf5 install @<group-id>`.

**Comment by jan-kolarik** [comment]
Though I agree it's confusing as the subcommands of `environment` are not consistent with the `group` command. This is already reported and tracked here: https://github.com/rpm-software-management/dnf5/issues/724.

**Comment by dschwoerer** [comment]
Sorry, I did read the other issue, but failed to realise that dnf-4 list environments with groups.

This is indeed a duplicate of #724
