### ISSUE TITLE
Implement upgrade command

### ISSUE THREAD

**Issue by mcurlej** [rpm-software-management/dnf5#156]
- [x] **Command:** ```upgrade```

- [x] **Aliases:** ```up```
  - keep it

- [x] **Deprecated aliases:** ```localupdate```
  - drop

- [x] **Deprecated aliases:** ```update```
  - keep it

- [x] **Deprecated aliases:** ```upgrade-to```
  - Dropping, because it is confusing in some cases - obsoletes and using without argument

```dnf [options] upgrade```

Updates each package to the latest version that is both available and resolvable.

```dnf [options] upgrade <package-spec>...```

Updates each specified package to the latest available version. Updates dependencies as necessary. When versions are specified in the ```<package-spec>```, update to these versions.

- [x] ```dnf [options] upgrade @<spec>...``` for groups and modules

Moved to another ticket

- [ ] #662

Alias for the dnf module update command.

If the main obsoletes configure option is true or the ```--obsoletes``` flag is present, dnf will include package [obsoletes](https://dnf.readthedocs.io/en/latest/conf_ref.html#obsoletes-conf-option-label) in its calculations. For more information see obsoletes.

See also [Configuration Files Replacement Policy](https://dnf.readthedocs.io/en/latest/command_ref.html#configuration-files-replacement-policy-label).

**Comment by Cyborgscode** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=2142257

**Comment by opoplawski** [comment]
Is it planned to implement the `--refresh` option to upgrade as well?

**Comment by j-mracek** [comment]
To implement `--refresh` option make sense. It is a global option in DNF4 but for some command it is not useful - `repolist`
