### ISSUE TITLE
memory leak in update_and_load_enabled_repos() (Python)

### ISSUE THREAD

**Issue by timlau** [rpm-software-management/dnf5#1561]
It looks like there is some memory there is not released when calling package_sack.update_and_load_enabled_repos(True)
from python when the cache is expired.
I have created some test  code located here
https://github.com/timlau/apitest/tree/main/dnf5/memleak

it does some basic dnf5 setup and get the number of  updates and clean up the base each time
with a fresh cache it run 3x and memory is released each time.

If I run "dnf5 clean expire-cache" before running the same code, the amount of allocated memory is increased at each run

Tested on dnf5.x86_64 5.1.17-1.fc40

I use python3-memray to track the memory usage

![test](https://github.com/rpm-software-management/dnf5/assets/283985/80f7e6de-9cf9-4e0f-85a7-7f4d193aabbb)

**Comment by timlau** [comment]
Thanks for looking into the issue

**Comment by kontura** [comment]
The PRs have been merged.
The issue should be resolved.
