### ISSUE TITLE
default command for `dnf5 history` should be `list`

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#1568]
The `dnf5 history --help` used to claim  the `list` is the default action (at least with dnf5-5.2.3.0-20240612113037.49.g28acb8d8), while:

```
$ dnf5 history
Missing command. Add "--help" for more information about the arguments.
```

The dnf5-5.2.4.0-20240701010012.1.g4eb54bac changed the `--help` output, it does not claim the `list` being the default any more.

I think it's convenient to expect the `list` being the default command, thus, unless you had a request to not do it, it would be nice to restore that behaviour.

**Comment by jan-kolarik** [comment]
Hi Milan,

I thought it was always like this for dnf5, it gives me:
```
$ dnf history --help
Usage:
  dnf5 [GLOBAL OPTIONS] history <COMMAND> ...

Query Commands:
  list                          List transactions
  info                          Print details about transactions

Software Management Commands:
  store                         [experimental] Store transaction to a file

$ dnf --version
dnf5 version 5.2.1.0
dnf5 plugin API version 2.0
libdnf5 version 5.2.1.0
libdnf5 plugin API version 2.0
```
But anyway, this is likely something we cannot change at this point. The modification is due to the stricter behavior of the argument parser in dnf5. For more details, please refer to docs [here](https://dnf5.readthedocs.io/en/latest/changes.html#optional-arguments).

**Comment by mcrha** [comment]
I thought the `--help` page changed semi-recently, but looking on it again, I could misplaced `dnf` and `dnf5`, where the `dnf`(4) does `list` by default and mentions it in the `--help` as well.

Even it would be still nice to preserver this behavior in the dnf5 (to `list` by default), if you think it would be hard, then no big deal.
