### ISSUE TITLE
offline: Running update with local package fails

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#1583]
I downloaded a package (`patch`) from koji, with a newer version than I've installed, and I wanted to update it, but in the offline (to save some bandwidth) and when I do that, I get:

```
# dnf update --offline ./patch-2.7.6-24.fc40.x86_64.rpm
Updating and loading repositories:
Repositories loaded.
Package                 Arch   Version                  Repository          Size
Upgrading:
 patch                  x86_64 2.7.6-24.fc40            @commandline   262.8 KiB
   replacing patch      x86_64 2.7.6-23.fc40            @commandline   262.8 KiB

Transaction Summary:
 Upgrading:         1 packages
 Replacing:         1 packages

Total size of inbound packages is 131 KiB. Need to download 0 B.
After this operation 0 B will be used (install 263 KiB, remove 263 KiB).
Is this ok [y/N]: y

Failed to access RPM "/usr/lib/sysimage/libdnf5/offline/./packages/patch-2.7.6-24.fc40.x86_64.rpm": No such file or directory
```

Not using pre-downloaded rpm file works.

**Comment by mcrha** [comment]
I forgot to add, this is with dnf5-5.2.4.0-20240715005730.21.g9c2e2150.fc41.x86_64

**Comment by ppisar** [comment]
I confirm this issue. It behaves like that for relative path, absolute paths, and for file:// schema. Also "dnf install --offline" is affected.

I guess this caused by an optimization for not copying local packages into a package cache.
