### ISSUE TITLE
"list installed" does not work

### ISSUE THREAD

**Issue by Germano0** [rpm-software-management/dnf5#1594]
`dnf5 list installed` does not work as expected (compared to old dnf)
```
dnf5 list installed
Updating and loading repositories:
Repositories loaded.
No matching packages to list
```
It should return the list of installed packages.
dnf5 version:
```
dnf5-5.1.17-1.fc40.x86_64
```

**Comment by kontura** [comment]
You have to use `--installed` option (which also works with old dnf).
The optional subcommands were problematic, there is some explanation here: https://dnf5.readthedocs.io/en/latest/changes.html#optional-arguments
