### ISSUE TITLE
Improve English: After this operation 4 MiB will be used

### ISSUE THREAD

**Issue by hboetes** [rpm-software-management/dnf5#1598]
I'd like to propose the following improvement to the English used by dnf5:

Original: "After this operation 4 MiB will be used"
Improved: "After this operation, 4 MiB extra will be used" or "After this operation, 4 MiB less will be used"

**Comment by ppisar** [comment]
For the shrink case we already have "4 MiB will be freed". Is it good enough? I will add the comma for both cases and change a wording for the enlargement case.

**Comment by hboetes** [comment]
Yes, an even better solution.
