### ISSUE TITLE
`config-manager addrepo` fails to add docker repository config

### ISSUE THREAD

**Issue by liemeldert** [rpm-software-management/dnf5#1603]
Following https://docs.docker.com/engine/install/fedora/ and updating commands to DNF5 causes this error when adding their repository:
```
❯ sudo dnf config-manager addrepo --from-repofile=https://download.docker.com/linux/fedora/docker-ce.repo

https://download.docker.com/linux/fedora/docker-ce.repo                                                 100% |  20.6 KiB/s |   1.9 KiB |  00m00s
Error in added repository configuration file. Cannot set repository option "#1= ": Option "#1" not found
```

Importing the repo from dnf4 and then installing with dnf5 works without issues.

I'm facing this issue on Ultramarine (Fedora) 40, dnf5 version 5.1.17, config-manager 0.1.0, kernel 6.9.11-200.fc40.x86_64.

**Comment by jan-kolarik** [comment]
Hi, thanks for the report and simple reproducer. I confirm the issue persist with the latest upstream dnf5 version. With dnf4 config-manager it works correctly.
