### ISSUE TITLE
get dnf5 packaged for EL9

### ISSUE THREAD

**Issue by asarubbo** [rpm-software-management/dnf5#1612]
Because of the issue described in https://github.com/ansible/ansible/issues/83681 and https://github.com/rpm-software-management/dnf/issues/2010 I would like to ask if dnf5 can be packaged to be used on EL9

Thanks.

**Comment by ppisar** [comment]
EPEL is maintained by Fedora and its bug tracker is <https://bugzilla.redhat.com/>. Please use that one.
