### ISSUE TITLE
automatic: Consider reading the dnf4 configuration file for backward compatibility

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#1624]
The configuration for the `automatic` functionality has been moved to a different location compared to dnf4, as this functionality is now provided as a plugin (see the [changes docs](https://dnf5.readthedocs.io/en/latest/changes.html#changes-to-individual-commands) and [automatic command docs](https://dnf5.readthedocs.io/en/latest/dnf5_plugins/automatic.8.html#automatic-plugin-ref-label)). The content is backwards compatible, and since we are already reading multiple configuration file locations, we might consider applying the values from the original location for users who have migrated to dnf5.

**Comment by keszybz** [comment]
I don't think the new location makes much sense. As a user, I really don't want to care or think about the fact this functionality is provided by a plugin. I'd vote for just using the old location (which is backwards compatible and makes the most sense for the user).

**Comment by jan-kolarik** [comment]
> I don't think the new location makes much sense. As a user, I really don't want to care or think about the fact this functionality is provided by a plugin. I'd vote for just using the old location (which is backwards compatible and makes the most sense for the user).

Yeah, good point, thanks for the feedback! If the plugin still needs to access the configuration at the standard plugin location, we can just add a symlink there.
