### ISSUE TITLE
Could we add `pkg_gpgcheck` as the supported option and make `gpgcheck` an alias to that (for now)?

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#1649]
Could we add `pkg_gpgcheck` as the supported option and make `gpgcheck` an alias to that (for now)? That would let us make a step toward #727...

_Originally posted by @Conan-Kudo in https://github.com/rpm-software-management/dnf5/issues/1648#issuecomment-2304404102_

**Comment by jan-kolarik** [comment]
IIUC, this doesn't change any existing behavior. If that's the case, I have no issue with it.
