### ISSUE TITLE
Implement ABI compatibility check in CI

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#1651]
We need to implement an ABI differences check action in our CI pipeline to detect if a submitted PR breaks ABI compatibility compared to the current upstream build. Although an `abidiff` check is already run as part of the `rpminspect` test suite after pushing a Bodhi update, this occurs too late in the process.

**Comment by ppisar** [comment]
When comparing the pull-requested code against a previous good known state, there were two ideas:

David's idea was offload it to Fedora build system and compare against "last" Fedora build in Koji.

My idea was use abidw to extract ABI from a good know state, commit the abidw output (a single XML file) to dnf5 git tree and then use abidiff against that committed abidw file.
