### ISSUE TITLE
dnf5daemon: Session caching can be harmful

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#1653]
When using only a single session a package install followed by the same package uninstall results into: `rpm transaction failed with code 5` and the package is not uninstalled, while using a different session for the uninstall works fine.

The package flags are also affected by this, because starting a new session and removing the package and immediately after that using the same session to get the package attributes keeps the `is_installed` flag of the package on `true`, while using two different sessions provides accurate information to the dnf5daemon client.

I believe both things are closely related, thus I filled them as a single issue.

This is with dnf5-5.2.5.0-20240826005752.50.gb1f839cd

**Comment by m-blaha** [comment]
This issue prevents gnome software from re-using the same dnf5daemon session. Bumping priority.

**Comment by m-blaha** [comment]
Proposed PR https://github.com/rpm-software-management/dnf5/pull/1678 which re-sets the goal automatically after the do_transaction() execution. Also adds a new D-Bus API call to reset the goal manually.

**Comment by m-blaha** [comment]
Now I'm thinking about the second part (the is_installed flag), this would require re-reading the system repo. Let me explore what options there are.

**Comment by mcrha** [comment]
I tried the changes from the #1757 in action and it seems to do the proper thing (I've just done some quick/smoke testing). Thank you.
