### ISSUE TITLE
Skipping PGP checks for packages from offline transaction

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#1668]
Using dnf5-5.2.5.0-20240828005842.55.g4b2fb499.fc40.x86_64.

I've upgraded the machine from f39 to f40.

When I run `dnf5 update` in the f40 it asks to import the f40 PGP key, as expected.

When I run `dnf5 update --offline`, it does _not_ ask to import the key. It claims on the terminal:

> Warning: skipped PGP checks for 2 packages from repository: @stored_transaction

Similarly when running an offline update using the D-Bus API of the dnf5daemon-server; it does not ask to import the key too.

I think it makes sense to have the PGP key imported and checked for (when the repo has it enabled) regardless whether the update is done immediately or offline.

_If you think this bug is different from that mine, then just say so and I can create a new bug instead._

_Originally posted by @mcrha in https://github.com/rpm-software-management/dnf5/issues/991#issuecomment-2314891892_

**Comment by m-blaha** [comment]
Looks like it's a regression of caused by 5c00c1a
We also need to add a test for this scenario.
