### ISSUE TITLE
[feature request] add global `--overide-protected` flag to overide `/etc/dnf/protected.d/`

### ISSUE THREAD

**Issue by solomoncyj** [rpm-software-management/dnf5#1675]
Say you installed the KDE spin, but you tried out budgie and like it, so you want to uninstall kde with `dnf group remove "KDE Desktop"` just to be hit with the protected packages error. Implementing this option shoyuld prevent the user form editing the protected packages themsleves, or having to run `rpm -e --nodeps` for each package

**Comment by kontura** [comment]
If I understand correctly you want to disable the protection for the specific dnf run.

You can already achieve this by cleaning the `protected_packages` config option, you can do:
```
dnf group remove group-id --setopt=protected_packages=,
```

It is not as user friendly as `--overide-protected` would be but perhaps that is a good thing, it is very easy to break your system by removing protected packages.
