### ISSUE TITLE
Implement --repofrompath parameter

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#168]
`--repofrompath <repo>,<path/url>`

Documentation for this parameter from `DNF` docs:

> Specify a repository to add to the repositories for this query.  This option can be used multiple times.
> - The repository label is specified by `<repo>`.
> - The path or url to the repository is specified by `<path/url>`.  It is the same path as a baseurl and can be also enriched by the repo variables.
> - The configuration for the repository can be adjusted using `--setopt=<repo>`.`<option>=<value>`.
> - If you want to view only packages from this repository, combine this with the `--repo=<repo>` or `--disablerepo="*"` switches.

**Comment by jan-kolarik** [comment]
This is also a requested functionality [here](https://github.com/rpm-software-management/microdnf/issues/128) by the current `microdnf` users.

**Comment by rossburton** [comment]
We (yoctoproject) use DNF to construct root filesystems, I've been doing an experimental port to dnf5 and this is a blocker for us.

**Comment by jan-kolarik** [comment]
There is a related ticket for implementing this option for `repoquery` command: https://github.com/rpm-software-management/dnf5/issues/549.
