### ISSUE TITLE
Many texts in "dnf install" output are not internationalized

### ISSUE THREAD

**Issue by bittin** [rpm-software-management/dnf5#1688]
dnf5 in Fedora 41 installed with https://kojipkgs.fedoraproject.org/compose/branched/Fedora-41-20240910.n.0/compose/Workstation/x86_64/iso/Fedora-Workstation-Live-x86_64-41-20240910.n.0.iso is still in English: https://github.com/rpm-software-management/dnf5/blob/main/dnf5/po/sv.po even if there is a Swedish translation

https://i.imgur.com/FjgHw5d.png

**Comment by ppisar** [comment]
Could you tell us what locale do you use (`locale` command output) and what DNF5 version you have installed (`rpm -q dnf5`)?

For me it works. The first message in the linked sv.po is:

~~~~
#: commands/advisory/advisory_info.hpp:33
msgid "Print details about advisories"
msgstr "Skriv ut detaljer om rekommendationer"
~~~~

It's a description of "info" command in `dnf advisory --help` output.

When I install a Swedish locale (`dnf install glibc-langpack-sv`) and call `dnf5 advisory --help` in sv_SE.utf8 locale, I get:

~~~~
# LC_ALL=sv_SE.utf8 dnf5 advisory --help
Användning:
  dnf5 [GLOBAL OPTIONS] advisory <COMMAND> ...
                                
Query Commands:                 
  list                          Lista rekommendationer
  info                          Skriv ut detaljer om rekommendationer
  summary                       Skriv ut en sammanfattning av rekommendationer
~~~~

That matches the translation.

**Comment by bittin** [comment]
> Could you tell us what locale do you use (`locale` command output) and what DNF5 version you have installed (`rpm -q dnf5`)?
> 
> For me it works. The first message in the linked sv.po is:
> 
> ```
> #: commands/advisory/advisory_info.hpp:33
> msgid "Print details about advisories"
> msgstr "Skriv ut detaljer om rekommendationer"
> ```
> 
> It's a description of "info" command in `dnf advisory --help` output.
> 
> When I install a Swedish locale (`dnf install glibc-langpack-sv`) and call `dnf5 advisory --help` in sv_SE.utf8 locale, I get:
> 
> ```
> # LC_ALL=sv_SE.utf8 dnf5 advisory --help
> Användning:
>   dnf5 [GLOBAL OPTIONS] advisory <COMMAND> ...
>                                 
> Query Commands:                 
>   list                          Lista rekommendationer
>   info                          Skriv ut detaljer om rekommendationer
>   summary                       Skriv ut en sammanfattning av rekommendationer
> ```
> 
> That matches the translation.


fed41betarc11@localhost-live:~$ locale
LANG=sv_SE.UTF-8
LC_CTYPE="sv_SE.UTF-8"
LC_NUMERIC="sv_SE.UTF-8"
LC_TIME="sv_SE.UTF-8"
LC_COLLATE="sv_SE.UTF-8"
LC_MONETARY="sv_SE.UTF-8"
LC_MESSAGES="sv_SE.UTF-8"
LC_PAPER="sv_SE.UTF-8"
LC_NAME="sv_SE.UTF-8"
LC_ADDRESS="sv_SE.UTF-8"
LC_TELEPHONE="sv_SE.UTF-8"
LC_MEASUREMENT="sv_SE.UTF-8"
LC_IDENTIFICATION="sv_SE.UTF-8"
LC_ALL=
fed41betarc11@localhost-live:~$ rpm -q dnf5
dnf5-5.2.5.0-2.fc41.x86_64
fed41betarc11@localhost-live:~$ dnf advisory --help
Användning:
  dnf5 [GLOBAL OPTIONS] advisory <COMMAND> ...
 
Query Commands:                 
  list                          Lista rekommendationer
  info                          Skriv ut detaljer om rekommendationer
  summary                       Skriv ut en sammanfattning av rekommendationer
 

still getting english when trying to install a package with sudo dnf5 install emacs 

as the example above, even if everything should be fully translated

**Comment by ppisar** [comment]
I see. Your problem is that not all messages printed by DNF5 are internationalized. That means they are not in the message catalogs and they do not undergo a lookup in for the translation. That's e.g. the case of "Updating and loading repositories: message.

This is not specific to Swedish. It concerns all languages. That's a cause of sloppy programming when internationalization was not implemented from the very beginning.

**Comment by bittin** [comment]
> I see. Your problem is that not all messages printed by DNF5 are internationalized. That means they are not in the message catalogs and they do not undergo a lookup in for the translation. That's e.g. the case of "Updating and loading repositories: message.
> 
> This is not specific to Swedish. It concerns all languages. That's a cause of sloppy programming when internationalization was not implemented from the very beginning.

heh then you have something to do ;) 
have fun :)

**Comment by ppisar** [comment]
Corresponding Fedora bug report <https://bugzilla.redhat.com/show_bug.cgi?id=2311298>.

**Comment by bittin** [comment]
yay, thanks for the C++ code writing you people in Czechia, now mine and @goeranu Swedish
and other peoples translations, actually can be shown in dnf5 for the Fedora Linux 41 release in 1-2 months

**Comment by bittin** [comment]
talked to @ppisar on #fedora-devel on irc.libera.chat Libera.chat IRC yesterday
and have started translating the new strings for dnf5 into Swedish now

**Comment by bittin** [comment]
> talked to @ppisar on #fedora-devel on irc.libera.chat Libera.chat IRC yesterday and have started translating the new strings for dnf5 into Swedish now

one i was unsure of but now its 99% done 
@goeranu do you have time to look at the last 1% :) ;)

**Comment by goeranu** [comment]
Done.

**Comment by bittin** [comment]
@goeranu thx :)
@ppisar so everything is in Swedish again for the Fedora 41 release in 1,5-2 months time now
