### ISSUE TITLE
Apply --debugsolver option for modules and groups

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#172]
- [x] [modules](https://github.com/rpm-software-management/dnf5/pull/870)
- [x] [groups](https://github.com/rpm-software-management/dnf5/pull/874)

Follow-up issue:
- #963

**Comment by jan-kolarik** [comment]
@j-mracek Can we consider this as completed? I am not really sure what is really meant by these optional features.

**Comment by j-mracek** [comment]
> @j-mracek Can we consider this as completed? I am not really sure what is really meant by these optional features.

In DNF4 `--debugsolver` only provides an information what solver sees, but it does not dump information about dnf configuration, repo configuration or variables. The optional items were only a idea wheres the option may dump additional information related to configuration, repo configuration or variables including releasever.

@jan-kolarik What do you think - shall we add it or keep it like it is?

**Comment by jan-kolarik** [comment]
> > @j-mracek Can we consider this as completed? I am not really sure what is really meant by these optional features.
> 
> In DNF4 `--debugsolver` only provides an information what solver sees, but it does not dump information about dnf configuration, repo configuration or variables. The optional items were only a idea wheres the option may dump additional information related to configuration, repo configuration or variables including releasever.
> 
> @jan-kolarik What do you think - shall we add it or keep it like it is?

I guess that the logic behind this is already implemented [here](https://github.com/rpm-software-management/dnf5/pull/877) and [here](https://github.com/rpm-software-management/dnf5/pull/875)? So the only thing would be to possibly redirect it to the file instead to the standard output?

**Comment by jan-kolarik** [comment]
I am closing this as completed. Optional functionality is now tracked in a separate issue.
