### ISSUE TITLE
Avoiding dependencie errors while upgrading F40/F41 for long-time dnf5 users.

### ISSUE THREAD

**Issue by ilikelinux69** [rpm-software-management/dnf5#1724]
Here an example:

https://discussion.fedoraproject.org/t/conflicts-with-libdnf5-dnf5-dnf-data-and-kio-extras-when-trying-to-upgrade-from-fedora-40-to-fedora-41/131963

I was avoiding some errors while making the sim-link dnf > dnf5 before upgrading to F41 (tested in a vm).  I generally preferred to use dnf5 already on F40.

What is the main problem not upgrading dnf before upgrade F40/F41? At least making possible for dnf5 users testing it since F39 on?

**Comment by ppisar** [comment]
I'm sorry, but I cannot reproduce your problem:

I have installed:

~~~~
# rpm -qa |grep dnf |sort
dnf-4.21.1-1.fc40.noarch
dnf5-5.1.17-2.fc40.x86_64
dnf-data-4.21.1-1.fc40.noarch
dnf-plugins-core-4.9.0-1.fc40.noarch
libdnf-0.73.3-1.fc40.x86_64
libdnf5-5.1.17-2.fc40.x86_64
libdnf5-cli-5.1.17-2.fc40.x86_64
python3-dnf-4.21.1-1.fc40.noarch
python3-dnf-plugins-core-4.9.0-1.fc40.noarch
python3-libdnf-0.73.3-1.fc40.x86_64
~~~~

I perform the command from the linked example:

~~~~
# dnf5 --no-best --releasever 41 system-upgrade download
~~~~

It correctly resolves all dependencies, correctly replacing "dnf" and "yum" packages with "dnf5" package, downloads the packages and finishes with:

~~~~
Transaction stored to be performed offline. Run `dnf5 offline reboot` to reboot and run the transaction. To cancel the transaction and delete the downloaded files, use `dnf5 offline clean`.
~~~~

When I issue `dnf5 offline reboot` command, it reboots and successfully upgrades the system. After logging in I end up with these packages:

~~~~
# rpm -qa |grep dnf |sort
dnf5-5.2.6.2-1.fc41.x86_64
dnf-data-4.21.1-2.fc41.noarch
dnf-plugins-core-4.9.0-1.fc41.noarch
libdnf-0.73.3-1.fc41.x86_64
libdnf5-5.2.6.2-1.fc41.x86_64
libdnf5-cli-5.2.6.2-1.fc41.x86_64
python3-dnf-4.21.1-2.fc41.noarch
python3-dnf-plugins-core-4.9.0-1.fc41.noarch
python3-libdnf-0.73.3-1.fc41.x86_64
~~~~

I also tried it with disabled fedora-updates-testing repository and also works for me.

Nevertheless, you have obviously issues with how DNF5 is packaged in Fedora. This is not a problem of DNF5 project. It's a problem of Fedora and you should open a bug report in Fedora's Bugzilla.
