### ISSUE TITLE
Option to retreive download url of a pacakge from all available mirrors

### ISSUE THREAD

**Issue by alimirjamali** [rpm-software-management/dnf5#1734]
With dnf4, our `downloadurl` plugin ([fork](https://github.com/QubesOS/qubes-core-agent-linux/blob/main/package-managers/dnf-plugin-downloadurl.py) of download plugin) allowed us to get urls for specific package from all mirrors (our own infrastructure). So we could shuffle them and use curl/wget/... to download the package via our own interactive CLI/GUI tools from multiple mirrors (They are multi-gigabyte VM templates). The command was `dnf downloadurl --url --all-mirrrors <pkg>`.

It appears that `downloadurl` plugin is not compatible with dnf5 anymore. Neither `dnf repoquery <pkg> --location` nor `dnf download <pkg> --url ` could do the same. Is there any workaround for dnf5?

**Comment by alimirjamali** [comment]
Never mind. Some confusion here. It is a forked version of `download` plugin. Not an official one.

**Comment by marmarek** [comment]
But maybe it still makes sense? What about adding `--all-mirrors` option to the `download` command? The way we have it in our `ownloadurl` plugin makes sense only for a single package (it prints all URLs but doesn't mark which one is for which package), but maybe still something that would be useful for others too?

**Comment by alimirjamali** [comment]
[This line](https://github.com/rpm-software-management/dnf5/blob/main/dnf5/commands/download/download.cpp#L276) in dnf5 download plugin is what that has to be changed/improved to allow `--all-mirrors` (to be used together with `--url` option). I am ready to work on a patch if DNF5 maintainers approve it.

**Comment by alimirjamali** [comment]
Related: #497

**Comment by alimirjamali** [comment]
> Would you print every URL on a separate line, or would you group URLs pertaining the same package on a single line, separating them with a white space?

For our current use case, we have been using the old DNF4 patched download plugin only for one package. So the grouping was not necessary. But grouping is doable and is very useful. I will amend the PR and apply the recommended change. Force-push it after testing.
