### ISSUE TITLE
Advertize --use-host-config option in "No matching repositories" error if --installroot was used

### ISSUE THREAD

**Issue by decathorpe** [rpm-software-management/dnf5#1756]
I have this repository file on my local system in `/etc/yum.repos.d/koji.repo`:

```ini
[koji]
name=koji
baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/$basearch/
enabled=0
skip_if_unavailable=False

[koji-sources]
name=koji-sources
baseurl=https://kojipkgs.fedoraproject.org/repos/rawhide/latest/src/
enabled=0
skip_if_unavailable=False
```

I use this to query the rawhide buildroot contents to get up-to-date data instead of having to wait for rawhide composes and mirroring delays.

This works fine with dnf on Fedora < 41 and with dnf-3 on Fedora 41, but dnf5 does not seem to find the repo definitions from this file.

```
$ dnf --installroot /tmp/dnf5/ --releasever rawhide --repo koji --repo koji-sources makecache --refresh 
No matching repositories for "*, koji, koji-sources". Add "--help" for more information about the arguments.
```

The same command works perfectly on Fedora 41 after replacing `dnf` with `dnf-3`.

**Comment by kontura** [comment]
The difference is that dnf5 no longer tries to automatically search for configuration file and reposdir in the host if it doesn't find them in the installroot.
There is now `--use-host-config`, see https://dnf5.readthedocs.io/en/latest/misc/installroot.7.html#installroot-parameter.

I think we could definitely improve the message though.

**Comment by decathorpe** [comment]
Oh, that is definitely a very confusing difference in behaviour ... so I need to pass `--use-host-config` in addition to `--installroot`?

**Comment by ppisar** [comment]
Yes, because configuration of repositories is part of DNF configuration and DNF5 consistently uses configuration from the host by default.

**Comment by ppisar** [comment]
Indeed the option name is terrible. I'd prefer `--installrootconfig: It would be close to `--installroot` in manual and usage output, so people could notice it. It would also have no hyphens as any other DNF5 options.

I think we can augment the "no matching repository" error in case of --installroot was supplied. Good point.

**Comment by ppisar** [comment]
Dammit. I also mistaken to systems.

Now DNF5 loads repository configuration from --installroot location by default. I.e. it loads everything (except a main configuration (/etc/dnf/dnf.conf)?) from the installation root. So actually `--use-host-config` option name is correct.

**Comment by decathorpe** [comment]
Awesome. Thank you for the quick fix!
