### ISSUE TITLE
Decide how to ship bgettext (and others from common/utils/ directory) headers

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#180]
There is `#include "utils/bgettext/bgettext-mark-common.h"` in `include/libdnf/common/exception.hpp` which makes `dnf install dnf5-devel` insufficient for building a third-party plugin. The bgettext/* headers are not part of any dnf5 devel packages.

**Comment by jan-kolarik** [comment]
After the team discussion, we decided to resolve this by exposing the needed methods to the public API.

**Comment by evan-goode** [comment]
Whoops, I meant to assign myself on a different issue. Didn't mean to steal this from ya @jan-kolarik

**Comment by jan-kolarik** [comment]
> Whoops, I meant to assign myself on a different issue. Didn't mean to steal this from ya @jan-kolarik

Haha, no worry! Let's leave this unassigned for now, so anyone can take it if interested. I still have several things in my queue :slightly_smiling_face:

**Comment by jan-kolarik** [comment]
This could be now closed as the PR is merged?
