### ISSUE TITLE
odd behavior for script_type_to_string

### ISSUE THREAD

**Issue by anaselli** [rpm-software-management/dnf5#1801]
I tried to show the script type string into [dnfdragora](https://github.com/manatools/dnfdragora) mnaging transaction_script_start, transaction_script_stop and transaction_script_error signals from dnf5daemon.

I used **libdnf5.rpm.TransactionCallbacks.script_type_to_string** from rpm.py:

```
@staticmethod
    def script_type_to_string(type):
        r"""
        :type type: int
        :param type:  scriptlet type
        :rtype: string
        :return: string representation of the scriptlet type
        """
        return _rpm.TransactionCallbacks_script_type_to_string(type)
```

The code is something like:

```
scriptletType=libdnf5.rpm.TransactionCallbacks.script_type_to_string(scriptlet_type),
values = (session_object_path,nevra, scriptlet_type, scriptletType, return_code)
logger.debug('OnTransactionScriptStop: %s', repr(values))
```
The output is like:
`2024-10-27 15:45:45,299 [dnfdragora.ui]{ui.py:1962}(DEBUG) OnTransactionScriptStart: ('/org/rpm/dnf/v0/7ae14cda6467e57a1d49e1f61563c9e2', 'glibc-6:2.39-8.mga10.x86_64', 8, ('trigger-install',))`

As you can see it seems more a list of strings.....

**Comment by m-blaha** [comment]
> ```
> scriptletType=libdnf5.rpm.TransactionCallbacks.script_type_to_string(scriptlet_type),
> ```

The comma in the end of the line is a typo? Otherwise it would explain the  tuple in the result.

**Comment by anaselli** [comment]
guess so thanks!

**Comment by m-blaha** [comment]
I guess, this one can be closed then.

**Comment by anaselli** [comment]
Yeah i could not verify it yet but I agree :)
