### ISSUE TITLE
"dnf list installed" has different behavior

### ISSUE THREAD

**Issue by Tiagoquix** [rpm-software-management/dnf5#1810]
When using something such as `dnf list installed *python*` in DNF before DNF5 (Fedora Linux 40 or earlier), it would only list the installed packages.

Now, it lists both the installed packages and the available packages to download.

Edit: using `--installed` instead of `installed` fixes the problem, but I believe `installed` without the hyphens should be an alias, if possible. Thanks.

**Comment by kontura** [comment]
Yes, this is a deliberate change.
The problem with using just `installed` is that it is not clear whether the user is trying to filter for a package called "installed" or using the option.
It is also described here: https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html#optional-arguments

I don't think we will be changing this back, sorry.
