### ISSUE TITLE
README.md contains out of date information

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#182]
It shouldn't mention `dnf-5-devel` branch, docs at https://libdnf.readthedocs.io/  or `dnf builddep libdnf.spec`.

It is also confusing to be in `dnf5` (name of the binary) repo but README talks about `libdnf` library.

It should mention the [CHANGES-DNF-5.md](https://github.com/rpm-software-management/dnf5/blob/main/CHANGES-DNF-5.md) doc

**Comment by inknos** [comment]
I changed the About section yesterday.
https://github.com/rpm-software-management/dnf5/commit/d42c163db2f83dae23e07e99016e183eb8c0a0f8

I will also update the readme accordingly
