### ISSUE TITLE
Updating of non-existent packages mustn't fail

### ISSUE THREAD

**Issue by birdie-github** [rpm-software-management/dnf5#1824]
I'm using `dnf5-5.2.6.2-1.fc41.x86_64`.

dnf could update the packages specified on the command line regardless of whether they are installed or not, the non-existent packages would be skipped, dnf5 instead fails:

```
dnf5 update existing-package non-existent-package
Failed to resolve the transaction:
Packages for argument 'non-existent-package' available, but not installed.
```

Please revert to the old behavior.

**Comment by kontura** [comment]
I am sorry but this change is on purpose and I don't think we will revert back to the old behavior.

It is described in the `upgrade` section of: https://dnf5.readthedocs.io/en/latest/changes_from_dnf4.7.html
Also there is a `--skip-unavailable` option which will restore the old behavior.

Can I ask what use-case is this change breaking for you?

**Comment by birdie-github** [comment]
`--skip-unavailable` works perfectly for me. I was just unaware of it. Thanks a lot.

So far there's just a ton of difference in syntax and invocation. A bit of a bummer that you've decided to change so much.
