### ISSUE TITLE
dnf5 repoquery --location doesn't return anything

### ISSUE THREAD

**Issue by davide125** [rpm-software-management/dnf5#1889]
On Fedora Linux 41:

```
$ dnf5 repoquery bash
Updating and loading repositories:
Repositories loaded.
bash-0:5.2.32-1.fc41.aarch64
$ dnf5 repoquery --location bash
Updating and loading repositories:
Repositories loaded.

$ 
```

I would have expected this to print out a URL, like it used to work with dnf4.

**Comment by kontura** [comment]
This looks like the same issue as https://bugzilla.redhat.com/show_bug.cgi?id=2299337.

Does it work when run as root user?

If yes this should be fixed in the next release.

**Comment by davide125** [comment]
Yes, this does work fine when run as root.

**Comment by kontura** [comment]
Ok, then this is resolved by: https://github.com/rpm-software-management/dnf5/pull/1880
