### ISSUE TITLE
QueryCmp NEQ doesn't work with filter_evr()

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#189]
When working with python3-libdnf5 is it expected that NEQ isn't supported with filter_evr()? eg. Adding this to a series of queries:

```
    from libdnf5.common import QueryCmp_NEQ as NEQ
    q.filter_evr(["4.0"], NEQ)
```

Results in:
```
terminate called after throwing an instance of 'libdnf::AssertionError'
  what():  libdnf/rpm/package_query.cpp:504: void libdnf::rpm::PackageQuery::filter_evr(const std::vector<std::__cxx11::basic_string<char> >&, libdnf::sack::QueryCmp): Assertion failed: Unsupported sack::QueryCmp value 257
Aborted (core dumped)
```

Additionally, it is dumping core when this happens instead of raising a python exception.

**Comment by jan-kolarik** [comment]
Hello Brian and sorry about the late reply (again :disappointed:). It is a correct behavior that `NEQ` filter does not work for `filter_evr()` method, see the docs for API: https://github.com/rpm-software-management/dnf5/blob/main/include/libdnf/rpm/package_query.hpp#L154.

About dumping the core, I will discuss that with colleagues.

**Comment by jan-kolarik** [comment]
I discussed this specific case which throws the `AssertionError` and this exception is not caught even in CPP code. It is considered as a serious problem in the code logic and there we want to have the dump and backtrace for further investigation.

Other exceptions should be correctly handled as you've written. I will try to check those as I am currently working on the bindings issues and eventually a new issue will be created to resolve these.
