### ISSUE TITLE
Kernel-core package protected even when trying to remove it from within container

### ISSUE THREAD

**Issue by Perpixel** [rpm-software-management/dnf5#1909]
If your host runs on the same kernel installed on your container, dnf5 won't allow you to remove it. My use case is from building a new Silverblue image with a longterm kernel from copr.

```
$ dnf5 remove -y kernel kernel-core
Failed to resolve the transaction:
Problem: The operation would result in removing of running kernel: kernel-core-0:6.11.8-300.fc41.x86_64
```

**Comment by ppisar** [comment]
The check for the running kernel can be suppressed with "--setopt protect_running_kernel=false" arguments.

I'm not sure if DNF5 has a detection for an container environment, but I worry that "container" is too fuzzy as you can have unshared PID name space, while sharing file system with the "host" environment. Therefore I suggest explicitly inhibiting the check with the proposed arguments.

Does the protect_running_kernel option solve the problem for you?

**Comment by Perpixel** [comment]
--setopt protect_running_kernel=false is the correct answer. Thank you!
