### ISSUE TITLE
Implement cacheonly functionality

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#191]
Running the DNF5 entirely from the system cache is not implemented yet. 

There are two things that are related to this functionality:
- [ ] `--cacheonly` parameter
- [ ] `cacheonly` configuration option

The configuration option is already present, but so far has no logic connected with it.

Here are documentation snippets for the related functionality in DNF:

>
>       -C, --cacheonly
>              Run entirely from system cache, don't update the cache and use it even in case it is expired.
>
>              DNF  uses  a separate cache for each user under which it executes. The cache for the root user is called the system cache. This switch allows a regular
>              user read-only access to the system cache, which usually is more fresh than the user's and thus he does not have to wait for metadata sync.

>       cacheonly
>              boolean
>
>              If set to True DNF will run entirely from system cache, will not update the cache and will use it even in case it is expired. Default is False.
>
>              API Notes: Must be set before repository objects are created. Plugins must set this in the pre_config hook. Later changes are ignored.

**Comment by genodeftest** [comment]
Just as a hint: It would be nice if you could take care that caching doesn't break if root has umask `0077`: https://bugzilla.redhat.com/show_bug.cgi?id=1154272

**Comment by j-mracek** [comment]
I do afraid that the situation is not so simple with cacheonly.
During history DNF has 2 different behavior for the option and may be it is the time to allow multiple behavior

1.  cacheonly applied for everything - METADATA, RPMS => in some cases user does not want to download anything or it is impossible to download anything therefore the option prevents it.
2.  cacheonly applied only for METADATA - it helps when some optional repositories are not available or metadata are not the latest but there are still functional

In DNF4 the cacheonly configuration option is present but it works correctly only for DNF and CLI user but not from API. DNF4 uses for chacheonly behavior Demands class. I think we should fix that and make it functional for CLI and API users.

There is a question related to cache handling - shall we hardcode the umask for cache files or shall we follow system default setting?

**Comment by jan-kolarik** [comment]
I am just trying to think of any real use cases and benefits of having metadata-only cacheonly variant.

Following up on the latest comment:
> cacheonly applied only for METADATA - it helps when some optional repositories are not available or metadata are not the latest but there are still functional

When some repositories are not available, then I cannot download any packages from there anyway, so the metadata-only doesn't seem to be useful there.

When metadata are expired, but we still want to do some local queries, again the cacheonly applied to everything seems to be enough. 

So the only thing I can think of now is if we want to download remote packages from repos with an expired cache. In this case we could already use the `metadata_expire` option with some bigger value, but we can expect potential problems with expired metadata anyway...

**Comment by j-mracek** [comment]
There is use case to spare download bandwidth. Let use Fedora-updates repository as an example. Fedora-updates is updated every second day but only few packages are modified. Therefore I can use cached outdated metadata to install some packages and there is high chance that it will work. In past - DNF --cacheonly ment to not refresh metadata bu rpms were allowed to download with that option. The situation was changed where we unified behavior with yum.

With DNF5 and additional technologies in DNF there is not such a need for the feature. DNF5 does not downloads filelists and DNF supported zchunk that limits download only to modified chunks.

Therefore the requirement has very low priority. I just want to mention it evaluated and to track it.

**Comment by jan-kolarik** [comment]
> Just as a hint: It would be nice if you could take care that caching doesn't break if root has umask `0077`: https://bugzilla.redhat.com/show_bug.cgi?id=1154272

This issue is tracked in a separate ticket: https://github.com/rpm-software-management/dnf5/issues/789.
