### ISSUE TITLE
Add `dnf5 update` alias

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/dnf5#201]
Please add an `update` alias for `dnf5 upgrade`. `dnf update` is still used many places in the wild.

**Comment by gotmax23** [comment]
Hmm, looks like this is covered by https://github.com/rpm-software-management/dnf5/issues/156 ?

**Comment by jan-kolarik** [comment]
Hello @gotmax23 :slightly_smiling_face:  Yes, it is planned as a subtask in the https://github.com/rpm-software-management/dnf5/issues/156. Therefore I am closing this one.
