### ISSUE TITLE
RepoQuery.filter_id behaves strange

### ISSUE THREAD

**Issue by timlau** [rpm-software-management/dnf5#215]
I have made this python example to get all repositories except *-source & *-debuginfo

https://github.com/timlau/testbed/blob/main/dnf5/repoquery.py

using .filter_id with a list with multiple values, don't give the same result as

using .filter_id with a string and another .filter_id with another string on the same query.

Maybe I have misunderstood how the API is supposed to be used

**Comment by timlau** [comment]
Ok, but it is in consistent with how PackageQuery filters work

```python
        query = PackageQuery(self)
        query.filter_name(["dnf*", "yum*"], QueryCmp_IGLOB)
        for pkg in query:
            print(pkg.get_nevra())
```
This will show all package matching dnf* or yum*

So PackageQuery filters make **OR** and RepoQuery make **AND** on a list, if that is the intended way, It should be documented, but from a logical point of view the should work the same way or maybe support a parameter to define if it is an **OR** or **AND** operation

**Comment by glum23** [comment]
Sorry, I haven't stressed that the main point is the negative GLOB.  The behavior is consistent.  When QueryCmp_IGLOB is used, it works the same way in RepoQuery.filrer_id and PackageQuery.filter_name (for the list=[X,Y]: (contains X) OR (contains Y)). When QueryCmp_NOT_IGLOB is used, both provide items satisfying the related negative formula ((does not contain X) AND (does not contain Y)).

**Comment by timlau** [comment]
Ok, I understand it now, thanks for the explanation
