### ISSUE TITLE
Python Bindings: Memory leak in `Package.get_reason()`

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/dnf5#216]
In this gist (https://gist.github.com/gotmax23/9786917434121c55165e512bf8e7f37d), there are two Python scripts that query for `yt-dlp` and print the `reason` attr. One uses dnf and the other uses libdnf5. 

dnf returns either a string or None. libdnf5 returns a SwigPyObject that doesn't allow accessing the value and results in a memory leak. I guess libdnf5 should return None here because it doesn't have access to dnf's history db.

``` console
$ ./reason.py
yt-dlp-2022.11.11-1.fc37.noarch
<class 'str'>
weak-dependency
```

``` console
$ ./reason5.py
yt-dlp-2022.11.11-1.fc37.noarch
<class 'SwigPyObject'>
<Swig Object of type 'libdnf::transaction::TransactionItemReason *' at 0x7fe0c5964270>
swig/python detected a memory leak of type 'libdnf::transaction::TransactionItemReason *', no destructor found
```

**Comment by jan-kolarik** [comment]
Hello @gotmax23. I don't know against which `dnf5` version or baseline you are testing, but with current `main` state, your script is working for me:

```
[root@5384bee76a4c temp]# ./reason5.py 
yt-dlp-2022.11.11-1.fc36.noarch
<class 'NoneType'>
None
```

**Comment by jan-kolarik** [comment]
Hi @gotmax23 and thanks for the report! The mentioned PRs should fix this problem.
