### ISSUE TITLE
Consider changing the configuration options' Python API to be more Pythonic

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#236]
For now the configuration options API is offering the `set()` and `get*()` methods for working with values stored inside configuration options. Speaking about the Python bindings this is not a traditional way how these operations are implemented in Python.

We could possibly define the `=` operator for these operations on the SWIG layer for Python target.

This is created as a follow-up of the #66 issue where the requests were initially raised.

**Comment by jan-kolarik** [comment]
Hi Vendula and thanks for your post. 

From the Python API user perspective, I definitely agree with you. Your points are absolutely valid there. However, the significant difference between the DNF and DNF5 here I would say is that the API is now generated from the C++ code as opposed to accessing the objects directly like in the original DNF written in Python. 

In this case the DNF5 internals are following kind of different principles like in standard OOP languages, including f.e. the encapsulation instead of using the properties you mentioned.

We will definitely address and discuss this issue in the team, because there were already several complaints about this regression from the existing users of the DNF API. I would also love to make the life easier for our Python clients :slightly_smiling_face:

**Comment by j-mracek** [comment]
Thank you veru much for suggestions. We decided that it would be good to rename methods to get configuration options from `conf.<name_of_option>()` to format `conf.get_<name_of_option>_option()`, because it fits the best to what it does. In future we could also delivery properties in format `config.installroot` only to Python

- [ ] rename configuration options getters in C++ to format `conf.get_<name_of_option>_option()`
It has a high priority

- [ ] Add properties to the python
Medium priority and could be delivered independently from the first task but in this case I would recommend to turn it into a new issue

**Comment by gotmax23** [comment]
>  rename configuration options getters in C++ to format conf.get_<name_of_option>_option()

Will these replace the existing members (e.g.`base.get_config().installroot()`) or be in addition? I assume the latter, as accessing other methods will be necessary for some cases. Perhaps leaving it as is and adding properties down the line would be a better approach to keep it simple and avoid fragmentation or too many ways to do the same thing.

**Comment by jan-kolarik** [comment]
The first checkbox means really just a renaming of the current getters f.e. from `installroot()` to `get_installroot_option()`. All the existing functionality will stay.

The next step is to create shortcuts for Python to easily set and get values which is basically the suggestion from @poncovka.

**Comment by gotmax23** [comment]
I still am not convinced that adding more getter methods is the answer, but fedrq already has a wrapper around this functionality so it doesn't matter too much to me.
