### ISSUE TITLE
Use NSCVA (and not NSVCA) in DNF5 for modules

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#238]
In the original modularity design, context had no information value for runtime or for the DNF solver. The modules identificator (NSVCA) was designed according to importance of element and the context was added after the version. After introduction of the static context the situation was changed and context contains a significant information used by solver. From command line DNF4 ignores context for modular decision.

In DNF5 we could improve the behavior by respecting context from command line and passing the information to the solver, but it requires to modify the identificator structure. (NAME:STREAM:CONTEXT)

The change will require to modify external documentation - https://docs.fedoraproject.org/en-US/modularity/core-concepts/nsvca/

**Comment by ppisar** [comment]
While it makes some sense for static-context modules, it does not make sense for nonstatic-context modules.
I'm not happy with changing meaning of the fields in the notation over all the modularity. It's not only about rewriting the documention. It would mean changing every piece of software which handles NSVCA identifiers. That's unrealistic.

I would rather see DNF5 to use "NAME:STREAM::CONTEXT" syntax (double colon) if it really needs to support specifying contexts by a user.

**Comment by mcurlej** [comment]
The problem here is that even if the change is only localized to DNF itself it will confuse people. All the modules everywhere else would be using the NSVC notation. DNF5 would expect NSCV notation. This is confusing. I am not sure what is the use case and how widely usable would this be. This really looks like a specific problem for a small group of users.

So i am againts it. The only way i would agree to this is that DNF5 would also understand the old format. Also the suggestion by @ppisar is a good one with the "NAME:STREAM::CONTEXT" way.

**Comment by j-mracek** [comment]
Additional information
After introduction of static context, DNF internally use format NAME:STREAM:CONTEXT. It is visible when user ask for degugdata in modular solver part. Therefore there is already a confusion.

### What the change will provide?
Easily enable correct modular dependencies. I would like to enable module or install profile with certain dependencies.
Install perl-DBI with perl:5.32 as dependency
- DNF4 example (not functional) `dnf enable perl-DBI:1.641:820190116185335:0e56aea9`
- DNF5 example (not yet implemented) `dnf enable perl-DBI:1.641:0e56aea9`


### Why it is a good time for such a change
DNF5 is a new product, therefore there are expected some differences

### Who will be affected by the change?
- User of `dnf` from commandline
  - I do not expect much of problems. In DNF4 using version and stream in arguments was possible and supported, but for install operation not really functional for multi context modules (perl-DBI). Module ID in format NSVCA is reported by DNF by modular errors and the `dnf module provides <arg>` command
- Infrastructure
  - NSVCA format is used internally, but I hope that they

List of solution

- Support NSVCA (keep the same behavior with RHEL9 - DNF4)
  - To enable particular context it will require to use globs - `perl-DBI:master:*:LKJHGF`
- Support NSCVA (keep the same behavior with RHEL9 - DNF4)
  - To enable particular context - `perl-DBI:master:LKJHGF`
- Support both formats
  - Not a perfect solution but possible (compatible) - dnf will test two possibilities istead of one. The first match wins
  - `dnf module info` and documentation will use the new format NSCVA
- Support additionaly to DNF4 only "NAME:STREAM::CONTEXT"

**Comment by ppisar** [comment]
> Install perl-DBI with perl:5.32 as dependency

~~~~
# dnf module enable perl-DBI:1.641 perl:5.32
~~~~

**Comment by ppisar** [comment]
I don't say DNF5 cannot support selecting a specific context (although it goes against original modularity design). I don't say DNF5 cannot use N:S:C as an identifier for specifying a given context. I only say that DNF5 should keep printing a module identifier in N:S:V:C format.

**Comment by ppisar** [comment]
> Install perl-DBI with perl:5.32 as dependency
> * DNF5 example (not yet implemented) <code>dnf enable perl-DBI:1.641:0e56aea9</code>

That's not portable because 0e56aea9 context does not mean that it's for perl:5.32. The dependency on perl:5.32 comes from a specific build (N:S:V:C). A later build (N:S:V+1:C) could change/remove the dependency. In other words, the requested feature is based on a false assumption that a context has invariant dependencies.

If you want to build on that assumption, than we need to implement modular obsoletes for a regular ''dnf upgrade'' (i.e. not only for ''dnf system-upgrade'') because there must be a way how to move a stream from one modular dependency to another.

**Comment by j-mracek** [comment]
### Summary of discussions
Change without compatibility could break some user cases related to infrastructure were NSVCA is used
The concept of the change should be handled as an extension of DNF functionality.

### Decision
- DNF5 must be compatible with DNF and accept both formats
- The new format (NSCVA) should be used as primary format - in outputs and order of processing for parsing
- The formal format should be marked as potentially removed in future in DNF5 documentation

**Comment by j-mracek** [comment]
### Requirements

- DNF5 must be compatible with DNF
- NSC should be also supported
- the change must not affect other teams and documentation
  - Satellite
  - MBS

We want to improve user experience and enable additional user-cases, but we cannot break the environment, therefore it would be better to implement minimalist change rather then to change the format that is not perfect for modules with static context but still functional.

### FINAL DECISION
Only add one additional format N:S:C to the original set of format that is supported by DNF4.

**Comment by pkratoch** [comment]
Resolved in https://github.com/rpm-software-management/dnf5/pull/260
