### ISSUE TITLE
Setting $releasever, $arch, and $basearch with Python bindings

### ISSUE THREAD

**Issue by inknos** [rpm-software-management/dnf5#241]
### Discussed in https://github.com/rpm-software-management/dnf5/discussions/232

<div type='discussions-op-text'>

<sup>Originally posted by **gotmax23** January 13, 2023</sup>
Hi! I couldn't figure out how to get or set/override these values with the libdnf5 Python bindings. Can you point me in the right direction?</div>

**Comment by j-mracek** [comment]
I believe that Vars class is something that you are looking for.

```
base = libdnf5.base.Base()
vars = base.get_vars().get()
```

**Comment by j-mracek** [comment]
But this works

```
print(vars.get_value('releasever'))
```
