### ISSUE TITLE
Missing logic around installroot

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#257]
DNF configuration uses several paths that can be related to intallroot or not. As an example lets use `reposdir` configuration option with value `/etc/yum.repos.d/`. If dnf is used in installroot `/tmp/test`, the path is expected to be `/tmp/test/etc/yum.repos.d/`

In DNF4 there is an auto-detection that decide whether path is supposed be modify with `installroot` prefix or not. The mechanism is well described in DNF man pages (option `--installroot`) - see https://dnf.readthedocs.io/en/latest/command_ref.html.
The auto-detection in DNF4 has two weaknesses - it does not work correctly on RHEL and there is no way in API how to enable the auto-detection. Therefore we discussed to replace the auto-detection by two options.

- [ ] Design possibility how to set DNF5 (from commandline) to take configurations from root or installroot path
Solution examples:
  - conflicting options `--installroot=<path>`, `--root=<path>`
  - `--installroot=<path>`, `--use_root`
- [ ] Design API interface to modify paths in configuration class
Example of possibilities
  - Method in base
  - Optional argument of Base::setup()
  - Configuration (bool)

- [ ] Document the new behavior also as a change to DNF4

- [ ] Resolves https://github.com/rpm-software-management/dnf5/issues/248

- [ ] Enable tests in our CI for installroot

**Comment by evan-goode** [comment]
To clarify:
- So `--installroot=/mnt` would look for a configuration file at `/mnt/etc/dnf/dnf.conf`, then error if that file doesn't exist, without falling back to `/etc/dnf/dnf.conf`? And if `--use-root` is _also_ passed, then `/etc/dnf/dnf.conf` is used without looking for `/mnt/etc/dnf/dnf.conf`. Is that what you had in mind?
- What would `--root=<path>` mean?
- Do we need to worry about the case where `installroot` is set in `/etc/dnf/dnf.conf`  and we need to chain load another config file? It might be best if `--installroot` were available only as a command-line option to avoid confusion about this case.
- I kind of like the current behavior in DNF4 where we fall back to the regular paths if the files don't exist in the installroot. Even if the new behavior remained similar to DNF4, we could expose a function in `Base` to search the installroot and modify these paths.

**Comment by j-mracek** [comment]
> To clarify:
> 
>     * So `--installroot=/mnt` would look for a configuration file at `/mnt/etc/dnf/dnf.conf`, then error if that file doesn't exist, without falling back to `/etc/dnf/dnf.conf`? And if `--use-root` is _also_ passed, then `/etc/dnf/dnf.conf` is used without looking for `/mnt/etc/dnf/dnf.conf`. Is that what you had in mind?
Yes with a minor modification - The absence of DNF configuration file is not an issue - dnf.conf contains only configuration overrides, therefore it is completely optional.

**Comment by praiskup** [comment]
Mock needs exactly what is described in `man 7 dnf5-installroot`

    Configuration  file  and  reposdir  are searched inside the
    installroot first.  If they are not present, they are taken from the
    host system.

That matches both the "normal" users' and Mock --installroot use-cases.

  - Normally users just test like `dnf install bash --installroot /somewhere`
    and don't care too much about configuration (perhaps about
    --releasever option)

  - Mock prepares /somewhere/etc/dnf/dnf.conf first, and then runs
    `--installroot /somewhere`

**Comment by evan-goode** [comment]
@praiskup do you have a strong objection to the proposed behavior change, i.e. to not fall back to the config file or reposdir of the host system if they are not present in the installroot? It sounds like there is always a dnf.conf in the installroot in Mock's case, but what about the reposdir?

**Comment by praiskup** [comment]
I think it should be OK from the mock perspective (but .  But I often test DNF
transactions with just

    dnf --installroot /somewhere install some set of packages

I believe this is a common use-case, and the absence of the fall-back will
hurt a bit.  Copying the config files manually is a tedious task.

**Comment by dmach** [comment]
The proposed `--use_root` option seems to be a boolean option, while this probably requires more states.
I think we spoke about an option taking multiple values in the past.
Something like `--installroot-conf=<host|root|auto>`.
The default should be `root`, using either `host` or `auto` during bootstrapping the installroot.

On the other hand, it would be great to avoid having the `auto` option - it's comfortable, but "magical" which makes it difficult do understand and debug.

**Comment by j-mracek** [comment]
`Auto` option will be difficult to implement correctly or have it as default because it is not functional in RHEL distribution and it is impossible to fix it. Therefore do we need the third option anyway (auto)?

With default it is very difficult which variant is more in use.

**Comment by praiskup** [comment]
I concur with @dmach and @j-mracek that the "auto" method is not needed.  The explicit (boolean) option switching to "host config" in #271 seems good enough.
