### ISSUE TITLE
System upgrade and offline transactions (upgrade, distrosync, ...)

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#258]
In DNF there is a possibility to perform offline upgrade for limited transactions and command. I suggest to extend the functionality to allow for any transaction operation offline upgrade and provide the functionality in API of LIBDNF5.

Components requiring that kind of functionality
- DNF
  - system-upgrade
  - offline-upgrade
  - offline-distrosync
- PackageKit
- LEAPP
- Convert2rhel
- Imagebuilder

The workflow should be split to multiple steps:
- [ ] Creation transaction, download packages and storing of transaction
- Store all required data to perform identical transaction after reboot
- DNF4 implementation is good but not perfect
  - not storing package or group reasons
  - Store group planned operation
  - Store module planned operation

- [x] #1052
Primary implement rebooting mechanism like DNF4 system-upgrade uses. LEAPP uses an alternative way of running stored transaction. It is superior to DNF approach for system upgrade, because it uses rpm from target system, but there are also some weak sides.
- [ ] loading of stored transaction and performing
We need to ensure that the transaction will be identical to approved in step 4 from multiple sides - RPM content, groups, modules, history DB and System-state
We can:

- store more information about transaction (reason, package checksum, ...)
- add check step that replayed transaction is identical - removed packages are not checked much in DNF4.
- alternatively we don't need to rerun libsolv transaction 
  - transaction itself is verified by RPM
  - ensure that RPMs are still identical what we stored (checksums + length)
  - optionally - system was not changed - rpm content - using RPM cookies
  - requires a new way how to update history DB, system state, and filling RPM transaction

**Comment by gbcox** [comment]
Thanks for referring me here from Fedora Bugzilla.  Not sure how you're defining priorities here but I would consider system upgrades / offline transactions a high priority unless you plan on having people run both the old and new DNF at the same time.  I'm the creator of the RFE for offline transactions: https://bugzilla.redhat.com/show_bug.cgi?id=1382063 and it came out a mailing list discussion which basically said:  Don't run DNF Upgrade within GNOME, KDE or any other Fedora DE.  We had to wait several years after the RFE was written for this functionality to finally be available.  It doesn't make sense to migrate to DNF5 and lose it, for any period of time.

**Comment by pirat89** [comment]
Hi \o finally got a time to write notes what functionality is needed for the in-place upgrade from the current "leapp" POV. Possibly it will be updated yet, but to share at least something already.

* we need to be able to specify the installroot & where the data (repos, transaction, rpms,..) should be cached
  * dnf is executed from a container so the host system is in a specific directory 
* configurable (possibility to activate/disable plugins, like subscription-manager)
* possibility to provide additional instructions from an input file (ideally json, schema of the currently used json file provided below; can be also extended when there is any idea what would be good to add also; possibilty exclude packages?... thinking loud)
  * instructions covered in the schema below should be understood as a required minimum what should be possible; briefly:
    * list of packages strictly required to be removed (more packages could be removed, but these are minimum)
    * list of packages to be installed
    * list of local packages to be installed (out of repositories, based on provided paths to rpms)
    * list of packages to be updated
    * module streams to be enabled (all previous module streams expected to be reset)
    * repositories to be used (all others are expected to be disabled for the transaction)
    * affect DNF options, like: gpgcheck, releasever, ....
* distro sync should be included - some packages are going to be downgraded if provided on the target system
* provide information about the transaction in parsable output (ideally json format, stored in a file)
  * to know what's going to happen - what's going to be installed, removed, kept, also what's missing based on input data; e.g. a package marked to be installed is not discovered in the repo-metadata, ... possibly problem? e.g. conflicts
  * data will be used by other applications out of dnf
* do not care about about booting to upgrade environment / skip creating the artefacts to affect the boot
  * dnf will be called by leapp
* have a possibility to split the execution in various phases (including the repeating of some steps!!)                                                                                
  * **check**  - check we are able to calculate the DNF transaction using only the YUM/DNF repositories metadata
    * no packages will be downloaded yet downloaded
  * **download** - (calculate the transaction, ) download all packages and test if the transaction is duable using data contained in RPMs (include search for file conflicts, disk space, ...)
  * **dry-run** - test the transaction again with the cached content
    * same as the download, but use only the cached data (repositories, downloaded rpms..)
      * the system is changed between the download and dry-run
        * e.g. less space is available; for more info: BZ: 1976932 and PR [#734](https://github.com/oamg/leapp-repository/pull/734)
  * **upgrade** - perform the DNF transaction using the cached data only!
* handle RHUI related stuff
  * For RHUI (AWS) functionality we need to be able to read and write the "repo.baseurl" and "repo.mirrorlist" (self.base.repos.all())

current JSON input file (pseudo schema; sorry, time pressure, so let's do it in this way to provide something):
```json
{
  "dnf_conf": {
    "allow_erasing": boolean,
    "best": boolean,
    "debugsolver": boolean,
    "disable_repos": boolean,
    "enable_repos": [
        "repoid"
    ],
    "gpgcheck": boolean,
    "installroot": "/installroot",
    "platform_id": "platform:el9",
    "releasever": "9.0",
    "test_flag": boolean
  },
  "pkgs_info": {
    "local_rpms": [
        "path"
    ],
    "modules_to_enable": [],
    "to_install": [
        "pkgname"
    ],
    "to_remove": [
        "pkgname"
    ],
    "to_upgrade": [
        "pkgname"
    ]
  },
  "rhui": {
    "aws": {
      "on_aws": boolean,
      "region": null / string
    }
  }
}
```

**Comment by AdamWill** [comment]
Oh, wow, I hadn't realized this but I agree it needs to be a high priority. Ideally this should have been done before the Rawhide swap :( `dnf offline-upgrade` is the recommended way to update anything besides a desktop which implements offline updating via PackageKit, and it's how I update even desktop installs (it's just more convenient than using GNOME Software).

**Comment by mcrha** [comment]
For what its worth, the gnome-software usage is much simpler than leapp's; it's using PackageKit under the hood, but maybe this will give you an idea what could work in a simpler environment. The operations/functions/APIs being used:
* download the packages & prepare the update
* trigger the update
* cancel the update
* have an API or a convention to recognize an offline update is prepared (GNOME Shell can use it on logout to ask whether the update should be installed)
* have a signal notifying the changes around the offline update state, like prepared/discarded (some operations can discard the prepared update, in which case the listener can initiate a new "download & prepare" operation).

It would be nice if the `org.rpm.dnf.v0.rpm.Rpm::list` is smart enough and reports package's `download_size` attribute as `0` in case the package is already downloaded for the update. PackageKit does that.

**Comment by mcrha** [comment]
The description of the #1052 speaks about major version upgrade, like Fedora 39 to Fedora 40, if I understand it correctly. Is there a similar functionality for package update? like the `distro-sync` split into download and then apply in offline.

**Comment by evan-goode** [comment]
> The description of the #1052 speaks about major version upgrade, like Fedora 39 to Fedora 40, if I understand it correctly. Is there a similar functionality for package update? like the `distro-sync` split into download and then apply in offline.

Yes, there is now an `--offline` flag that allows any operation (`install`, `upgrade`, `distro-sync`, etc.) to be run in the same offline environment that is used for the major version upgrade. See example usage here: https://dnf5.readthedocs.io/en/latest/commands/offline.8.html#examples.

The old `offline-distrosync` and `offline-upgrade` commands from the DNF 4 system-upgrade plugin are also supported now; they are essentially just aliases to `dnf5 distro-sync --offline` and `dnf5 upgrade --offline`.

Related: https://github.com/rpm-software-management/dnf5/issues/1224.

**Comment by mcrha** [comment]
I see, thanks for the pointers and clarification. I wasn't sure it's covered from the #1052 content.
