### ISSUE TITLE
build: Fails to build due to under-linking

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#267]
When using stricter options for linking the project fails to build due to undefined symbols. Steps:

```
   export LDFLAGS='-Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,defs'
   cmake .....
   make
```

current result is tons of undefined references, beginning with:

```
/usr/bin/ld: CMakeFiles/actions.dir/actions.cpp.o: in function `(anonymous namespace)::Actions::substitute(libdnf::base::TransactionPackage const*, libdnf::rpm::Package const*, std::basic_string_view<char, std::char_traits<char> >, std::filesystem::__cxx11::path, int)':
..../dnf5/libdnf-plugins/actions/actions.cpp:223: undefined reference to `libdnf::OptionBinds::Item::get_value_string[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:239: undefined reference to `libdnf::rpm::Package::get_name[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:241: undefined reference to `libdnf::rpm::Package::get_arch[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:243: undefined reference to `libdnf::rpm::Package::get_version[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:245: undefined reference to `libdnf::rpm::Package::get_release[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:247: undefined reference to `libdnf::rpm::Package::get_epoch[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:249: undefined reference to `libdnf::rpm::Package::get_na[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:251: undefined reference to `libdnf::rpm::Package::get_evr[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:253: undefined reference to `libdnf::rpm::Package::get_nevra[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:255: undefined reference to `libdnf::rpm::Package::get_full_nevra[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:257: undefined reference to `libdnf::rpm::Package::get_repo_id[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:259: undefined reference to `libdnf::rpm::Package::get_license[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:261: undefined reference to `libdnf::rpm::Package::get_location[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:263: undefined reference to `libdnf::rpm::Package::get_vendor[abi:cxx11]() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:268: undefined reference to `libdnf::transaction::transaction_item_action_to_letter[abi:cxx11](libdnf::transaction::TransactionItemAction)'
/usr/bin/ld: CMakeFiles/actions.dir/actions.cpp.o: in function `(anonymous namespace)::Actions::parse_action_files()':
..../dnf5/libdnf-plugins/actions/actions.cpp:367: undefined reference to `libdnf::ConfigMain::pluginconfpath() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:369: undefined reference to `libdnf::ConfigMain::pluginconfpath() const'
/usr/bin/ld: ..../dnf5/libdnf-plugins/actions/actions.cpp:369: undefined reference to `libdnf::OptionString::get_value[abi:cxx11]() const'
```

Using only `LDFLAGS='-Wl,--as-needed` makes it build with no problem.

**Comment by j-mracek** [comment]
@mcrha May I ask you whether the issue is still valid and whether you consider the issue as critical?

**Comment by mcrha** [comment]
Yes, it is still reproducible on the main branch at commit bf87232f58c89d31a8303344ed198331dd2b68db .

How much critical, well, it's up to you to decide. It's not an ideal state, but I know the workaround, thus no big deal from my side.

**Comment by ppisar** [comment]
Is it triggered with "-Wl,-z -Wl,defs"? The other linker flags are used in ELN build regularly. Frankly, after reading -z defs documentation in ld(1) manual, I don't understand what it is good for. From the error message, I would guess a plugin, technically a shared library, is either not linked to libdnf5, or the plugin includes header files with private symbols. However, according to the manual -z defs pertain non-shared library objects.

**Comment by ppisar** [comment]
Now I understand the option. By default GNU linker behaves differently when linking programs and when linking libraries. -z defs and -z undefs enforce uniform behavior either that or another way.

**Comment by jrohel** [comment]
I've created a PR https://github.com/rpm-software-management/dnf5/pull/848 that fixes missing links in swig generated libraries.

But "actions.cpp", more precisely everything in the "libdnf5-plugins" and "dnf5-plugins" directories are plugins. I'm not sure how to solve it with them yet. And is it correct to compile the plugins with "-Wl,-z -Wl,defs"?

**Comment by mcrha** [comment]
> And is it correct to compile the plugins with "-Wl,-z -Wl,defs"?

I do not think the LDFLAGS variable can be selectively applied, not without changes in the build scripts, but those might be wrong (removing distro-specified flags, which should be left there).

As long as the plugins use public API (headers), that API should contains also public libraries, thus the plugins should link against those libraries, instead of expecting the plugin is loaded into an environment, where all the public API libraries are already loaded in the process.

That's my understanding of the matter. I can be wrong.

**Comment by jrohel** [comment]
1. I agree that for example "dnf5-plugins/changelog_plugin" should link to "libdnf5" (since it uses it directly internally) and not rely on the dnf5 application to load it.

2. But link the dnf5 application? dnf5 will definitely be in the environment, because it is the one that loads the plugin. And using `target_link_libraries` to link the plugin with dnf5 will check that dnf5 has `ENABLE_EXPORTS` enabled. Good thing too. I will add. But linking on the ELF platform will not happen.

3. But I'm still not sure if we want to split the dnf5 application into a library and a small wrapper using it. After all, plugins are loadable MODULES. And they use `ENABLE_EXPORTS` which is intended for that. https://cmake.org/cmake/help/v3.14/prop_tgt/ENABLE_EXPORTS.html

I think the first PR https://github.com/rpm-software-management/dnf5/pull/848 is OK. I will prepare a follow-up PR. According to points 1 and 2. But I will not yet change the application to a library with a "wrapper", which will turn it into an application.

**Comment by mcrha** [comment]
Linking library (module) against executable (or another module) is not a thing one should do, let aside it won't work (from my point of view).

Some projects have it as you suggested, split the "API" into a linkable library and have the application code load/link against that library too, thus make the app code work like a wrapper. It adds certain complexity in the code maintenance for sure. The "only" advantage of this approach is a clean linker tree within the code. If it feels as an unnecessary overhead for the dnf5 use case, then feel free to not doing that.

By the way, the https://github.com/rpm-software-management/dnf5/blob/main/libdnf5-plugins/actions/actions.cpp seems to include these internal headers:
```
#include <libdnf5/base/base.hpp>
#include <libdnf5/base/transaction.hpp>
#include <libdnf5/common/exception.hpp>
#include <libdnf5/rpm/package_query.hpp>
#include <libdnf5/utils/bgettext/bgettext-mark-domain.h>
```
are any/all of them considered "an application" code? I do not know the code structure of the dnf, I'm sorry if it's a lame question.

**Comment by jrohel** [comment]
> are any/all of them considered "an application" code? I do not know the code structure of the dnf, I'm sorry if it's a lame question.

It's more complicated. There are 2 types of plugins in the dnf5 project.
The "dnf5-plugins" directory contains the dnf5 application plugins. So they are loaded by the dnf5 application.
The "libdnf5-plugins" directory contains the libdnf5 library plugins. So they are loaded by the libdnf5 library. These plugins have no relation to the dnf5 application. Action plugin is a plugin of the libdnf5 library. It doesn't use anything from the dnf5 app.

**Comment by jrohel** [comment]
I prepared a second PR https://github.com/rpm-software-management/dnf5/pull/853 that tune library linking.
With my two PRs, compiling with `LDFLAGS='-Wl,--as-needed -Wl,-z -Wl,relro -Wl,-z -Wl,now -Wl,-z -Wl,defs'` fails only for dnf5 plugins.

**Comment by j-mracek** [comment]
@jrohel @mcrha May I ask you a question? Do you consider the issue as resolved?

**Comment by mcrha** [comment]
I tried with the main branch at commit 8b515b7ef0696af425e2d50874b5026abacf18ff and it still fails when linking changelog_cmd_plugin.so, builddep_cmd_plugin.so and copr_cmd_plugin.so (the build stopped with these three), which reflects the last Jaroslav comment (about "only plugins fail now).

That being said, the situation is better, but not fixed.

If you want to, then feel free to close this (even proper linking flags would be better). I know how to workaround the problem.

**Comment by ppisar** [comment]
changelog_cmd_plugin, builddep_cmd_plugin, and copr_cmd_plugin are plugins into dnf5 program which call symbols for the program. "-z defs" cannot work for such plugins.

We could nullify LDFLAGS "-z defs" effect by appending "-z undefs" to linker flags for these specific dnf5 program plugins, but I'm not sure it's worth of working around unreasonable distribution global LDFLAGS.

I will look whether it's possible, if it is, I will create a pull request, otherwise I will reject this bug report.

**Comment by ppisar** [comment]
I posted #994 PR which should resolve this issue.
