### ISSUE TITLE
Add a download method for Transaction class

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#277]
The new method should simplify the workflow of DNF5 when transaction is created. 

Basically to replace following code 
```
# Add the inbound packages (packages that are being installed on the system)
# to the downloader.
for tspkg in transaction.get_transaction_packages():
    if libdnf5.base.transaction.transaction_item_action_is_inbound(tspkg.get_action()):
        downloader.add(tspkg.get_package())

# Download the packages.
#
# The first argument is `fail_fast`, meaning the download will fail right away
# on a first package download failure. The second argument is `resume`, if
# `true`, the downloader will try to resume downloads of any partially
# downloaded RPMs.
downloader.download(True, True)
```

By 
```
transaction.download()
```

- [x] add the method to Transaction Class
- [x] Modify tutorials to use the method
- [ ] Replace the code in DNF5 part to use the download method

**Comment by j-mracek** [comment]
@evan-goode I am sorry I forget to mention one sub-task.

**Comment by evan-goode** [comment]
https://github.com/rpm-software-management/dnf5/pull/313 has been merged. I think that's all the refactoring we want to do for now.
