### ISSUE TITLE
Enable upstream unstable nightly copr builds for EPEL9

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#279]
To build DNF5 for EPEL9 it will require to rebuild a lot of RHEL components (core), but it was a requirement from our QE, therefore it has a high priority. Builds are for testing therefore install-ability on the standard system (workstation) is a perk, not a requirement.

**Comment by inknos** [comment]
The following repos have been created to enable dnf5 in epel9 and it successfully builds.
This is the branch used to build which adds patches to build on epel9. https://github.com/inknos/dnf5/tree/rhel9 No specific version is rebased. Unit tests are disabled for now.

COPR:
[dnf5](https://copr.fedorainfracloud.org/coprs/nsella/dnf5-epel9/)
[smartcols](https://copr.fedorainfracloud.org/coprs/nsella/smartcols-epel9/)
[rpm==4.1.7](https://copr.fedorainfracloud.org/coprs/mdomonko/rpm-4.17.x/)

**Comment by inknos** [comment]
dnf5 was rebased to 5.0.9

**Comment by glum23** [comment]
QEs have tested the dnf5 build provided for EPEL9 and as a result have created several issues. When the issues will be resolved, QEs will request a new build of dnf5 for EPEL. This issue can be closed now.
