### ISSUE TITLE
Add i686, s390x, and ppc64le builds to Copr

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/dnf5#282]
Can you please enable i686, s390x, and ppc64le Copr builds in https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-unstable/? This matches Fedora and will allow me to test [fedrq](https://git.sr.ht/~gotmax23/fedrq)'s new libdnf5 backend across all Fedora arches.

**Comment by inknos** [comment]
we are having some issues in our nightly repo which is preventing to enable i686, s390x, and ppc64le for dnf5 unstable but I am working on it!

**Comment by inknos** [comment]
Done. https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-unstable/build/5535355/
