### ISSUE TITLE
Make downloading transaction packages easier for API users

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#289]
Currently there are several places where the code for downloading packages from resolved transaction is repeated.

This code is like this:
```
libdnf::repo::PackageDownloader downloader;

for (auto & tspkg : transaction.get_transaction_packages()) {
    if (transaction_item_action_is_inbound(tspkg.get_action()) && 
        tspkg.get_package().get_repo()->get_type() != libdnf::repo::Repo::Type::COMMANDLINE) {
        downloader.add(tspkg.get_package());
    }
}

downloader.download(true, true);
```
Let's put this logic at a single place and expose it for API users. It could be then reused also by `download` command etc. I suggest to add a `download` method for the `libdnf::base::Transaction` class.

**Comment by kontura** [comment]
I believe this is related to: https://github.com/rpm-software-management/dnf5/issues/277

**Comment by jan-kolarik** [comment]
You're right, next time I should first look at existing issues :slightly_smiling_face:
