### ISSUE TITLE
Undefined substitution variables kill the Python process 

### ISSUE THREAD

**Issue by poncovka** [rpm-software-management/dnf5#292]
When I try to get a value of an undefined substitution variable, it kills the Python process.

```
base = libdnf5.base.Base()
vars = base.get_vars()
vars.get_value("undefined")
```

The example above fails with the exit code 134 and the error messages below.

```
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)
```

Please, raise an exception instead.

**Comment by j-mracek** [comment]
Thank you for the report. We raise the exception, but it is C++ exception. It requires to catch it in SWIG and convert it into Python exception.
