### ISSUE TITLE
TypeError: 'EnvironmentQuery' object is not iterable

### ISSUE THREAD

**Issue by poncovka** [rpm-software-management/dnf5#296]
Some queries like `EnvironmentQuery` and `GroupQuery` doesn't seem to be iterable. However, you can iterate over `RepoQuery`.

```
base = libdnf5.base.Base()
base.setup()
query = libdnf5.comps.EnvironmentQuery(base)
```

If I try to iterate the items of the query I get a `TypeError` exception.

```
>>> print([env.get_environmentid() for env in query])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'EnvironmentQuery' object is not iterable
```

If I try to iterate the output of `query.list()` I get a similar exception.

```
>>> print([env.get_environmentid() for env in query.list()])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'SwigPyObject' object is not iterable
```

**Comment by jan-kolarik** [comment]
Thanks for the report. It seems the Python wrapper is not generated correctly.
