### ISSUE TITLE
Error thrown when loading a non-existent config file

### ISSUE THREAD

**Issue by evan-goode** [rpm-software-management/dnf5#305]
DNF5 throws an error when it tries to load a config file that doesn't exist:
```
$ mv /etc/dnf/dnf.conf /etc/dnf/dnf.conf.old
$ dnf5 -y install hello
filesystem error: cannot open file: No such file or directory [/etc/dnf/dnf.conf]
```

DNF4, however, ignores the missing file and works fine.

**Comment by j-mracek** [comment]
This is an issue. DNF5 must be able to work without presence of config. There is one exception in DNF4 - when user specify config from commandline - `sudo dnf install --config /asas/asas.conf sss` then it complains `Config error: Config file "/asas/asas.conf" does not exist`.

Also check the behavior of DNF4 when you do not have a permissions for `dnf.conf`.

**Comment by j-mracek** [comment]
The implementation in DNF4 was not optimal:

```
        filename = conf._get_value('config_file_path')
        if (conf._get_priority('config_file_path') == dnf.conf.PRIO_COMMANDLINE) and \
                not os.path.isfile(filename):
            raise dnf.exceptions.ConfigError(_('Config file "{}" does not exist').format(filename))

        # read config
        conf.read(priority=dnf.conf.PRIO_MAINCONFIG)
```
It tested the existence of the path and config path priority and then it called conf.read().
DNF4 API did not read the configuration by default - it required additional call.
