### ISSUE TITLE
Create documentation for dnf configuration

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#309]
We need to document all dnf configuration options - both main and repository. Ideally we need both - readthedoc and man pages.

- [ ] document main configuration options
- [ ] document repository configuration options (some options can be found in both sections)

**Comment by j-mracek** [comment]
It would be perfect if the description will be available only in one copy to avoid problems with synchronization.

There are:
Main options
Repo options
Repo and Main options
There might be options that are not bind to configuration files (dnf.conf or .repo file) therefore the value cannot be modify using those configurations files.
