### ISSUE TITLE
Documentation doesn't match available rpms

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#334]
I'm using `libdnf5-5.0.6-2.fc38.x86_64` while working my way through converting lorax to dnf5 and the documentation at https://dnf5.readthedocs.io/en/latest/tutorial/bindings/python3/transaction.html doesn't match the current rpm's behavior in at least 2 cases:
 * There is no `transaction.download()` function (worked around that using the code from https://github.com/rpm-software-management/dnf5/commit/9f8d4a39840a86ab352c95669b054bc18daf76ce)
 * Trying to use `transaction.run()` complains `TypeError: Wrong number or type of arguments for overloaded function 'Transaction_run'.`

**Comment by jan-kolarik** [comment]
Hello Brian, I think that the mentioned docs are matching latest upstream version of  the `main` branch while you are using the `dnf5` package released in downstream, Fedora. It should be enough to just switch the docs to the `stable` mode in the lower left corner ...

![stable_docs_screen](https://user-images.githubusercontent.com/110612307/223631299-8231fcca-1d6b-4899-91cd-cc9cd6576c01.png)

**Comment by bcl** [comment]
True, but given that this is a fast changing library under heavy development shouldn't rpms be released more frequently? I really don't want to make changes that will immediately need to be reworked when main is released.

**Comment by j-mracek** [comment]
Our plan is to release DNF5 every  second week.
