### ISSUE TITLE
DNF5 is confusing when transaction is performed without root permission

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#337]
DNF4 is checking whether command has root privileges
`Then please feel free to rename it. --use-host-config and configuration option use-host-config.`

In dnf5 there is no check and commands ends after downloading of all packages on `filesystem error: cannot create directories: Permission denied [/run/dnf]`  but I have seen also error related to GPGCHECK.

We need to check permission before download of packages or at the beginning like DNF4.

**Comment by jan-kolarik** [comment]
I am closing this one in favor of https://github.com/rpm-software-management/dnf5/issues/849 where more information and discussion is provided.
