### ISSUE TITLE
Do we need to add obsoletes for install action?

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#339]
[Bug 2176263](https://bugzilla.redhat.com/show_bug.cgi?id=2176263) - Attempting to run "dnf install systemd-udev" no longer installs systemd-udev on F37 container

This bug demonstrates really strange behavior. Let me try to describe it here:

Let's have a package **systemd-udev-1.0**.
Later, the maintainers decide to deliver a feature from this package as a separate subpackage using obsoletes:

Now we have
**systemd-udev-2.0**
  Obsoletes: systemd-udev < 2   (I would argue this is not needed since the name has not changed)

**systemd-boot-unsigned-2.0**
  Obsoletes: systemd-udev < 2  (important part is that there is only obsolete, package does not provide systemd-udev)

If you try to run `dnf5 install systemd-udev` with these three packages available, the result is kind of unexpected:
```
# dnf5 install systemd-udev
============================================================================================
 Package                      Architecture  Version              Repository            Size
============================================================================================
Installing:
 systemd-boot-unsigned        noarch        2.0-1.fc29           split-package        6.0 k

Transaction Summary
============================================================================================
Install  1 Package
```

The package `systemd-boot-unsigned` does not provide systemd-udev, only obsoletes the package.
I dumped the debugsolver data and this is interesting part of this transaction:
```
job install oneof systemd-boot-unsigned-2.0-1.fc29.noarch@split-package
                  systemd-udev-1.0-1.fc29.noarch@split-package
                  systemd-udev-2.0-1.fc29.noarch@split-package [forcebest,setevr,setarch]
```

So libdnf actually allows libsolv to install `systemd-boot-unsigned`.

Here is a simple test for the CI - https://github.com/rpm-software-management/ci-dnf-stack/commit/3301e50fafff3ab8f61ea2a3a785ff7bd3f859ed

So the question is - why we add obsoletes (without provides) to the install job? I tried to dig in dnf git history to find why the feature was added (because you can observe exactly the same behavior in dnf4), but did not find any reason for it.

**Comment by j-mracek** [comment]
This is very complicated topic. The original reason of adding obsoletes was that user complains that after installation of the latest package package is replaced and remove by the first upgrade. They expect that obsoletes will be applied in the first place. Obsoletes are not related to what obsoleters provides.

**Comment by m-blaha** [comment]
I did a bit more digging and found this - https://github.com/rpm-software-management/dnf/pull/1708
So even though the behavior might be surprising, it's documented and expected.

**Comment by j-mracek** [comment]
This the first PR with introduction of handling of obsoletes for install - https://github.com/rpm-software-management/dnf/pull/609. This PR modify the implementation to use queries - https://github.com/rpm-software-management/dnf/pull/647

**Comment by m-blaha** [comment]
Hm thinking about it more, this is not exactly a "split in the upgrade path". It's just splitting off the new package, but the old package with the same name continues to exist.
I believe both obsoletes should be installed only when upgrading from `systemd-udev-1`, because you do not know which part of the old package the user actually needs.
The current behavior makes sense in case the old name ceased to exist - either by renaming the old package, or by splitting it into several new packages with completely new names.

**Comment by m-blaha** [comment]
There are two possible solutions to the issue:

1. experiment with SOLVER_FAVOR / SOLVER_DISFAVOR flags. We do not have much experience with it, it is not used in dnf4, we do not know how strong/weak this flag is (compared with repo priority, vendor, obsoletes)
2. add only obsoleters of the best version of the package (need to take also priority and vendor into account)
