### ISSUE TITLE
Linters for the repo

### ISSUE THREAD

**Issue by jpodivin** [rpm-software-management/dnf5#343]
This is an extremely minor issue. But I believe it would be much easier to maintain contribution standards, as described in[0], if the project were to utilize some linters.

In Openstack we've had a very good experience with plain pre-commit[1], which is lightweight and extremely modular.
There would be a relatively significant initial patch involved, as all the rule issues would have to be resolved, but besides that it should be mostly self-sustaining.

[0] https://dnf5.readthedocs.io/en/latest/contributing/index.html
[1] https://pre-commit.com/

**Comment by m-blaha** [comment]
I concur. @inknos pointed pre-commit out to me some time ago, I've been testing it for several weeks and it is really helpful.

**Comment by jpodivin** [comment]
I'll propose a minimum set of hooks and we can later expand as needed. It shouldn't get too complex as otherwise nobody will run them.

**Comment by jan-kolarik** [comment]
I also support this idea. As it is not currently a part of the commit process, it is sometimes annoying to find out having an extra space at the end of the line only after CI tests are initiated...
