### ISSUE TITLE
Add documentation regarding creating custom aliases

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#348]
Create a simple tutorial / section in documentation how-to create and deploy custom user aliases.

**Comment by jan-kolarik** [comment]
Asked from community during Fedora Test Day.

**Comment by j-mracek** [comment]
The issue might be a duplicate of https://github.com/rpm-software-management/dnf5/issues/131

**Comment by jan-kolarik** [comment]
> The issue might be a duplicate of #131

Yes, as the issue was modified with adding the documentation, I can close this one to track it on the single place.
