### ISSUE TITLE
Include rpmlint in pre-commit

### ISSUE THREAD

**Issue by inknos** [rpm-software-management/dnf5#351]
Follow up to https://github.com/rpm-software-management/dnf5/pull/344. Better to include rpmlint check in pre-commit. Rpmlint is not included in pre-commit hooks, therefore a custom solution may be required to use rpmlint such as local installation.

**Comment by jpodivin** [comment]
Or we could release it as a hook. That would simplify things in the long run for dnf5 and for other projects that need rpmlint to validate files.

https://pre-commit.com/index.html#new-hooks

**Comment by inknos** [comment]
good idea, I made a quick repo with rpmlint hooks

https://github.com/rpm-software-management/dnf5/pull/361
