### ISSUE TITLE
Explain how to exclude packages

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#357]
I'm trying to convert the osbuild-composer dnf-json script to libdnf5 and am hitting a problem with this chunk of (python) code:

https://github.com/osbuild/osbuild-composer/blob/main/dnf-json#L215

```
            self.base.install_specs(
                transaction.get("package-specs"),
                transaction.get("exclude-specs"),
                reponame=transaction.get("repo-ids"),
            )
```

How do you add a list of packages, along with excluding another list, and limit it to a specific set of repos?
Limiting to the repos may not be strictly needed, but we do need to be able to exclude packages.

Thanks,
Brian

**Comment by jan-kolarik** [comment]
For excluding a specific list of packages from the specific repository you could use a following API script snippet example which is excluding `zlib` and `zlib-devel` packages from the `updates` repo:

```python3
import libdnf5

base = libdnf5.base.Base()
base.load_config_from_file()
base.setup()

sack = base.get_repo_sack()
sack.create_repos_from_system_configuration()

repo_query = libdnf5.repo.RepoQuery(base)
repo_query.filter_id('updates')
repo = next(iter(repo_query))
repo.get_config().excludepkgs = ['zlib', 'zlib-devel']

sack.update_and_load_enabled_repos(True)

package_query = libdnf5.rpm.PackageQuery(base)
package_query.filter_available()
package_query.filter_name(['zlib*'], libdnf5.common.QueryCmp_IGLOB)
packages = [pkg.get_nevra() for pkg in package_query]

print(packages)
```

**Comment by jan-kolarik** [comment]
Let me know please if it is helpful :slightly_smiling_face:
