### ISSUE TITLE
Output user name and login at dnf5 history info

### ISSUE THREAD

**Issue by geraldosimiao** [rpm-software-management/dnf5#358]
Actual dnf 4 history info returns, among other information, user name and login.
Dnf5 instead return only user ID at the same field (as seen on screenshot attached).
It is possible to add again the user name and login? Can be together with user ID.
![Screenshot_20230315_140620-1](https://user-images.githubusercontent.com/72357821/225504810-345d1d81-2e8b-4d42-8a5c-334cb18afbc9.jpg)

**Comment by derickdiaz** [comment]
For this issue, I believe we can use include the <pwd.h> and use the getpwuid() function to resolve the UID to a valid username within in the transaction.cpp file. If the function returns a null, then we just print out the standard uid as it has been doing.

Example: https://linux.die.net/man/3/getpwuid
I tried using this function on my fedora box and it worked.

**Comment by ppisar** [comment]
I believe this issue has been fixed by your PR #1203.
