### ISSUE TITLE
Package object should implement remote_location()

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#366]
In libdnf4 the package object method `.remote_location()` returned the remote url where the package could be downloaded from. This is a core part of how osbuild works, so it would be very useful if libdnf5 could provide the same information.

I have worked around it temporarily in this code:
https://github.com/osbuild/osbuild-composer/pull/3332/commits/d6f4f66a5214249a8e342fc04d1cf26664dd1580

but note that this doesn't provide the final resolved url, it provides the intermediate url pointing to the mirror url used to setup the repo.

**Comment by gotmax23** [comment]
This is also a blocker for [fedrq#20](https://todo.sr.ht/~gotmax23/fedrq/20).

For the record, here is dnf4's implemention:

https://github.com/rpm-software-management/dnf/blob/110c40194f23d9587b02dd221e0162332f66793c/dnf/package.py#L292-L303

https://github.com/rpm-software-management/dnf/blob/110c40194f23d9587b02dd221e0162332f66793c/dnf/repo.py#L636-L659

**Comment by kontura** [comment]
PR: https://github.com/rpm-software-management/dnf5/pull/664

**Comment by kontura** [comment]
We have added `get_remote_locations()` it returns a vector of urls.
