### ISSUE TITLE
add_install(environment) doesn't appear to be working.

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#367]
I can add groups, but when selecting an environment it doesn't add anything to the transaction:

``` python
import libdnf5

base = libdnf5.base.Base()
base.load_config_from_file()
conf = base.get_config()
conf.zchunk().set(False)
base.setup()

sack = base.get_repo_sack()
sack.create_repos_from_system_configuration()

repo_query = libdnf5.repo.RepoQuery(base)
repo_query.filter_enabled(True)
print("\n".join(list(r.get_name() for r in repo_query)))

print("update and load enabled repos...")
sack.update_and_load_enabled_repos(False)
print("done.")

goal = libdnf5.base.Goal(base)
#goal.add_rpm_install("tmux")

# Environment doesn't work
#goal.add_install("@Fedora Cloud Server")
goal.add_install("@^cloud-server-environment")

# group works
#goal.add_install("@rpm-development-tools")

transaction = goal.resolve()
for tsi in transaction.get_transaction_packages():
    print(tsi.get_package().get_nevra())
```

**Comment by jan-kolarik** [comment]
Hi Brian, yes, installing environment and modules is not implemented yet. There is a `TODO` in the source code, but it should be definitely tracked in the issue, so thanks for filing one!

**Comment by bcl** [comment]
I see that there is an environment PR #554 so I patched the latest version and gave it a try. Some things I ran into:

I can no longer parallel install libdnf5 on rawhide/f39. I think it is a mistake to do this so early in the process. It is going to make it much harder to transition to the new library. I worked around this by doing it on Fedora 38.

conf.zchunk seems to have changed to a real bool instead of a function. That's good :)

My script above (with zchunk fixed) still doesn't work with environments. Still works with plain groups.

**Comment by bcl** [comment]
Testing this against #585 rebased on main and it mostly works!

For some reason I thought dnf supported `^@environment` but that's an Anaconda syntax. So my test script was slightly wrong :)

With a patched dnf5 scratch build I can now install `@cloud-server-environment` and that works. But it doesn't work with `@Fedora Cloud Server` which is how it used to work (and how osbuild-composer currently refers to the environment).  It's not a huge problem for us to change it to the id since it's just a constant, but mapping names to the id can sometimes be difficult to figure out so it would be generally helpful if names would continue to work.

**Comment by jan-kolarik** [comment]
I think you can just pass the custom `GoalJobSettings` to the `add_install` method. Like this:
```python
settings = libdnf5.base.GoalJobSettings()
settings.group_with_name = True
goal.add_install("@cloud-server-environment", settings)
```

**Comment by bcl** [comment]
Ah! Yes, with that I can do `goal.add_install("@Fedora Cloud Server", server)`, thanks!

**Comment by m-blaha** [comment]
> For some reason I thought dnf supported `^@environment` but that's an Anaconda syntax. So my test script was slightly wrong :)

Thanks for the remainder! I want to have this syntax also supported. BTW kickstart files use slightly different syntax - `@^environment` (positions of `@` and `^` swapped). Just to be sure - is there a typo in your example?

**Comment by m-blaha** [comment]
@bcl I've added a commit with support for `@^environment` syntax.
