### ISSUE TITLE
python bindings: "No match for argument:" when setting installroot

### ISSUE THREAD

**Issue by mkrizek** [rpm-software-management/dnf5#383]
Setting `installroot` via Python API:
```python
import libdnf5

base = libdnf5.base.Base()
conf = base.get_config()
base.load_config_from_file()
conf.installroot = "/installroot"
base.setup()

sack = base.get_repo_sack()
sack.create_repos_from_system_configuration()
sack.update_and_load_enabled_repos(True)

goal = libdnf5.base.Goal(base)
goal.add_install("mc")

transaction = goal.resolve()
if transaction.get_problems():
    for log in transaction.get_resolve_logs_as_strings():
        raise Exception(log)
```

Results in:
```
No match for argument: mc
```

I wonder if it is a regression since I *think* the same program worked before (last week?), was there a change in the API that requires a change in the example above?

**Comment by jan-kolarik** [comment]
Hi Martin, hmm, yeah there were actually some changes around this functionality. This seems like related issue to [this](https://github.com/rpm-software-management/dnf5/issues/248) one or even possibly a duplicate...

**Comment by jan-kolarik** [comment]
I don't know the configuration of your environment, but you may try setting the `conf.use_host_config = True`. But there is still some problem described in the above linked ticket.

**Comment by mkrizek** [comment]
> I don't know the configuration of your environment, but you may try setting the `conf.use_host_config = True`. But there is still some problem described in the above linked ticket.

That appears to fix my issue. Feel free to close this in favor of  the issue linked above, thanks!
