### ISSUE TITLE
enable/disable plugins via API

### ISSUE THREAD

**Issue by mkrizek** [rpm-software-management/dnf5#391]
In DNF4 API the following methods could be used to enable and/or disable a list of plugins:
```python
base.init_plugins(disable_plugin: list, enable_plugin: list)
base.pre_configure_plugins()
```
The intent is to achieve the same behavior as with the following options on the command line:
```
--enableplugin
--disableplugin
```

The ask here is to expose the same functionality via DNF5 API, including the Python bindings.

**Comment by bcl** [comment]
I'd like to have this for lorax's use as well. Currently I'm going to just log a warning that plugins are not supported.
