### ISSUE TITLE
Handle duplicate REPOIDs somehow

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#399]
DNF4 warns like this:

> Repository REPOID is listed more than once in the configuration

And uses just one of them?  Or merges the config?

With DNF5 it seems the `REPOID` is loaded twice as `libdnf::Repo`, per:

```
$ dnf5 repo list
REPOID   Some repo name
REPOID   Some repo name - the duplicate
```

**Comment by j-mracek** [comment]
This issue might create a problem that will be very difficult to discover. The report is related to repofrompath issue - https://github.com/rpm-software-management/dnf5/issues/794

**Comment by praiskup** [comment]
The current solution though isn't ideal - this is how every single DNF5 command ends now for me:

> Failed to create repo "copr:copr.fedorainfracloud.org:project:foo": Id is present more than once in the configuration

The Copr inter-project dependency was designed so that some of those repositories _may_ be defined twice on the system, and that DNF is able to handle that.  Consider that user enables projects `foo` and `baz`, both `foo` and `baz` though depend on `bar`.  This basically leads to duplicated `bar` on the user's system.

**Comment by m-blaha** [comment]
Oh, sorry for breaking it...

**Comment by m-blaha** [comment]
@praiskup I've created PR https://github.com/rpm-software-management/dnf5/pull/814 which will hopfully fix the issue.

**Comment by praiskup** [comment]
Hats off, it's a pleasure to report here. Thank you for such a quick reaction and fix!
