### ISSUE TITLE
In an Upgrade operation, make the display of the previous version to remove optional

### ISSUE THREAD

**Issue by pavelbraginskiy** [rpm-software-management/dnf5#407]
The dnf5 transaction table is awesome, but I really don't like how on upgrade, it takes up double the vertical space of the old transaction table.
Would it be possible to create an option to suppress output of these "replacing" lines with some config setting or flag?
![image](https://user-images.githubusercontent.com/29113974/228308040-bcbdc805-d1df-4f8c-9d56-1c54c7f1017a.png)
Ideally, I would love to see Previous Version be its own column so that the information takes up horizontal rather than vertical terminal space, but I can see how that would be harder.
It's just this one thing keeping me from liking dnf5 over dnf4.

**Comment by j-mracek** [comment]
It will be tricky, because one package coud replace multiple packages

**Comment by pavelbraginskiy** [comment]
A package replacing a previous version of itself and a package replacing one or more *other* packages are completely different cases. I'm only talking about the "replace previous version of self" case.

When it's replacing other packages, that information is more important and I believe is already handled differently by being shown in red.

**Comment by j-mracek** [comment]
This issue is a duplicate with https://github.com/rpm-software-management/dnf5/issues/326

May I ask you to continue with the discussion in the other issue?
