### ISSUE TITLE
Using filter_installed after running the transaction

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#412]
If this isn't clear I can write a reproducer, but I think I've narrowed down my lorax issues. With dnf4 we used to reset the sack after running the transaction by calling:

``` python
self.dbo.reset(repos=False)
self.dbo.fill_sack(load_system_repo=True, load_available_repos=False)
```

This is because lorax needs to query what files were installed with the packages. I tried replacing this with:

``` python
sack = self.dbo.get_repo_sack()
sack.update_and_load_enabled_repos(True)
```

Which leads to problems like queries returning two copies of the pkg object!

So the question is, how do I reset things so that a `query.filter_installed()` will work after running the transaction?

**Comment by jan-kolarik** [comment]
Hi Brian, yes this seems to be a bug/missing feature. I don't know about any way right now to reset the sack objects and calling the `update_and_load_enabled_repos` multiple times results in loading the same packages to the sack again, just using different internal solver ids.

**Comment by jan-kolarik** [comment]
So the situation is like it's basically not possible to reset the sack for now in DNF5. There are several solutions you could try for your use case:
- Use `transaction.get_transaction_packages()`
  - You could filter inbound packages with `libdnf5.base.transaction.transaction_item_action_is_inbound()`
  - On each item from the result, you should be able to do `item.get_package().get_files()` and list the containing files
- Start with a new empty `Base` instance after the transaction and use it for querying
- Use the [`rpm`](https://github.com/rpm-software-management/rpm) API to query information about installed packages on the system

**Comment by bcl** [comment]
It looks like the packages returned by `get_transaction_packages()` don't include all the files. Some of the packages have files listed, others are empty. And the ones with files are incomplete. For example, `tmux` says it only installed one file.

```
inbound package: tmux-3.3a-3.fc39.x86_64
('/usr/bin/tmux',)
```

But running `rpm -ql` on a rawhide system lists these:

```
[root@fedora ~]# rpm -ql tmux
/usr/bin/tmux
/usr/lib/.build-id
/usr/lib/.build-id/e9
/usr/lib/.build-id/e9/f91def390607bfc329961e862bf1135ba2e432
/usr/share/bash-completion/completions/tmux
/usr/share/doc/tmux
/usr/share/doc/tmux/CHANGES
/usr/share/doc/tmux/example_tmux.conf
/usr/share/man/man1/tmux.1.gz
```

And all those files are present in the installroot. Is this a bug? Or is there something else that needs to be done to get the full list?

**Comment by jan-kolarik** [comment]
Oh, you're right. I was looking into the `PackageQuery` using already installed packages and there everything seemed present, but info about packages from the transaction resolution are loaded from the loaded metadata. So if you don't enable optional `filelists` metadata then not all files are listed using this method. Therefore f.e. adding the following line before the `base.setup()` should do the trick:
```python
base.get_config().optional_metadata_types = ['filelists']
```

**Comment by bcl** [comment]
@jan-kolarik  That didn't help :/ Here' my test script:

``` python
import libdnf5
from libdnf5.common import QueryCmp_EQ as EQ
action_is_inbound = libdnf5.base.transaction.transaction_item_action_is_inbound

import tempfile


def get_base(installroot):
    base = libdnf5.base.Base()
    base.load_config_from_file()
    conf = base.get_config()
    conf.zchunk().set(False)
    conf.installroot().set(installroot)
    conf.optional_metadata_types = ['filelists']
    base.setup()

    sack = base.get_repo_sack()
    sack.create_repos_from_system_configuration()
    sack.update_and_load_enabled_repos(False)

    return base


class TemplateRunner(object):
    def __init__(self):
        pass


class AddPkgMixin:
    def add_package(self, name):
        self.goal.add_rpm_install(name)


class LoraxTemplates(TemplateRunner, AddPkgMixin):
    def __init__(self, base):
        self.base = base
        self.goal = libdnf5.base.Goal(self.base)
        self.transaction = None

    def print_pkg_nevra(self, pkg):
        q = libdnf5.rpm.PackageQuery(self.base)
        q.filter_available()
        q.filter_name([pkg], EQ)
        for p in list(q):
            print(p.get_nevra())

    def print_repos(self):
        repo_query = libdnf5.repo.RepoQuery(self.base)
        repo_query.filter_enabled(True)
        print("Enabled repositories:")
        print("\n".join(list(r.get_name() for r in repo_query)))

    def run_transaction(self):
        self.transaction = self.goal.resolve()
        print("Transaction:")
        for tsi in self.transaction.get_transaction_packages():
             print(tsi.get_package().get_nevra())
        self.transaction.download()
        self.transaction.run()

    def filelist(self):
        if self.transaction is None:
            raise RuntimeError("Transaction has not been run yet")

        for tsi in self.transaction.get_transaction_packages():
            if not action_is_inbound(tsi.get_action()):
                continue

            print("inbound package: %s" % tsi.get_package().get_nevra())
            print(tsi.get_package().get_files())


if __name__ == '__main__':
    rootdir = tempfile.mkdtemp(prefix="dnf5-tree")
    print(f"Installing into {rootdir}")
    base = get_base(rootdir)
    tmpl = LoraxTemplates(base)

    print("Adding packages:")
    for pkg in ["tmux", "filesystem", "rsync"]:
        tmpl.print_pkg_nevra(pkg)
        tmpl.add_package(pkg)

    tmpl.print_repos()
    tmpl.run_transaction()

    tmpl.filelist()
```

**Comment by jan-kolarik** [comment]
In my example I used the current upstream API, therefore it should be like this, I think:
```python
conf.optional_metadata_types().set(['filelists'])
```
