### ISSUE TITLE
dnf5 should provide/obsolete dnf and yum

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#416]
- [x] Add dnf obsolete, dnf symlink and dnf provide
  - [x] Add yum obsolete, yum symlink and yum provide
    - [x] requires changes in yum-utils
  - [x] modify DNF protection in DNF package (Fedora 37+) to allow removal during upgrade to Fedora 39

**Comment by evan-goode** [comment]
> Add dnf obsolete, dnf symlink and dnf provide
> Add yum obsolete, yum symlink and yum provide

Addressed in https://github.com/rpm-software-management/dnf5/pull/469

> Modify DNF protection in DNF package (Fedora 37+) to allow removal during upgrade to Fedora 39

Addressed in https://github.com/rpm-software-management/dnf/pull/1924

**Comment by evan-goode** [comment]
>  requires changes in yum-utils

See https://github.com/rpm-software-management/dnf-plugins-core/pull/488

**Comment by mcurlej** [comment]
Can we have a better issue name? Thanks... :)
