### ISSUE TITLE
Move ownership of /etc/dnf/dnf.conf to libdnf5

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#417]
- [x] Remove requirements of dnf-data from multiple components (dnf5, dnf5-daemon, microdnf?)

- [x] Add requirement to libdnf5 to python3-dnf, microdnf, ... because they require /etc/dnf/dnf.conf

- [x] Clean all values in /etc/dnf/dnf.conf and keep only empty main section (distribution overrides has a different location)

**Comment by evan-goode** [comment]
> Remove requirements of dnf-data from multiple components (dnf5, dnf5-daemon, microdnf?)

Removed from `dnf5` and `dnf5daemon-server` in https://github.com/rpm-software-management/dnf5/pull/469. Removed from `microdnf` in https://github.com/rpm-software-management/microdnf/pull/131. 

> Add requirement to libdnf5 to python3-dnf, microdnf, ... because they require /etc/dnf/dnf.conf

Requirement added to `python3-dnf` in https://github.com/rpm-software-management/dnf/pull/1924. Added to `microdnf` in https://github.com/rpm-software-management/microdnf/pull/131.

> Clean all values in /etc/dnf/dnf.conf and keep only empty main section (distribution overrides has a different location)

New /etc/dnf/dnf.conf (now belonging to `libdnf5`) is here: https://github.com/rpm-software-management/dnf5/pull/469

**Comment by jan-kolarik** [comment]
@evan-goode I guess this is done now?
