### ISSUE TITLE
Disallow loading repositories multiple times

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#439]
This is a follow-up to #412 where the issue regarding [`libdnf::repo::RepoSack::update_and_load_enabled_repos()`](https://github.com/rpm-software-management/dnf5/blob/ce88399e3da1fcc6d555fefadc9037628674a325/include/libdnf/repo/repo_sack.hpp#L110) was discovered. When calling this function multiple times then the same packages with different solver ids are loaded into sack, which is undesirable.

**Comment by softwaresale** [comment]
Hi I'm a new contributor and am interested in working on this issue.

In terms of actually fixing this, is it as easy as setting a flag that checks if the method has been called and throwing an assertion exception if it has been called already? This problem seems to be more of a programmer issue instead of an end user issue. Let me know I'm wrong though. Thanks!

**Comment by j-mracek** [comment]
Thank you very much for interest. You are correct it is programmer issue but we opened a door for it. In our API there are multiple ways how to load repositories. The preferable way is to use  void update_and_load_enabled_repos(bool load_system), and other methods should be moved to private section

Move to private in class Repo:
    /// Downloads repository metadata.
    // @replaces libdnf:repo/Repo.hpp:method:Repo.downloadMetadata(const std::string & destdir)
    void download_metadata(const std::string & destdir);

    /// Loads the repository objects into sacks.
    ///
    /// Also writes the libsolv's solv/solvx cache files.
    void load();

    /// Append a rpm database into the system repository. The type of the repo must be Type::SYSTEM.
    // TODO(jrohel) this will add packages with conflicting rpmdb ids, which will break some operations
    void load_extra_system_repo(const std::string & rootdir);

**Comment by jan-kolarik** [comment]
@softwaresale Hello Charlie, please do you still plan to work on this issue?

**Comment by softwaresale** [comment]
Sorry, I didn't see that feedback until just now. I'll work on this issue for sure.

**Comment by jan-kolarik** [comment]
If we would make the only way to load repos the `update_and_load_enabled_repos` method, then user shouldn't use also the `update_and_load_repos` which is accepting `RepoQuery`. But that seems quite limiting from my POV. Maybe we just need to implement per-repo instance logic to store info about data being loaded. Then we should easily determine if to load such repo in the `update_and_load_repos` method which is the only user of the `Repo::load()` right now.
