### ISSUE TITLE
dnf4 and dnf5 do not share groups

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#471]
When a group (e.g. security-tools) is installed via dnf5, it's not supposed to be installed by dnf4 and vice versa (even when the group has  the same ID and there are the same packages in it).

 version: dnf5-5.0.9-1.git.966.354f7b6.el9.x86_64, libdnf5-5.0.9-1.git.966.354f7b6.el9.x86_64
              dnf-4.14.0-5.el9_2.noarch, libdnf-0.69.0-3.el9_2.x86_64

**Comment by j-mracek** [comment]
Thank you very much for the report, but in this case, we cannot fix it. The same issue was for dnf vs. yum-3. In general it is not recommended to use more package managers for one system. I am suggesting to close the issue. @glum23 Is it ok with you or do you suggest any further steps?

**Comment by glum23** [comment]
OK then, feel free to close the issue.
