### ISSUE TITLE
Add offline-upgrade plugin for DNF5.

### ISSUE THREAD

**Issue by Bavuett** [rpm-software-management/dnf5#485]
While using DNF5 during the tests while developing, I loved how fast it is. I'd like to add support for the `offline-upgrade` plugin currently included in DNF4 since it is currently used by lots of people as an alternative to using the GNOME Software app to upgrade their systems by rebooting them.

I'd like to work on the project personally if I have the approval to begin working on it.

**Comment by j-mracek** [comment]
This topic is quite complex - see https://github.com/rpm-software-management/dnf5/issues/258. I propose to close this issue as a duplicate.

**Comment by Bavuett** [comment]
Alright. I'll take a look at the issue. Thanks.
