### ISSUE TITLE
DNF versionlock Plugin

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#489]
The version lock plugin used excludes and description of what should be excluded was stored as glob.

Problems with DNF4:

- it was a dnf plugin therefore microdnf did not honor locked packages
  - Proposing to have it as a core libdnf5 functionality of core plugin
- Difficult to say lock `dnf < 4.5`
- Using globs is extremely costly

We could also investigate to use SOLVER_LOCK for the functionality
- depends whether we want to hide locked packages for repoquery|list|... or not

**Comment by jan-kolarik** [comment]
I am closing this in favor of https://github.com/rpm-software-management/dnf5/issues/332.
