### ISSUE TITLE
dnf5-plugins should admit-at-RPM-level what commands are provided

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#493]
It was a very convenient feature in DNF4:

$ dnf builddep
No such command: builddep. Please use /usr/bin/dnf --help
It could be a DNF plugin command, try: "dnf install 'dnf-command(builddep)'"

The `try: "dnf install ..."` hint was **very helpful**, often C&Ped.

We should have the command-related Provides: in DNF5 too, and add back the useful warning:

```
$ rpm -q --provides dnf-plugins-core | grep command
dnf-command(builddep)
dnf-command(changelog)
dnf-command(config-manager)
dnf-command(copr)
dnf-command(debug-dump)
...
```

**Comment by j-mracek** [comment]
I agree, it was cool feature for the modular software.

**Comment by ppisar** [comment]
There is a more alive, duplicate issue #566.

**Comment by evan-goode** [comment]
Resolved by https://github.com/rpm-software-management/dnf5/pull/718
