### ISSUE TITLE
dnf download `--url`

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#497]
Additional resources:

DNF4 implementation - https://github.com/rpm-software-management/dnf-plugins-core/blob/master/plugins/download.py (between lines 112 and 125)

Requirements:
Each package will be represented only by one url

Problems or recommendations:
RPM location could contain the whole url (then don't merge it with url of mirror)
Skip mirrors with unsupported protocols by Curl (rsync).
Metalinks and mirrorlists should be taken as primary source for urls - DNF5 use that approach also.

**Comment by Bavuett** [comment]
Hi, @j-mracek. I've worked on the issue but I'm encountering some difficulties. After reading the code in the [`download.cpp`](https://github.com/rpm-software-management/dnf5/blob/main/dnf5/commands/download/download.cpp) file I figured out that I needed to print a combination of the values returned by the `get_baseurl()` and the `get_location()` functions. However, I've noticed that with the packages I tried (`code` and `python`) the base location is not included in their `repomd.xml` file which, as I understood from the code base, the function uses to get the URL.

As a draft, I'm currently printing the repo's mirrors along with the location that `get_location()` returns. This does the job with packages such as `python` which specify different mirrors for their repos and the URLs are correct too, but this doesn't work with other packages such as `code`.

Am I missing something? What should I change in [my code](https://github.com/Bavuett/dnf5/commit/0fe50a8c576f6ca796626ed0766cd938b4e26090)?

**Comment by j-mracek** [comment]
I updated the issue description with some additional information. Please ping me, if I forget to describe something.

I checked your code and I think it will generate all possible urls for each package. Usually users use the feature to download packages using a different downloaded, therefore they need only one url per package. If there will be more urls per package they will have a difficulty to known what is an alternative and what is a different package.

**Comment by kontura** [comment]
@Bavuett are you still working on this?
The same functionality (`pkg->get_remote_location()`) is also needed for `repoquery --location` (https://github.com/rpm-software-management/dnf5/issues/589) so I was wondering what is the status.

**Comment by kontura** [comment]
PR: https://github.com/rpm-software-management/dnf5/pull/664 add `get_remote_locations(...)` to `libdnf5::rpm::package`, this should be useful for this.

**Comment by derickdiaz** [comment]
In dnf4, I'm I correct to believe it is only returning the first url that matches the schema supplied? I've attached the link where the code lives. 

https://github.com/rpm-software-management/dnf/blob/1c43d0999178d492381ad0b43917ffd9c74016f8/dnf/repo.py#L636

I was able to call the remote_locations function on the pkg, however that function returns multiple urls.

**Comment by kontura** [comment]
> In dnf4, I'm I correct to believe it is only returning the first url that matches the schema supplied? I've attached the link where the code lives.
> 
> https://github.com/rpm-software-management/dnf/blob/1c43d0999178d492381ad0b43917ffd9c74016f8/dnf/repo.py#L636
> 
> I was able to call the remote_locations function on the pkg, however that function returns multiple urls.

Yes, I think you can just use the first one from the vector. It is what dnf4 does.

**Comment by derickdiaz** [comment]
I was having trouble implementing the url-protocols option. I believe this needs to be a set containing the values {"http", "https", "ftp" , "file"} such as the const defined for the remote locations function:

<img width="1011" alt="image" src="https://github.com/rpm-software-management/dnf5/assets/44981122/c7b83e3d-e4d3-4771-8c6a-2337a467982b">

I didn't know how to use the option_string_list as an argument. Are there any example of this being used? My lack of c++ skills might get the best of me but I can try.

**Comment by kontura** [comment]
`OptionStringList` is used for example for [`--disable-repo=REPO_ID,...`  ](https://github.com/rpm-software-management/dnf5/blob/main/dnf5/main.cpp#L361-L377). 
You might want to use `OptionStringSet`, however I think that is only used for config options not as an argument.
