### ISSUE TITLE
Decide on the format of machine readable outputs

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#512]
We should select and consistently use one output format. The obvious options are

- json (copr plugin needs json parsing)
- toml (already used by system state)
- yaml
- xml (used in comps group's `serialize` method, but the parsing itself is done by libsolv for us, so no external library used)
- something different?

Here is a (incomplete) list of dnf5 commands that would profit from machine readable outputs

- repoquery
- list
- info
- repoclosure
- updateinfo

**Comment by praiskup** [comment]
Other option is YAML.  I prefer using it for most use-cases nowadays (for good human-readability, too).

**Comment by praiskup** [comment]
> json (copr plugin needs json parsing)

Also [libdnf/transaction/Transformer.cpp](https://github.com/rpm-software-management/dnf5/blob/92624a6830ab764983068f5e6c1a495162b70702/libdnf/transaction/Transformer.cpp#L459).

**Comment by praiskup** [comment]
The Copr plugin would benefit from (opt-in) machine-readable output as well.

**Comment by evan-goode** [comment]
My vote would be for JSON, it is very simple and probably the most popular choice for this type of use case. It's plenty human-readable if pretty-printed. There's `jq` for parsing it in shell scripts.

TOML is nice for configuration, but it's not good IMO for arbitrarily-structured data with potentially many layers of nesting.

I have no strong opinion on YAML, I think that would be fine too.

**Comment by j-mracek** [comment]
If smartcols has an option to export to json I would prefer json.

**Comment by inknos** [comment]
> If smartcols has an option to export to json I would prefer json.
it does
https://cdn.kernel.org/pub/linux/utils/util-linux/v2.31/libsmartcols-docs/libsmartcols-Table.html#scols-table-enable-json

**Comment by evan-goode** [comment]
Have we decided on JSON? Or maybe this is worth a post to fedora-devel to gather some more input?

**Comment by jan-kolarik** [comment]
I think we "sort of" decided the JSON is the winner. Also, if we want to use `libsmartcols` for generating the output, it seems this is the only supported format there after I did some brief browsing through the docs...

**Comment by jan-kolarik** [comment]
Agreed on `json`, using `--json` parameter to produce machine-readable output from dnf commands.
