### ISSUE TITLE
'dnf5 downgrade' exits with 0 and non-empty stderr when its argument is non-existent or not installed

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#524]
When dnf5 downgrade's argument package does not exist or it is not installed, dnf5 exit code is 0, however, it provides a non-empty stderr message (dnf4 exits with 1).

See also comments in https://github.com/rpm-software-management/dnf5/issues/137 and https://github.com/rpm-software-management/ci-dnf-stack/pull/1264

**Comment by kontura** [comment]
This problem exists also in other commands: https://github.com/rpm-software-management/dnf5/issues/527

**Comment by kontura** [comment]
This issue should be resolved by: https://github.com/rpm-software-management/dnf5/pull/532
