### ISSUE TITLE
All commands should respect `--skip-unavailable` option

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#527]
When running a command with a missing package the return code is 0 regardless of `--skip-unavailable` option.
It currently works only for `install` command.

However all other commands: `downgrade`/`upgrade`/`remove`/.... don't work correctly.

**Comment by frenzymadness** [comment]
I have exactly the same problem. I'd like to upgrade packages on my system and some of them are missing from repositories (giving me HTTP/404).

The results from dnf 4 and 5 are identical:
```
dnf5 upgrade
…
>>> Not finished - interrupted by error: Cannot download f/ffmpeg-libs-6.0-10.fc38.x86_64.rpm:
----------------------------------------------------------------------------------------------
[31/94] Total                      0% [                  ] | 138.3 KiB/s |  14.1 KiB | -06m53sFailed to download packages

---

dnf4 upgrade
…
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: Error downloading packages:
  ffmpeg-6.0-10.fc38.x86_64: Cannot download, all mirrors were already tried without success
```

I'd expect `dnf5 upgrade --skip-unavailable` to fix the problem for me but it makes no difference while `dnf4 upgrade --skip-broken` is able to update all the available packages.

**Comment by j-mracek** [comment]
I've created additional PR to improve behavior - https://github.com/rpm-software-management/dnf5/pull/532.

But I believe that remove command behaves correctly.

**Comment by j-mracek** [comment]
> I have exactly the same problem. I'd like to upgrade packages on my system and some of them are missing from repositories (giving me HTTP/404).
> 
> The results from dnf 4 and 5 are identical:
> 
> ```
> dnf5 upgrade
> …
> >>> Not finished - interrupted by error: Cannot download f/ffmpeg-libs-6.0-10.fc38.x86_64.rpm:
> ----------------------------------------------------------------------------------------------
> [31/94] Total                      0% [                  ] | 138.3 KiB/s |  14.1 KiB | -06m53sFailed to download packages
> 
> ---
> 
> dnf4 upgrade
> …
> The downloaded packages were saved in cache until the next successful transaction.
> You can remove cached packages by executing 'dnf clean packages'.
> Error: Error downloading packages:
>   ffmpeg-6.0-10.fc38.x86_64: Cannot download, all mirrors were already tried without success
> ```
> 
> I'd expect `dnf5 upgrade --skip-unavailable` to fix the problem for me but it makes no difference while `dnf4 upgrade --skip-broken` is able to update all the available packages.

I think that this is not related. If package cannot be downloaded I recommend to exclude the package before transaction (dnf5 upgrade -x=ffmpeg), or clean cache before run (dnf5 clean all) to ensure that you don't have outdated metadata.

**Comment by frenzymadness** [comment]
After reading the manual page, I agree that `--skip-broken` and `--skip-unavailable` are different and the difference makes sense. I thought that the latter is just a new name for the former.

But for me, it seems that a repository returning HTTP/404 for a package means that the package is not available. I honestly don't understand what is the `--skip-unavailable` useful for.

**Comment by j-mracek** [comment]
> After reading the manual page, I agree that `--skip-broken` and `--skip-unavailable` are different and the difference makes sense. I thought that the latter is just a new name for the former.
> 
> But for me, it seems that a repository returning HTTP/404 for a package means that the package is not available. I honestly don't understand what is the `--skip-unavailable` useful for.

There are two layers in dnf - data in repository metadata and RPMs. Data in repository are used to resolve transaction and when we have a solution for user request (transaction) then DNF downloads RPMs.

`--skip-unavailable` is used to skip argument that does not have package described in metadata.

`dnf install not-here` will fail but `dnf install not-here --skip-unavailable` will skip argument because `not-here` is not in any repository.

What happen to you 
You requested upgrade (`dnf upgrade`), dnf5 created transaction and you approved it. After this step it is impossible to modify what you request and DNF fails when something goes wrong. DNF download packages and if any package is not possible to download then DNF fails. We cannot skip such a package 
and continue because it could lead into broken system.

**Comment by j-mracek** [comment]
I tested upgrade, downgrade with unknown argument and it returns 1 therefore I consider the issue as resolved.
