### ISSUE TITLE
countme=1 causes metadata download failure 

### ISSUE THREAD

**Issue by DaanDeMeyer** [rpm-software-management/dnf5#531]
If I have `countme=1` in a repo definition, I get the following error when trying to run dnf:

```
>>> Librepo error: Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were triedFailed to download metadata (metalink: "https://mirrors.centos.org/metalink?repo=centos-baseos-9-stream&arch=x86_64") for repository "baseos"
```

The full repository definition is:

```
[baseos]
name=CentOS Stream $releasever - BaseOS
metalink=https://mirrors.centos.org/metalink?repo=centos-baseos-$releasever-stream&arch=$basearch
gpgkey=file:///usr/share/distribution-gpg-keys/centos/RPM-GPG-KEY-CentOS-Official
gpgcheck=1
repo_gpgcheck=0
countme=1
enabled=1
```

Removing `countme=1` fixes the error.

**Comment by kontura** [comment]
Are you sure this is `countme` related?

I have tested it and it works with and without `countme` for me.

Also the fedora repos use `countme` by default and those work fine.

**Comment by DaanDeMeyer** [comment]
With the above repo, if I remove `countme=1`, it works, if I add it back, I get the error I mentioned.

I'm happy to debug further but I can't seem to find any debugging options? The error I get is extremely generic and doesn't really tell what specifically is going wrong.

**Comment by kontura** [comment]
You could check the log files in `/var/log/dnf5.log`.

Can you provide a reproducer?

**Comment by DaanDeMeyer** [comment]
It seems I have to set `persistdir=` which is used when the countme= setting is enabled.
