### ISSUE TITLE
--setopt with an unknown option ends up with core dumped

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#534]
When an unknown option is passed to  --setopt, dnf5 ends up with core dumped, e.g.
~~~
# dnf5 install --setopt=unknown=whatever bash
terminate called after throwing an instance of 'std::runtime_error'
  what():  setopt: "unknown=whatever": Option "unknown" not found
Aborted (core dumped)
~~~
version: dnf5-5.0.10-20230516005440.11.g9c125fd5.fc38

**Comment by j-mracek** [comment]
I create a patch (https://github.com/rpm-software-management/dnf5/pull/536) to resolve the issue. I would like to have test for it, but I am not whether the test already exists. Do you know whether there is a CI test?

Additionally it resolves `--setvars=hjsdjfhjhds`
