### ISSUE TITLE
DNF5 builds are failing on fedora for non x86_64 arch

### ISSUE THREAD

**Issue by inknos** [rpm-software-management/dnf5#543]
- f38 https://koji.fedoraproject.org/koji/taskinfo?taskID=101288171
- rawhide https://koji.fedoraproject.org/koji/taskinfo?taskID=101288351

**Comment by kontura** [comment]
This should be resolved by: https://github.com/rpm-software-management/dnf5/pull/539

**Comment by jan-kolarik** [comment]
Yep, today's [results](https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-unstable/package/dnf5/) are looking good.

**Comment by inknos** [comment]
nice, I'll do another release with the fixes, thank you.
