### ISSUE TITLE
Add hints when transaction fails for DNF5 outputs

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#548]
In DNF4 there is a hint which option could be used to resolve the situation:

```
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
```

In DNF5 we have a new option `--skip-unavailable`.

The hint is dynamically generated because we should not suggest option that are not relevant for the current situation.

It would be good to suggest or document to not use all option at the same time. When user use `--allow-erasing` with `--skip-broken` and `best` then the valid solution range is from do nothing (sucess) to erase the whole system, or do nothing with error.

**Comment by evan-goode** [comment]
The hint would be great to have in DNF 5. A couple participants in the 2023-08-11 test week ran into "conflicting requests" errors where `--allowerasing` would have helped.

**Comment by jan-kolarik** [comment]
Another fresh request for displaying the `--allowerasing` hint for Fedora: https://bugzilla.redhat.com/show_bug.cgi?id=2250559.

**Comment by damaestro** [comment]
I was glad to see the option was available, but for new users this would just look like a broken transaction.
