### ISSUE TITLE
Support for `dnf5 repoquery --repofrompath ID,baseurl` 

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#549]
I typically diagnosed repository issues using this command before, and I miss the option since I switched to DNF5.
Is there an alternative way to query other repositories without touching the system DNF configuration?

**Comment by praiskup** [comment]
This is also [needed by prunerepo](https://pagure.io/prunerepo/issue/18).

**Comment by j-mracek** [comment]
The issue is related to https://github.com/rpm-software-management/dnf5/issues/306. If there will be a factory method then the issue 306 will be resolved.

**Comment by thrix** [comment]
This is needed for Fedora CI, which uses this to get all rpms to install from a repository

**Comment by mcurlej** [comment]
Also we have additional issue which is related to this. 

Closes #168

**Comment by thrix** [comment]
Thanks, @m-blaha @jan-kolarik when will this get to Rawhide pls?

**Comment by jan-kolarik** [comment]
@thrix Hello, probably in about like 2-3 weeks. Most of the team is OOO till that. I will link here @inknos as a reminder.

**Comment by pkratoch** [comment]
Hi @thrix, actually, I'll be doing the release instead of @inknos this time, and you can expect it sometime next week (I'm guessing Tuesday).

**Comment by pkratoch** [comment]
Change of plans, I was told the release is more urgent, so I plan to do it tomorrow.

**Comment by LecrisUT** [comment]
Thank you very much for the consideration

**Comment by pkratoch** [comment]
Bodhi update: https://bodhi.fedoraproject.org/updates/FEDORA-2023-3f321278b5

**Comment by LecrisUT** [comment]
The update is being blocked by a failure in `dnf update`
