### ISSUE TITLE
Replace dnf-automatic functionality by DNF5

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#57]
dnf-automatic provides essential functionality for the automatic system administration. DNF5 must also provides such a functionality to allow DNF replacement in Fedora 39.

**Comment by rathann** [comment]
Please include https://github.com/rpm-software-management/dnf/issues/1954 when implementing the replacement. Information about pending updates on a system is valuable intel for an attacker and should not be sent over unencrypted SMTP connection.
