### ISSUE TITLE
dnf5daemon-server install packages without checking gpg key

### ISSUE THREAD

**Issue by timlau** [rpm-software-management/dnf5#574]
While implementing dnf5daemon support for  https://github.com/timlau/yumex-ng i found out the the **repo_key_import_request** signal is not sent when a key need to be imported, it just install the package with out any issues.

### Enable a new copr repo

sudo dnf copr enable timlau/rasmil -y

### Test with dnf5 cli

**This work as expected, dnf5 ask for key import**

```
sudo dnf5 install python3-rasmil
Updating and loading repositories:
Repositories loaded.
Package                       Arch   Version                       Repository                   Size
Installing:                                                                                         
 python3-rasmil               noarch 1.0.2-2.fc38                  copr:copr.fedorainfracl  76.5 KiB
Installing dependencies:                                                                            
 libxfce4util                 x86_64 4.18.1-2.fc38                 fedora                  889.9 KiB
 xfconf                       x86_64 4.18.1-1.fc38                 updates                 832.6 KiB

Transaction Summary:
 Installing:        3 packages

Total size of inbound packages is 440 KiB. Need to download 0 B.
After this operation 2 MiB will be used (install 2 MiB, remove 0 B).
Is this ok [y/N]: y
[1/3] python3-rasmil-0:1.0.2-2.fc38.noarch                  100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded
[2/3] xfconf-0:4.18.1-1.fc38.x86_64                         100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded
[3/3] libxfce4util-0:4.18.1-2.fc38.x86_64                   100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded
----------------------------------------------------------------------------------------------------
[3/3] Total                                                 100% |   0.0   B/s |   0.0   B |  00m00s
[1/4] https://download.copr.fedorainfracloud.org/results/ti 100% |   1.7 KiB/s | 994.0   B |  00m01s
----------------------------------------------------------------------------------------------------
[4/4] Total                                                 100% |   0.0   B/s |   0.0   B |  00m00sImporting PGP key 0xD3337195
 UserId     : "timlau_rasmil (None) <timlau#rasmil@copr.fedorahosted.org>"
 Fingerprint: B2C5988089B26F72266DF052B12760C9D3337195
 From       : https://download.copr.fedorainfracloud.org/results/timlau/rasmil/pubkey.gpg
Is this ok [y/N]: n
PGP check for package "python3-rasmil-1.0.2-2.fc38.noarch" (/var/cache/libdnf5/copr:copr.fedorainfracloud.org:timlau:rasmil-3cd2f7420b9fe0da/packages/python3-rasmil-1.0.2-2.fc38.noarch.rpm) from repo "copr:copr.fedorainfracloud.org:timlau:rasmil" has failed: Canceled by the user.
Signature verification failed


```

### Test with dnf5daemon-client

** package is installed without asking for key import and the key is not installed **

```
rpm -q gpg-pubkey --qf '%{NAME}-%{VERSION}-%{RELEASE}\t%{SUMMARY}\n'
gpg-pubkey-eb10b464-6202d9c6	Fedora (38) <fedora-38-primary@fedoraproject.org> public key
gpg-pubkey-47511840-63a1d2f8	timlau_yumex-ng (None) <timlau#yumex-ng@copr.fedorahosted.org> public key
gpg-pubkey-90f437f2-5dd896bd	atim_starship (None) <atim#starship@copr.fedorahosted.org> public key
gpg-pubkey-d651ff2e-5dadbbc1	RPM Fusion free repository for Fedora (2020) <rpmfusion-buildsys@lists.rpmfusion.org> public key
gpg-pubkey-94843c65-5dadbc64	RPM Fusion nonfree repository for Fedora (2020) <rpmfusion-buildsys@lists.rpmfusion.org> public key
gpg-pubkey-be1229cf-5631588c	Microsoft (Release signing) <gpgsecurity@microsoft.com> public key

```

```
sudo dnf5daemon-client install python3-rasmil
Package                       Arch   Version                       Repository                   Size
Installing:                                                                                         
 python3-rasmil               noarch 1.0.2-2.fc38                  copr:copr.fedorainfracl  76.5 KiB
Installing dependencies:                                                                            
 libxfce4util                 x86_64 4.18.1-2.fc38                 fedora                  889.9 KiB
 xfconf                       x86_64 4.18.1-1.fc38                 updates                 832.6 KiB

Transaction Summary:
 Installing:        3 packages

Is this ok [y/N]: y
[1/3] python3-rasmil-0:1.0.2-2.fc38.noarch                  100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded
[2/3] xfconf-0:4.18.1-1.fc38.x86_64                         100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded
[3/3] libxfce4util-0:4.18.1-2.fc38.x86_64                   100% |   0.0   B/s |   0.0   B |  00m00s
>>> Already downloaded
----------------------------------------------------------------------------------------------------
[3/3] Total                                                 100% |   0.0   B/s |   0.0   B |  00m00s[1/2] Verify package files                                  100% | 500.0   B/s |   3.0   B |  00m00s
[2/3] Prepare transaction                                   100% |   9.0   B/s |   3.0   B |  00m00s
[3/4] Installing libxfce4util-0:4.18.1-2.fc38.x86_64        100% |   9.3 MiB/s | 903.1 KiB |  00m00s
[4/5] Installing xfconf-0:4.18.1-1.fc38.x86_64              100% |  10.2 MiB/s | 845.5 KiB |  00m00s
[5/5] Installing python3-rasmil-0:1.0. 100% [==================] |   4.4 MiB/s |  80.8 KiB | -00m00s
>>> Running scriptlet: glibc-common-0:2.37-4.fc38.x86_64
>>> Stop scriptlet: glibc-common-0:2.37-4.fc38.x86_64
----------------------------------------------------------------------------------------------------
[4/5] Total                            100% [==================] |   1.0 KiB/s |   1.8 MiB | -00m00s
~ took 4s 

```

**Comment by pmatilai** [comment]
Not wanting to side-track the autoverify PR so commenting here instead: are you guys aware that rpm itself will automatically perform enforcing signature checking as a part of all transactions (including test-ones), if the verify level (set by rpmtsSetVfyLevel() or configuration) includes RPMSIG_SIGNATURE_TYPE?

So in theory you could throw out all the PGP checking code and just tell rpm to do it, and then process the returned rpm problem objects (if any) for results, including any missing keys which you could then import and retry.

That rpm machinery was developed precisely to guarantee that verification of the package set is always performed whether the API user is aware of it or not, eg exactly this kind of case. The caveat being that rpm only defaults to verifying digests instead of signatures, because decades of legacy that would break otherwise (sigh).

Mind you, there might be some gaps in that functionality wrt what something like dnf may want, but I guess we'd only really find those by attempting to use it.

**Comment by m-blaha** [comment]
Thanks - I'll check whether the `rpmtsSetVfyLevel` is set correctly, which is probably not given that the invalid package was installed.

But we still need/want to do our own PGP checking for (at least) these reasons:

- `--downloadonly` use-case - packages are downloaded, but the rpm transaction is not executed
- the handling of the key import to rpmdb is more straightforward if the step is executed separately (although as you said this can be handled by checking rpm transaction results and retry if needed)
- we need to prevent installation of unsigned rpm from repository that has `gpgcheck=1` set

Also the PGP checking/import is done exclusively using rpm API calls, we do not maintain our own implementation.

**Comment by pmatilai** [comment]
Right, --downloadonly is a different. Of course you could feed that too to a test-transaction but that seems kinda silly too.

As for preventing installation of unsigned rpms, that's exactly what RPMSIG_SIGNATURE_TYPE vfylevel will achieve, on rpm level. I think dnf has intentionally not overridden that from whatever is configured on rpm level, but it can do so.

I know dnf uses the rpm API for the verification, it's just that the available APIs (with the exception of the transaction verify step perhaps) are pretty terrible. Anyway, there was more than meets the eye (eg --downloadonly), I'll shut up now :smile:

**Comment by m-blaha** [comment]
But we need to do it (prevention installation of unsigned rpms) depending on the repo the package comes from (more precisely on repo.gpgcheck attribute). And I think rpm does not know anything about repos so it cannot selectively switch vfylevel for particular packages.

**Comment by pmatilai** [comment]
Yes, the rpm vfylevel is at odds with per-repo gpgcheck setting as it's a big hammer and applies to absolutely everything, on purpose so that nobody can accidentally forget it. It could use some per-package override mechanism, it just needs to leave a trail of evidence.
