### ISSUE TITLE
Clarify dnf5 verisoning scheme

### ISSUE THREAD

**Issue by gotmax23** [rpm-software-management/dnf5#579]
Can you please spell out dnf5's versioning scheme somewhere? dnf5 is currently at 5.0.13, but there's multiple breaking (API) changes in almost every release since 5.0.0. It makes it hard to utilize libdnf5 as a library when there's no policy about versioning or breaking changes in minor releases. I'm not sure why 5.0.0 was released with an unstable public API, but in any case, these type of breaking updates should not be pushed to stable Fedora releases.

**Comment by j-mracek** [comment]
Thank you very much for the report. The current state is temporal and we have to move to stable side. API was often modify upon request from teams that have been adopting DNF5.

- Changes of API allowed until end of the June 2023
- The first stable version - 5.1.x
- After 5.1 - use the same versioning principle like in DNF
  - New feature - increase minor version
  - Bug fixes - increase the last number
  - No API changes in stable Fedoras
    - Keeping old API and mark it as deprecated
    - Removal of deprecated API - only in rawhide
