### ISSUE TITLE
dnf download lacks --disableexcludes=all option

### ISSUE THREAD

**Issue by rwmjones** [rpm-software-management/dnf5#581]
supermin uses `dnf download ... --disableexcludes=all` which is missing in dnf5:

https://github.com/libguestfs/supermin/blob/3efe663421d94376694f292ca1fcf2732a82149f/src/ph_rpm.ml#L488

**Comment by rwmjones** [comment]
This is being done by an automated process so editing a config file is not practical.  Can it be done from the command line at all?

**Comment by jan-kolarik** [comment]
Yes, you can do `dnf5 download ... --setopt=disable_excludes=*`.

**Comment by rwmjones** [comment]
Changed here: https://github.com/libguestfs/supermin/commit/2f3eae350aa89b8067201a8bb24ff830d0fd919c
