### ISSUE TITLE
The behavior of dnf5 is a bit inconsistent for `downgrade`

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#582]
The behavior of dnf5 is a bit inconsistent. When there's no downgrade of a package available, it reports on stderr  `Package <whatever> of lowest version already installed, cannot downgrade it.` (BTW, it should be "the lowest version")
When there's no upgrade of a package available, dnf5 does not report anything on stderr.

_Originally posted by @glum23 in https://github.com/rpm-software-management/dnf5/issues/532#issuecomment-1568376511_

**Comment by jrohel** [comment]
From my point of view better is "The lowest **available** version of the <whatever> package is already installed, cannot downgrade it." . But still, this report is inconsistent with the upgrade, which is silent.

**Comment by m-blaha** [comment]
Hmm, the question is whether we want to make the upgrade/downgrade commands consistent regarding this message.

The `downgrade` operation is somewhat exceptional, and the user performs it with a specific intent. I think it's good to print a 'warning' indicating that dnf was unable to find any lower available version of the package.

On the other hand, the `upgrade` is a routine system maintenance operation that users run periodically, and I'm not sure if adding the message 'The latest version of the package is already installed...' brings any additional value, especially when the upgrade is run without specifying a package. Simply stating 'Nothing to do' should be sufficient in this situation.

**Comment by glum23** [comment]
@m-blaha, that's a valid point, it's not possible to call 'dnf5 downgrade' while 'dnf5 upgrade' is quite common. However, it'd be nice to adjust the message provided to stderr, I like Jarek's suggestion.

**Comment by j-mracek** [comment]
Thank you very much for opinion, I agree you. Proposing - improve message according to @jrohel suggestion. I also support an idea of not adding any message for upgrade because it could result in too many massages when upgradeing the whole system or in a different behavior for `dnf5 upgrade` and `dnf5 upgrade '*'`

**Comment by glum23** [comment]
PR: https://github.com/rpm-software-management/dnf5/pull/656
Also upstream tests dnf/downgrade.feature and dnf/shell-downgrade.feature has to be updated accordingly, PR with updates will be created soon.

**Comment by glum23** [comment]
has been resolved via https://github.com/rpm-software-management/dnf5/pull/656
