### ISSUE TITLE
Please add a documentation how to write plugins

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/dnf5#59]
Hello,
can you please write some documentation about how to implement custom plugins? I think it will be a very important piece of information since there are 23 plugins in `dnf-plugins-core`, 7 plugins in `dnf-plugins-extra`, and howmany more unpublished on user machines.

Please keep in mind that all of the existing plugins are written in python which is vastly distant from C++, so the developers re-implementing the plugins for DNF5 will be most likely very inexperienced with the new language, build system, etc.

Personally, I would search for this plugin documentation here
https://libdnf.readthedocs.io/en/dnf-5-devel/contributing/index.html

**Comment by praiskup** [comment]
Related https://github.com/rpm-software-management/dnf5/pull/39

**Comment by j-mracek** [comment]
Because PR with template plugin was merged I consider the issue as resolved
