### ISSUE TITLE
dnf5 repoquery appears to be missing -l/--list files options

### ISSUE THREAD

**Issue by opoplawski** [rpm-software-management/dnf5#592]
dnf5 repoquery appears to be missing -l/--list files options that dnf has.  I can't find an equivalent.

**Comment by kontura** [comment]
Hello, the option `--files` was added recently that works the same way.
It should be part of 5.0.12 release.

For future reference we have: https://dnf5.readthedocs.io/en/latest/changes.html which should list all dnf -> dnf5 changes.

**Comment by opoplawski** [comment]
Thanks for the addition, sorry for the noise.
