### ISSUE TITLE
`dnf5 info` mangles non-Latin characters in the Description field

### ISSUE THREAD

**Issue by lnicola** [rpm-software-management/dnf5#593]
![image](https://github.com/rpm-software-management/dnf5/assets/308347/6f685e7d-3921-4e9d-b76a-14809ee0be15)

See the smart quotes on the last lines; also, the coloring is a bit different. I have `LANG=en_GB.UTF-8`.

**Comment by lnicola** [comment]
Update: this works now with UTF-8 locales:

![image](https://github.com/user-attachments/assets/735d13e7-9871-401f-8cd9-a26dac229bc2)

It still shows hex-encoded UTF-8 with `LANG=C`, while dnf 4 just passes them through. I think they'd normally be replaced with `?`.

Anyway, feel free to close if you want.

**Comment by ppisar** [comment]
Thanks for the testing.

The hex-escaping in `C` locale is correct because `C` means US-ASCII.

**Comment by lnicola** [comment]
> The hex-escaping in C locale is correct because C means US-ASCII.

But Python (and probably others) does:

```python
>>> '“half”'.encode('ascii', errors='replace')
b'?half?'
```

**Comment by ppisar** [comment]
Different libraries handle inconvertible characters differently. There is no single correct method.
