### ISSUE TITLE
Modify fedora comps group

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#597]
It is critical to ensure that Fedora 39 deployments will use dnf5 and dnf5 plugins. We need to modify kickstar and comps group.
The definition of fedora kickstar is here - https://pagure.io/fedora-kickstarts.git
Information about comps group - https://fedoraproject.org/wiki/How_to_use_and_edit_comps.xml_for_package_groups
Comps group repository - https://pagure.io/fedora-comps

- [x] Replace microdnf by dnf5
- [x] Replace dnf by dnf5
- [x] Replace dnf-plugins-core by package that provides dnf5 plugins (including `builddep` command)

**Comment by praiskup** [comment]
As discussed in the off-tracker discussion;  we should provide a statement or policy somewhere
assuring the Fedora folks that `dnf5-plugins` will bring necessary dependencies into the minimal
installs (it is the case now, I was amazed to find the fact, but it would be nice to keep it that way).

**Comment by evan-goode** [comment]
Draft PR to fedora-kickstarts: https://pagure.io/fedora-kickstarts/pull-request/967

**Comment by j-mracek** [comment]
> Draft PR to fedora-kickstarts: https://pagure.io/fedora-kickstarts/pull-request/967

LGTM

**Comment by evan-goode** [comment]
PR to fedora-comps: https://pagure.io/fedora-comps/pull-request/852

**Comment by evan-goode** [comment]
Both PRs have been merged, closing.
