### ISSUE TITLE
Is get_base_arch available in python?

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#600]
I need to be able to map the arch back to basearch. Currently I'm using code I borrowed from dnf.rpm, but I see that `libdnf/conf/vars.cpp` has a `get_base_arch` function. But I don't see it available anywhere in the Python API. If it isn't available, could it be added?

**Comment by j-mracek** [comment]
Thank you very much for your report. @bcl May I ask you for additional information for which component and for which purpose you need the method. I am asking because there is a project that can provide such a mapping and we are looking for customers (DNF5 would be a customer).

**Comment by bcl** [comment]
In https://github.com/osbuild/osbuild-composer/pull/3332/files#diff-cc316e51a644ae96748aa77302da8fa1d0e24bd9afa43163b3cd53b43eaaa7beR28 I am using it to setup the basearch substitution for `dnf5-json` in osbuild-composer.

And in lorax (this is an older PR, needs updating for latest dnf5 changes) - https://github.com/weldr/lorax/pull/1319/files#diff-6252bbe9a917d5070d076793ce4bf11888c3a7720c4ceaca07b0a9079fa00a90R71 I am using it to setup basearch for the package install.

I'm fine with using a library as long as it's well maintained. But I'd prefer to just depend on libdnf5 if it is possible.
