### ISSUE TITLE
Please add `--downloaddir` option to `dnf5 update --downloadonly` option

### ISSUE THREAD

**Issue by mark-hyde** [rpm-software-management/dnf5#603]
In DNF we can currently do this:

`dnf-3 update --downloaddir=/var/cache/auter/default --downloadonly`

But the `--downloaddir` option doesn't currently work in dnf5.

Could you please implement this?
 (Alternatively the --destdir from the `download` option for consistency would be OK too)

**Comment by j-mracek** [comment]
There is a `create_destdir_option(dnf5::Command & command)` that add option to a command

**Comment by jan-kolarik** [comment]
In case you already want to redirect the downloads into a specified folder, you can use the `setopt` option as a workaround:
```
dnf5 upgrade --downloadonly --setopt=destdir="/folder/you/want"
```

**Comment by mark-hyde** [comment]
Thanks - I'll try that workaround

**Comment by derickdiaz** [comment]
I will like to take this issue on!

**Comment by j-mracek** [comment]
@derickdiaz We will be happy to help or make a review

**Comment by derickdiaz** [comment]
@j-mracek PR has been created. Sorry for the delay: https://github.com/rpm-software-management/dnf5/pull/1103
