### ISSUE TITLE
dnf5 history {undo|rollback} errors

### ISSUE THREAD

**Issue by mark-hyde** [rpm-software-management/dnf5#604]
In DNF we can do:
  `dnf-3 history undo 4`
  OR
  `dnf-3 history rollback 4`
But in dnf5 we get an error:
`# dnf5 history rollback 4`
Unknown argument "4" for command "rollback". Add "--help" for more information about the arguments.`
 `# dnf5 history rollback --help`
Usage:
  dnf5 history rollback [GLOBAL OPTIONS] [OPTIONS] [ARGUMENTS]

**Comment by evan-goode** [comment]
Should this issue be closed since #642 is merged, temporarily removing the unimplemented subcommands? We have https://github.com/rpm-software-management/dnf5/issues/140 to track the implementation of the subcommands.

**Comment by mark-hyde** [comment]
Happy to close as it's covered elsewhere
