### ISSUE TITLE
Doc: check that all command line options are documented in respective man pages

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#644]
Discovered via https://bugzilla.redhat.com/show_bug.cgi?id=2216660 (man dnf5-install lacks `--skip-unavailable` and `--skip-broken` description, but I suppose there is more missing.

**Comment by glum23** [comment]
There is a lot of such missing options and the list of options is inconsistent in `man dnf5-<command>` and `dnf5 <command> --help`. E.g. in `man dnf5-upgrade` in comparison with `dnf5 upgrade --help` there are missing the following options:
~~~
--advisory=ADVISORY_NAME,...
--allow-downgrade
--bz=BUGZILLA_ID,...
--cve=CVE_ID,...
--downloadonly
--no-allow-downgrade
--skip-unavailable
~~~

**Comment by jan-kolarik** [comment]
> (man dnf5-install lacks --skip-unavailable and --skip-broken description, but I suppose there is more missing.

This is already fixed by https://github.com/rpm-software-management/dnf5/pull/1036.

**Comment by hedayat** [comment]
I just stumbled upon the missing `list` command in `man dnf5`!
