### ISSUE TITLE
Translations are not available

### ISSUE THREAD

**Issue by goeranu** [rpm-software-management/dnf5#658]
Testing out _dnf5_ on my Fedora 38 system, the first thing that struck me was it had reverted to English. I note there is a `dnf5/po` directory in the repository, but it is empty save for the `pot` file.

Would it be possible to make _dnf5_ available for translation, and the translations included in the distribution?

**Comment by j-mracek** [comment]
Thank you for the report. We plan to translate the project for other languages.

**Comment by jan-kolarik** [comment]
This should be resolved by https://github.com/rpm-software-management/dnf5/issues/419.

**Comment by goeranu** [comment]
It is true that an infrastructure for translation has been set up, But there are very few translations available, and most of the components are locked in the _dnf5_ project on Weblate so I can't add, in my case, Swedish. _Dnf5_ isn't really *available* for translation yet.

**Comment by m-blaha** [comment]
Oh, my bad. I must have forgotten to unlock the components... Now it should be allright.
