### ISSUE TITLE
RFE: --source option

### ISSUE THREAD

**Issue by goeranu** [rpm-software-management/dnf5#659]
The option `--source` of DNF4 is useful to fetch the source package of some binary package, even without having to figure out yourself what the name of the source package is, and without having to explicitly enable the correct source repositiry. Apparently, it is missing from _dnf5_. It is not too complicated to script that on top of _dnf5_. but it would be nice to have it available natively.

Tested on Fedora with dnf5-5.0.13-2.fc38.x86_64.

**Comment by pkratoch** [comment]
Hello, there is no general option `--source` in DNF4, but the option exists for `repoquery` or `download` commands. For `repoquery`, the option is already implemented (PR: https://github.com/rpm-software-management/dnf5/pull/595, already in dnf5-5.0.15). It's not done for `download` command yet (tracking issue for the download command: https://github.com/rpm-software-management/dnf5/issues/494). Or is there any other command that has the `--source` option that I missed?
