### ISSUE TITLE
Need help converting to libdnf5

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#66]
I'm trying to get an idea of what's going to be needed to convert lorax and other dnf based project to libdnf5. I started out with a simple app I use to try and see how far I could get.

After some stumbling around (the docs really need to have python examples, that's how many existing projects use dnf) the c++ docs I got to the point where I'm stuck trying to iterate the results of the transaction.

See https://github.com/bcl/test-dnf-transaction/pull/1 for the current attempt.

**Comment by jan-kolarik** [comment]
Hi Brian and sorry for the late reply. Are you still struggling with the `dnf5` API setup? We have currently some python tutorials PR in progress [here](https://github.com/rpm-software-management/dnf5/pull/102) which could already give some hints.

**Comment by jan-kolarik** [comment]
Looking at your link I see now. There seems to be missing some SWIG vector definition for transaction objects in `dnf5`. I will try to look at it tomorrow and let you know.

**Comment by jan-kolarik** [comment]
Hello Brian, please look at the mentioned PR, it should fix the issues in your attempt with using the `dnf5` Python API.

**Comment by bcl** [comment]
> Hello Brian, please look at the mentioned PR, it should fix the issues in your attempt with using the `dnf5` Python API.

Thanks for the reply, I added the patch to the current 5.0.1 release and now I can iterate the transactions!

My simple test project is now working, I'll move on to more complex uses next.

One very annoying thing about the new API is the `.set()` and `.get_value()` requirement. Is there any chance of those being turned into regular python so you can just use `=` and read the value directly or is this a permanent change?

**Comment by jan-kolarik** [comment]
Looking into your example [here](https://github.com/bcl/test-dnf-transaction/blob/cf29dcf267757bf494058b467fb893341e3e80ff/test-dnf-transaction#L87), this could be now done using the `add_item()` and `add()` methods for appending the single item or all items from another list.

Talking about the `set()` and `get_value()` methods, this is how it is implemented in the C++ library and the methods are also used internally therefore the priority argument is needed for these purposes. But you're right that when using these methods through the Python bindings API, the priority argument makes no sense then as it should be always `RUNTIME` and it could be irritating to supply it everytime. I could look into it if there is some easy way how to redefine the `=` operator on the SWIG layer.

**Comment by jan-kolarik** [comment]
Hi Brian, we've discussed the configuration options API and kept the `set()` and `get_value()` methods. If there will be more requests about this topic we could reconsider in the future.

For now at least you can already use the `set(value)` method overloads and omit the priority argument which will store the `RUNTIME` value.

I will close this thread as the original problem was resolved, but feel free to create a new issue if anything bugs you.

**Comment by jan-kolarik** [comment]
I created the issue, so we don't forget about this and to discuss the priority and possible implementation pitfalls there...
