### ISSUE TITLE
Create a man page related to caching functionality

### ISSUE THREAD

**Issue by jan-kolarik** [rpm-software-management/dnf5#668]
I think it would be great to summarize and document somewhere all caching features of DNF5 CLI.

What to include:
- parameters
  - `--cacheonly`, `--refresh`
- configuration options
  - `cachedir`, `cacheonly`, `keepcache`, `build_cache`
- commands
  - `clean`, `makecache`

Mention typical user use cases and examples.

**Comment by glum23** [comment]
Please stress the differences in comparison with dnf4 also in https://dnf5.readthedocs.io/en/latest/changes.html, e.g. the different system cache path and the different default cache destination for non-root users. When `dnf makecache` is called by a common user, nothing is stored in their home directory while `dnf5 makecache` stores the whole dnf5 cache there.
