### ISSUE TITLE
repoquery --whatprovides doesn't work with files in /boot

### ISSUE THREAD

**Issue by hiredman** [rpm-software-management/dnf5#685]
I am on fedora rawhide which recently replaced its `dnf` command with the `dnf5` provide one.  A common task I do (for reasons) is run `dnf provides` over /boot/*vmlinuz* which gives me the list of packages that installed various kernels. dnf5 doesn't have a `provides` subtask so I have switched to `repoquery --whatprovides`, which works on most files:
```
% dnf repoquery --whatprovides /bin/zsh
Updating and loading repositories:
Repositories loaded.
zsh-0:5.9-5.fc38.x86_64
% 
```
but does not work in files in /boot seemingly:
```
% dnf repoquery --whatprovides /boot/vmlinuz-6.4.0-0.rc7.20230623git8a28a0b6f1a1.57.fc39.x86_64
Updating and loading repositories:
Repositories loaded.
% 
```
rpm -qf seems to work fine since the package is installed though:
```
% rpm -qf /boot/vmlinuz-6.4.0-0.rc7.20230623git8a28a0b6f1a1.57.fc39.x86_64                     
kernel-core-6.4.0-0.rc7.20230623git8a28a0b6f1a1.57.fc39.x86_64
% 
```

for my particular case I likely should have been using rpm -qf all along, so that is what I will switch to, but provides not working on stuff in /boot is weird

**Comment by jan-kolarik** [comment]
Hi, I am testing this with current upstream version in Fedora 38 container and it seems working OK:
```
[root@cdea1f56712a dnf5]# dnf5 repoquery --whatprovides /boot/vmlinuz-6.3.8-200.fc38.x86_64
Updating and loading repositories:
Repositories loaded.
kernel-core-0:6.3.8-200.fc38.x86_64
```
Could it be due to outdated filelists metadata? With current dnf5 version you can do:
```
dnf5 repoquery --whatprovides /boot/vmlinuz-6.3.8-200.fc38.x86_64 --refresh
```
With not latest versions you can first invalidate cache before running the command like:
```
dnf5 clean expire-cache
```

**Comment by jan-kolarik** [comment]
You can also use glob to query various versions, but the processing time is much longer then:
```
dnf5 repoquery --whatprovides /boot/vmlinuz*
```

**Comment by hiredman** [comment]
```
% dnf5 clean expire-cache
Removed 0 files, 0 directories. 0 errors occurred.
% dnf5 repoquery --whatprovides /boot/vmlinuz* --refresh
Unknown argument "--refresh" for command "repoquery". Add "--help" for more information about the arguments.
zsh: exit 2     dnf5 repoquery --whatprovides /boot/vmlinuz* --refresh
% dnf5 repoquery --whatprovides /boot/vmlinuz*
Updating and loading repositories:
 Fedora - Modular Rawhide - Developmental packages for the next Fedora release                                         100% |  81.1 KiB/s |  23.0 KiB |  00m00s
 keybase                                                                                                               100% | 107.7 KiB/s |   3.3 KiB |  00m00s
 Fedora - Rawhide - Developmental packages for the next Fedora release                                                 100% |  48.5 KiB/s |  18.5 KiB |  00m00s
 Fedora rawhide openh264 (From Cisco) - x86_64                                                                         100% |   3.4 KiB/s | 989.0   B |  00m00s
 Copr repo for pdfsandwich owned by merlinm                                                                            100% |   5.4 KiB/s |   3.3 KiB |  00m01s
 RPM Fusion for Fedora rawhide - Free tainted                                                                          100% |  13.5 KiB/s |   3.2 KiB |  00m00s
 RPM Fusion for Fedora Rawhide - Free                                                                                  100% |   7.6 KiB/s |   3.5 KiB |  00m00s
 RPM Fusion for Fedora rawhide - Nonfree tainted                                                                       100% |  25.2 KiB/s |   6.1 KiB |  00m00s
 slack                                                                                                                 100% |   6.5 KiB/s |   1.8 KiB |  00m00s
 RPM Fusion for Fedora Rawhide - Nonfree                                                                               100% |  14.4 KiB/s |   6.9 KiB |  00m00s
Repositories loaded.
% rpm -q kernel
kernel-6.4.0-0.rc4.20230601git929ed21dfdb6.38.fc39.x86_64
kernel-6.5.0-0.rc0.20230628git6aeadf7896bf.2.fc39.x86_64
%
```

**Comment by kontura** [comment]
Can you check what dnf5 version you have?

Also another possible explanation could be that you do not have updated kernel to the newest version. Given that rawhide metadata contain only the latest version looking for files from older kernels will not work.

**Comment by kontura** [comment]
> Ah, I get it:
> 
> ```
> dnf5 repoquery --whatprovides /boot/vmlinuz*
> ```
> 
> fails because --whatprovides can only take a single file(not sure if this is intentional)

It does actually take multiple parameters but they have to be separated by `,` if shell expands the `*` they are separated by space. If you pass the wildcard directly to dnf: `dnf5 repoquery --whatprovides "/boot/vmlinuz*"` or even `dnf5 repoquery --whatprovides=/boot/vmlinuz*` it should work.


> but that is a change from legacy dnf where dnf provides would handle files installed by not the most recent kernel.

I think the difference is that repoquery runs by default with only available packages (not installed) but you can try:
```
repoquery --whatprovides=/boot/vmlinuz* --installed --available 
```
this should find all installed kernels (even if not latest) and the latest available.

**Comment by hiredman** [comment]
oh, well great, thanks for the education
