### ISSUE TITLE
Add repoquery -l/--list as alias for --files

### ISSUE THREAD

**Issue by FrostyX** [rpm-software-management/dnf5#696]
I discovered this regression because the `fedora-review` tool now started failing. It calls the `dnf repoquery` command with `-C` and `-l` parameters.

See for example here
https://pagure.io/FedoraReview/blob/wip/f/src/FedoraReview/deps.py#_286

A simple reproducer

```
$ fedora-review -b 2209024
Unknown argument "-l" for command "repoquery". Add "--help" for more information about the arguments.
ERROR: Exception down the road... (logs in /home/jkadlcik/.cache/fedora-review.log)
```

Can those be added to DNF5 please?

**Comment by jn64** [comment]
`-C` is in since #665

`-l` `--list` was [changed to](https://github.com/rpm-software-management/dnf5/blob/1288e7374a774d7a638163882e0fcfc1672b4e34/doc/changes.rst?plain=1#L145) `--files`. I would like `-l` `--list` to be retained for compatibility and convenience (easier to switch between dnf4/5 and also mirrors the `rpm -q` option, easier to remember as distinct from `--file`).

**Comment by FrostyX** [comment]
Thank you @jn64, I didn't know that.
`--files` is good enough for me, but adding `-l` for backward compatibility sounds IMHO reasonable.

Feel free to close this issue once a new DNF5 with `-C` is released.

**Comment by jn64** [comment]
I suggest renaming the issue like "Add repoquery -l/--list as alias for --files"
;)

**Comment by FrostyX** [comment]
In case `-l`, `--list` won't be implemented, can you please mention it here?
https://dnf5.readthedocs.io/en/latest/changes.html#repoquery-command
or in some other comparison table?

Btw, I am not seeing `repoquery --resolve` mentioned there as well and it isn't available in DNF5.

**Comment by kontura** [comment]
I have totally missed the rpm compatibility aspect for `--files`, thank you.
PR: https://github.com/rpm-software-management/dnf5/pull/707

> Btw, I am not seeing `repoquery --resolve` mentioned there as well and it isn't available in DNF5.

It is not implemented yet together with a couple of other options: https://github.com/rpm-software-management/dnf5/issues/122
Also can I ask what is your use case for it?

**Comment by FrostyX** [comment]
> > I have totally missed the rpm compatibility aspect for --files, thank you.
> PR: https://github.com/rpm-software-management/dnf5/pull/707

Thank you very much for the PR

> It is not implemented yet together with a couple of other options: https://github.com/rpm-software-management/dnf5/issues/122

I completely missed the issue, sorry about that.

> Also can I ask what is your use case for it?

It is used in `fedora-review` but I am not the author and I don't have the best knowledge of the codebase either. But I am trying to find out, see this thread (search for "--resolve").

https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/QMCHW3ZUTKLPIDARUFKPINA3VBSI3OT5/#AN2W7KFRQ7AVKYXOBS7SRGJC57OI3KTD

**Comment by j-mracek** [comment]
@FrostyX Because the original request is resolved. May I ask you to track `--resove` in another issue? It is not easy to find in the discussion why the issue is not yet closed. What do you think?

**Comment by FrostyX** [comment]
Sure, makes sense.

**Comment by FrostyX** [comment]
Actually, the #122 issue should be enough?
