### ISSUE TITLE
Add support for `$releasever_major`, `$releasever_minor`, and limited shell expansion

### ISSUE THREAD

**Issue by Conan-Kudo** [rpm-software-management/dnf5#710]
### Description of request
Zypper defines in its man page that two additional variables are auto-defined based on `$releasever`'s definition: `$releasever_major` and `$releasever_minor`.

Per `zypper(8)`:

> In addition `$releasever_major` will be set to the leading portion up to
> (but not including) the 1st dot; `$releasever_minor` to the trailing portion
> after the 1st dot. If there’s no dot in `$releasever`, `$releasever_major` is
> the same as `$releasever` and `$releasever_minor` is empty.

This can be verified by reading the man page of zypper on any Fedora system.

In addition, it seems that SUSE has [implemented very limited shell expansion capabilities](https://doc.opensuse.org/projects/libzypp/HEAD/structzypp_1_1repo_1_1RepoVarExpand.html) for supporting SUSE Linux Enterprise upgrades due to how their OBS names the repos.

For example, this is a common thing to see in repo files for SLE when trying to use repos from the openSUSE Build Service (or other OBS instances making SLE packages): `SLE_${releasever_major}${releasever_minor:+_SP$releasever_minor}`.

Having support for this would make it tremendously easier to slot in DNF in place of Zypper in SUSE distributions.

The implementation in libzypp is here:

* header: https://github.com/openSUSE/libzypp/blob/d03a02d986f43266af81c73cced1b310e8615971/zypp/repo/RepoVariables.h
* source: https://github.com/openSUSE/libzypp/blob/d03a02d986f43266af81c73cced1b310e8615971/zypp/repo/RepoVariables.cc

### Benefit to RHEL/CentOS

Starting with EPEL 10, [EPEL will be versioning its repositories with minor versions (`epel10.Y`) targeting RHEL and the major version-only branch (`epel10`) will target CentOS Stream 10](https://discussion.fedoraproject.org/t/epel-10-proposal/44304).

EPEL would really like this feature so that we can have a singular `epel-release` package that seamlessly works on CentOS Stream and derivatives (such as RHEL, Alma, etc.).

**Comment by Conan-Kudo** [comment]
cc: @davide125, @carlwgeorge, @tdawson

**Comment by gotmax23** [comment]
+1. It'd be great to have this in time for EL 10.

**Comment by j-mracek** [comment]
Zypper uses following code for parsing `releasever`:
```

        /** Split \c releasever at \c '.' and store major/minor parts as requested. */
        void splitReleaseverTo( const std::string & releasever_r, std::string * major_r, std::string * minor_r ) const
        {
          if ( major_r || minor_r )
          {
            std::string::size_type pos = releasever_r.find( "." );
            if ( pos == std::string::npos )
            {
              if ( major_r ) *major_r = releasever_r;
              if ( minor_r ) minor_r->clear();
            }
            else
            {
              if ( major_r ) *major_r = releasever_r.substr( 0, pos );
              if ( minor_r ) *minor_r = releasever_r.substr( pos+1 ) ;
            }
          }
        }
```

**Comment by Conan-Kudo** [comment]
We should probably also have a `$RELEASEVER_PATCH` if it's `x.y.z` too. I think some of the immutable OSes use this format to preserve the base OS version and then append the build date as a third number.

**Comment by j-mracek** [comment]
Note: If we will introduce `$RELEASEVER_PATCH` then we will create incompatibility with zypper.

**Comment by Conan-Kudo** [comment]
I have a feeling that Zypper may adopt it once we have it, since they will encounter a similar problem soon enough. 😉

**Comment by Conan-Kudo** [comment]
That said, we don't need to implement `$RELEASEVER_PATCH` right now.

**Comment by Conan-Kudo** [comment]
The goal for EPEL is that we can have `${RELEASEVER_MAJOR}${RELEASEVER_MINOR:+.${RELEASEVER_MINOR}}` for EPEL's repo definition for EPEL 10, so that things transparently handle going from RHEL to CentOS Stream.

**Comment by j-mracek** [comment]
The implementation in DNF5 should be accompanied by implementation in DNF4. We also need CI test for this functionality.

**Comment by gotmax23** [comment]
Right, especially now that dnf5 is no longer planned for RHEL 10, we'll need this in libdnf to allow us to use it for the new EPEL 10 release structure.
