### ISSUE TITLE
dnf5 make cache --refresh

### ISSUE THREAD

**Issue by 11raob** [rpm-software-management/dnf5#711]
Run (as superuser or root)

# dnf makecache --refresh

Receive the following output---
root@machinename:~# dnf makecache  --refresh 
terminate called after throwing an instance of 'std::filesystem::__cxx11::filesystem_error'
  what():  filesystem error: cannot create directory: Not a directory [/var/cache/libdnf5/fastestmirror.cache/attrs]
Aborted (core dumped)

**Comment by jan-kolarik** [comment]
Bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2222143.
