### ISSUE TITLE
dnf5 will not install an older kernel

### ISSUE THREAD

**Issue by AdamWill** [rpm-software-management/dnf5#720]
kernels being parallel-installable in Fedora, it should be fine to install one that is *older* than the latest one currently installed. Previous versions of dnf and yum let you do this, no problem.

Attempting to do it with dnf5, though, results in an error. Here, I have kernel-6.5.0-0.rc1.20230711git3f01e9fed845.12.fc39 installed, and I want to install kernel-6.5.0-0.rc0.20230706gitc17414a273b8.12.fc39 alongside it:

    Transaction failed: Rpm transaction failed.
      - package kernel-modules-core-6.5.0-0.rc1.20230711git3f01e9fed845.12.fc39.x86_64 (which is newer than kernel-modules-core-6.5.0-0.rc0.20230706gitc17414a273b8.12.fc39.x86_64) is already installed
      - package kernel-core-6.5.0-0.rc1.20230711git3f01e9fed845.12.fc39.x86_64 (which is newer than kernel-core-6.5.0-0.rc0.20230706gitc17414a273b8.12.fc39.x86_64) is already installed
      - package kernel-modules-6.5.0-0.rc1.20230711git3f01e9fed845.12.fc39.x86_64 (which is newer than kernel-modules-6.5.0-0.rc0.20230706gitc17414a273b8.12.fc39.x86_64) is already installed
      - package kernel-6.5.0-0.rc1.20230711git3f01e9fed845.12.fc39.x86_64 (which is newer than kernel-6.5.0-0.rc0.20230706gitc17414a273b8.12.fc39.x86_64) is already installed

This happens whether you use `dnf install` or `dnf downgrade`.

**Comment by AdamWill** [comment]
Running `dnf-3 install` instead of `dnf install`, the operation works fine.

**Comment by jan-kolarik** [comment]
There is also related Bugzilla ticket: https://bugzilla.redhat.com/show_bug.cgi?id=2221308.

**Comment by jan-kolarik** [comment]
Could you please provide a reproducer and dnf5 version? I tried to install the `6.5.0-0.rc1.20230711git3f01e9fed845.12.fc39.x86_64` kernel in Rawhide container and then downgrade to `6.3.12-200.fc38` with dnf5 `5.0.15` and everything seems OK.

**Comment by jan-kolarik** [comment]
Maybe it is also connected with the currently running kernel version and new dnf5 having the `allow_vendor_change` option set to `False` by default.

**Comment by m-blaha** [comment]
I have a reproducer and a test case prepared for CI stack.

**Comment by m-blaha** [comment]
The test case is in this PR: https://github.com/rpm-software-management/ci-dnf-stack/pull/1337 (currently draft, I'm still working on it)
