### ISSUE TITLE
Missing `dnf5 remove --allowerasing` option

### ISSUE THREAD

**Issue by praiskup** [rpm-software-management/dnf5#729]
SSIA, reported against [mock](https://github.com/rpm-software-management/mock/issues/1149).

**Comment by j-mracek** [comment]
May I ask you why the option is required even in dnf4?

DNF4 and DNF5 adds allow-erasing flag to transaction by default. Using `--allowerasing` with dnf4 is redundant or unneeded.

I propose to close the bug report.

**Comment by praiskup** [comment]
It is used by default for every DNF transaction.

**Comment by praiskup** [comment]
I mean, Mock uses this option whenever a DNF command is run;  if `allowerasing` is the default, we'll have to fix/reconfigure Mock.

**Comment by kontura** [comment]
> I mean, Mock uses this option whenever a DNF command is run; if `allowerasing` is the default, we'll have to fix/reconfigure Mock.

In `dnf5` we are trying to convert as many global options as possible to command specific options.
This means that for example the `--allowerasing` can no longer be used for any command but currently just for:
`downgrade`. `upgrade`, `distro-sync`, `install`, `swap`, `builddep`. It is not the default for these options.

We are doing this to fix options that don't make sense for all commands. Like: `dnf repoquery htop --allowerasing`, it works with old dnf but really is wrong.

Similarly to the `repoquery` example `--allowerasing` had no effect for the `remove` command so the option is not available for it in dnf5.

(Internally `dnf` of course allows erasing of installed packages for the `remove` command which is the functionality of `allowerasing` but it is not connected to the option.)
