### ISSUE TITLE
dnf5 must provide a man page for dnf.conf file

### ISSUE THREAD

**Issue by m-blaha** [rpm-software-management/dnf5#742]
The man page should also cover new `#!include` directive introduced by https://github.com/rpm-software-management/dnf5/pull/741

**Comment by jan-kolarik** [comment]
I guess this is a duplicate of https://github.com/rpm-software-management/dnf5/issues/309 ?

**Comment by jan-kolarik** [comment]
Closing as duplicate and also the #741 was eventually closed.
