### ISSUE TITLE
dnf5 messes up terminal if interrupted during the middle of installation.

### ISSUE THREAD

**Issue by DaanDeMeyer** [rpm-software-management/dnf5#748]
If I SIGKILL dnf5 while it's in the middle of installing packages, my terminal, the cursor my terminal usually has is gone. This only happens when interrupting dnf5 while it's installing packages, not while it's downloading repo metadata.

Before invoking dnf5:

![image](https://github.com/rpm-software-management/dnf5/assets/9395011/efd68388-a151-4d53-b5fe-e62b3fe5dc0e)

After SIGKILL of dnf5 during package installation:

![image](https://github.com/rpm-software-management/dnf5/assets/9395011/ac6d33d9-b16f-4b80-bb60-d7d1346aa361)

`reset` fixes the issue and I get my cursor back. `clear` does not fix the issue

Interrupting any other command during execution does not cause my terminal to lose its cursor, it only happens with dnf5.

**Comment by ppisar** [comment]
There is nothing DNF5 can do besides not hiding the cursors at all. SIGKILL is uncatchable and a user process cannot react on it in any way. This effect of invisible cursor after killing is common to all application that hide the cursor for aesthetic reason.

I recommend you instead terminating DNF5 with SIGTERM or SIGQUIT. Those signals can be handled and they are subject of issue #851.
