### ISSUE TITLE
Variables are not expanded in urls from mirrorlist=

### ISSUE THREAD

**Issue by DaanDeMeyer** [rpm-software-management/dnf5#761]
The alma linux mirrorlist returns urls with $basearch in them (e.g. https://mirrors.almalinux.org/mirrorlist/8/appstream). With dnf4, $basearch is expanded in these urls, in dnf5 $basearch is not expanded. dnf5 should expand $basearch and other variables in these urls as well.

**Comment by j-mracek** [comment]
@DaanDeMeyer May I ask you for a reproducer with DNF5. It will speed up development.

**Comment by DaanDeMeyer** [comment]
```
git clone github.com/systemd/mkosi
cd mkosi
dnf install dnf5
bin/mkosi -d alma -t directory -f # This will fail with 404 with $basearch in the alma url
dnf remove dnf5
bin/mkosi -d alma -t directory -f # This will succeed without problems
```

**Comment by j-mracek** [comment]
Thank you. It looks like that with `-d alma` it doesn't work but with `-d fedora` it works correctly. I believe that it is related to a different setting for dnf5 fot `alma` distribution.

**Comment by j-mracek** [comment]
Commands for both distribution looks nearly identical, therefore I guess that the difference should be in dnf.conf or content of vars directory.

**Comment by DaanDeMeyer** [comment]
So dnf5 is already supposed to replace the $basearch variables in the mirrors returned by the alma mirrorlist (https://mirrors.almalinux.org/mirrorlist/8/appstream)?

**Comment by j-mracek** [comment]
There is a test in our CI that is disabled for DNF5 (vars.feature Scenario: Variables are substituted in mirrorlist URLs)
