### ISSUE TITLE
clang prints many warnings

### ISSUE THREAD

**Issue by yurivict** [rpm-software-management/dnf5#769]
[log](https://people.freebsd.org/~yuri/dnf5-5.1.0-build.log)

You use ```-Werror``` which was removed for this compilation. Otherwise every warning would be an error.

Version: 5.1.0
clang-15
FreeBSD 13.2

**Comment by pkratoch** [comment]
Hello, these warnings are coming from libsolv, so, I'd suggest to file the issue there: https://github.com/openSUSE/libsolv
