### ISSUE TITLE
dnf5daemon: Add functions to work with local files into org.rpm.dnf.v0.rpm.Rpm D-Bus interface

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#772]
In order to be feature complete with PackageKit (on the gnome-software side), it would be good to add functions to work with local .rpm files, specifically:
1. to be able to get details about a local .rpm file
2. to be able to install it.

The PackageKit functions are `pk_client_get_details_local()` and `pk_task_install_files_sync()`. And for URI-s also `pk_client_resolve()`.

**Comment by mcrha** [comment]
If I can expand on this a bit: The install is possibly covered by https://github.com/rpm-software-management/dnf5/pull/371 , there there lefts a way to get details about the rpm itself. I did not find anything in the current dnf5 API (git checkout with 5.1.11 in VERSION.cmake at commit 1461a37489448bf574e614757d40dcfe53fd65c6 ).

The work flow I'm looking for is:

1. user receives an .rpm file and opens it in gnome-software
2. gnome-software asks dnf5 for details about the .rpm file content, just
   like `org.rpm.dnf.v0.rpm.Rpm::list: package_attrs` property does.
3. gnome-software asks dnf5 whether this package is already installed and
   in what version (it won't suggest install to lower version than in the system)
4. gnome-software shows the details to the user
5. when user clicks Update/Install button the package is updated/installed

From what I understood the mentioned merge request does only the last thing (5.), but not the 2. neither the 3. .

**Comment by m-blaha** [comment]
With this PR https://github.com/rpm-software-management/dnf5/pull/1245 `Rpm::list` is able to retrieve info about rpm file.

**Comment by jan-kolarik** [comment]
This is already done as mentioned in https://bugzilla.redhat.com/show_bug.cgi?id=2124501.
