### ISSUE TITLE
dnf5daemon: Add functions to support system upgrade into a D-Bus interface

### ISSUE THREAD

**Issue by mcrha** [rpm-software-management/dnf5#774]
I know one may think of this as a duplicate of the https://github.com/rpm-software-management/dnf5/issues/258 , but it's not it, because you use a word `upgrade` in a meaning of `update`, while the `upgrade` I talk about is a move from one system version to another, like from Fedora 38 to Fedora 39. The `distro_sync` is close to it, but not exactly it. Not talking it should be done in stages like the #258, only for the whole system/"all" packages.

This is to be feature complete with PackageKit (on the gnome-software side).

**Comment by pirat89** [comment]
@mcrha  to be honest, it seems to me as duplicate as #258 is covering the upgrade between major versions also, as that's the main use-case of offline upgrades.

**Comment by mcrha** [comment]
If it's so, then even better.

**Comment by mcrha** [comment]
I'm closing this in favour of the #258
