### ISSUE TITLE
Regression in Vars handling

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#792]
There are 3 issues covered by CI scenarios (`vars.feature`) that fails with DNF5

- [x] Scenario: Variables arch supports basearch `loongarch64` {}
Substitution of multiple vars in section `[dnf-ci-test-$arch-$basearch]` fails

- [x] Scenario: Using dnf with non-files in /etc/dnf/vars
- bz2091636

- [x] Scenario: Ignoring variable files with invalid encoding
- bz2141215

**Comment by m-blaha** [comment]
The issue with invalid encoding doesn't seem to affect dnf5. The problems with loongarch64 and non-files in the 'vars' directory have been resolved by https://github.com/rpm-software-management/dnf5/pull/797 and https://github.com/rpm-software-management/dnf5/pull/798, respectively.
