### ISSUE TITLE
dnf builddep --spec returns 'Unknown argument'

### ISSUE THREAD

**Issue by bcl** [rpm-software-management/dnf5#799]
See https://github.com/osbuild/weldr-client/actions/runs/5752335719/job/15593094835?pr=114

I understand that the dnf5 builddep may be different, and from the --help output it only accepts .spec files so `--spec` is redundant, but it might make the transition from dnf4 easier if it accepted `--spec` without an error.

**Comment by dcantrell** [comment]
Yeah, this is reasonable and will make it easier for people bringing scripts and commands to dnf5 from legacy dnf.  I've added --spec and --srpm as no-op arguments for the builddep command.  It's true the behavior is different and dnf5 doesn't require the explicit argument anymore, but the no-op commands are fine.
