### ISSUE TITLE
Inform DNF dependents that switch to DNF 5 has been postponed

### ISSUE THREAD

**Issue by evan-goode** [rpm-software-management/dnf5#822]
Follow-up to https://github.com/rpm-software-management/dnf5/issues/418. Many users of DNF already changed their spec to depend on `dnf5` in Fedora 39+, but these changes now should be reverted or changed to Fedora 41+.

These dependents should be informed that DNF 5 is not going to replace DNF 4 as the default package manager until (likely) Fedora 41.

We also should advertise https://copr.fedorainfracloud.org/coprs/rpmsoftwaremanagement/dnf5-testing/.

List of dependents:

- [x] auter
  - https://github.com/rackerlabs/auter/issues/245
- [x] calamares
  - https://github.com/calamares/calamares/issues/2145
- [x] copr-builder
  - https://github.com/fedora-copr/copr/issues/2739
  - copr-builder should be fine, all they changed was to additionally require DNF 5
- [x] dnf-plugin-diff
  - https://github.com/praiskup/dnf-plugin-diff/pull/1
  - No action needed
- [x] dnfdragora
  - https://github.com/manatools/dnfdragora/issues/214
- [x] etckeeper-dnf
  - https://src.fedoraproject.org/rpms/etckeeper/pull-request/6
- [x] fedora-review
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209416
  - No action required, still depends on DNF
- [x] fedora-upgrade
  - https://github.com/xsuchy/fedora-upgrade/pull/46
- [x] kiwi-systemdeps-core
  - https://github.com/OSInside/kiwi/pull/2353
- [x] libdnf-plugin-subscription-manager
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209387
  - No action required, depends on python3-dnf
- [x] lpf
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209396
- [x] mock
  - https://github.com/rpm-software-management/mock/issues/1084
  - https://github.com/rpm-software-management/mock/pull/1185
- [x] osbuild
  - https://github.com/osbuild/osbuild/issues/1315
- [x] perl-CPAN-Plugin-Sysdeps
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209402
  - Change was made but now reverted in F39
- [x] policycoreutils-devel
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209404
- [x] rbm
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209405
  - Change was made but now reverted in F39
- [x] rpmdistro-repoquery
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209408
  - No action needed
- [x] subscription-manager
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209411
- [x] supermin, supermin-devel
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209412
  - Fixed already in https://src.fedoraproject.org/rpms/supermin/c/b394af62b0292e4243354236eb984218be48499f?branch=rawhide
- [x] system-config-language
  - https://bugzilla.redhat.com/show_bug.cgi?id=2209413

**Comment by jan-kolarik** [comment]
Probably also `ansible` as they was [recently](https://github.com/ansible/ansible/issues/78898) also adding a dnf5 module, right?

**Comment by evan-goode** [comment]
> Probably also `ansible` as they were [recently](https://github.com/ansible/ansible/issues/78898) also adding a dnf5 module, right?

Thanks, I posted to their mailing list. They shouldn't need to make any packaging changes; `ansible` depends on neither `dnf` nor `dnf5`, they detect which package manager to use at runtime.

**Comment by evan-goode** [comment]
OK, I've checked in with each project. The important PRs to watch are:
- https://github.com/OSInside/kiwi/pull/2353
- https://github.com/xsuchy/fedora-upgrade/pull/46

They changed their specs to depend on `dnf5` in F39+, but hopefully we can revert that before Fedora 39 goes GA.
