### ISSUE TITLE
new feature - dnf search by parsing output 

### ISSUE THREAD

**Issue by catafest** [rpm-software-management/dnf5#829]
Will be great if **dnf5 search** will come with a feature to parse the output.
At this moment you can use the pipe and grep or awk to parse the result, but most people want to see the output parsed by a **version**, **devel**, **libs**, or maybe **a regular expression**.
I think this will be a good feature and will speed up the tasks with the DNF5 tool.

**Comment by ppisar** [comment]
I don't understand what you mean with "parsed by a version". Do you mean only search in a package version? What does mean by "devel" or "libs"? Do you mean search only in packages whose name ends with "-devel" or "-libs"? Could you elaborate more? Can you give some example?

Does the "regular expression" mean that the search pattern passed in an argument should be a regular expression? I believe that now it's a glob. E.g. "pcre*-devel" returns both "pcre-devel" and "pcre2-devel".

**Comment by j-mracek** [comment]
I am really sorry, but the request is not clear therefore I am closing the issue. Please feel free to reopen it with additional information.
