### ISSUE TITLE
DNF debuginfo-install Plugin

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#846]
- [ ] ``dnf debuginfo-install <pkg-spec>...``

- [ ] ``autoupdate`` a plugin confoguration option to passively enable all debuginfo repositories. I believe that it would require a libdnf5 plugin to allow the same behavior for all libdnf5 users

- [ ] enable DNF4 tests for debuginfo-install

============================
DNF debuginfo-install Plugin
============================

Install the associated debuginfo packages for a given package specification.

--------
Synopsis
--------

``dnf debuginfo-install <pkg-spec>...``

---------
Arguments
---------

``<pkg-spec>``
    The package to install the associated debuginfo package for.

-------
Options
-------

All general DNF options are accepted, see `Options` in :manpage:`dnf(8)` for details.

-------------
Configuration
-------------

``/etc/dnf/plugins/debuginfo-install.conf``

The minimal content of conf file should contain ``main`` sections with ``enabled`` and
``autoupdate`` parameter.

- [ ] ``autoupdate``

    A boolean option which controls updates of debuginfo packages. If options is enabled
    and there are debuginfo packages installed it automatically enables all configured
    debuginfo repositories.
    (Disabled by default.)

--------
Examples
--------

``dnf debuginfo-install foobar``
    Install the debuginfo packages for the foobar package.

``dnf upgrade --enablerepo=*-debuginfo <package-name>-debuginfo``
    Upgrade debuginfo package of a <package-name>.

``dnf upgrade --enablerepo=*-debuginfo "*-debuginfo"``
    Upgrade all debuginfo packages.

**Comment by travier** [comment]
Hey folks, we would appreciate if this could be targeted for the Fedora 41 timeframe as this is a dependency for plasma-drkonqi: https://src.fedoraproject.org/rpms/plasma-drkonqi/blob/rawhide/f/plasma-drkonqi.spec#_51

Otherwise, we'll have both dnf4 & 5 installed.

See also: https://pagure.io/workstation-ostree-config/pull-request/514

**Comment by ppisar** [comment]
Did plasma-drkonqi considered moving to libdebuginfod <https://sourceware.org/elfutils/Debuginfod.html> for obtaining debugging data?

**Comment by Conan-Kudo** [comment]
We already do this but we need a fallback for when that's not a viable backend. It is not reasonable to expect everything to be available via debuginfod with third party repositories (COPR, OBS, etc.).

**Comment by Conan-Kudo** [comment]
Also, Red Hat Enterprise Linux does not have debuginfod servers.
