### ISSUE TITLE
Make `--forcearch` option a global one

### ISSUE THREAD

**Issue by katexochen** [rpm-software-management/dnf5#872]
In dnf4, `--forcearch` was handled as a global option (between "dnf" and "\<command\>", like `dnf --forcearch=aarch64 install nano`.
With dnf5, this usage isn't currently possible. Some tools, including [mkosi](https://github.com/systemd/mkosi) use global options to construct a base command and append arguments dynamically.

**Comment by ppisar** [comment]
I confirm this issue with dnf5-5.1.2-20230906004518.61.g6d7cb379.fc40.x86_64:

~~~~
root@fedora-40:~ # dnf5 --forcearch=x86_64 install dnf5
Unknown argument "--forcearch=x86_64" for command "dnf5". Add "--help" for more information about the arguments.
~~~~

~~~~
root@fedora-40:~ # dnf5 install --forcearch=x86_64 dnf5
Updating and loading repositories:
Repositories loaded.
Package "dnf5-5.1.2-20230906004518.61.g6d7cb379.fc40.x86_64" is already installed.

Nothing to do.
~~~~

DNF5 indeed implements --forcearch option as an command-specific option at 10 subcommands now. I agree that with this amount of subcommands it makes sense to turn it into a global option.

**Comment by ppisar** [comment]
@evan-goode, you can take it. I don't have time for this now.
