### ISSUE TITLE
updateinfo: dnf5 output depends on timezone

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#900]
The output of `dnf5 updateinfo list` depends on the currently set time zone, namely 'Issued' time of advisories is transformed from (supposed) universal time to the local time.
~~~
# timedatectl
<snip>
               Time zone: America/Phoenix (MST, -0700)
<snip>
# dnf5 updateinfo list
Name                   Type        Severity                                    Package              Issued
FEDORA-2023-3630891bed enhancement Moderate                 make-1:4.4.1-1.fc38.x86_64 2023-09-13 18:27:18
FEDORA-2023-6a22f9d0ca enhancement Low         cloud-utils-growpart-0.33-3.fc38.noarch 2023-09-16 18:25:42
# timedatectl set-timezone Europe/Prague
# dnf5 updateinfo list
Name                   Type        Severity                                    Package              Issued
FEDORA-2023-3630891bed enhancement Moderate                 make-1:4.4.1-1.fc38.x86_64 2023-09-14 03:27:18
FEDORA-2023-6a22f9d0ca enhancement Low         cloud-utils-growpart-0.33-3.fc38.noarch 2023-09-17 03:25:42
~~~
It can be intentional, however, in that case upstream tests **updateinfo.feature** and **security-upgrade.feature** (both tagged as dnf5) have to be changed. They fail when the local time is different from the universal time.

**Comment by ppisar** [comment]
It's normal that time formatting functions and thus applications honor a localtime zone. Please adjust your tests to set TZ environment variable to a time zone your tests expect.
