### ISSUE TITLE
Docs: command man page vs. --help (without subcommand specified)

### ISSUE THREAD

**Issue by glum23** [rpm-software-management/dnf5#921]
> Regarding the `dnf5 updateinfo --help` not showing any options. I think that is expected, the options are for subcommands: `dnf5 updateinfo info --help`.

I'd expect the output of  `dnf5 updateinfo --help` similar to the related man page (especially because all subcommands' options are the same), sth like:
~~~
Usage:
  dnf5 advisory <COMMAND> [GLOBAL OPTIONS] [OPTIONS] [ARGUMENTS]
Command:                 
  list                          List advisories
  info                          Print details about advisories
  summary                       Print summary of advisories
Options:                         
 <list of options>
Arguments:                                     
  advisory-spec                                List of patterns matched against advisory names.
~~~
From my POV, seeking the relevant options in two steps is unnecessarily protracted. However, the current solution is consistent.

**Comment by glum23** [comment]
see also comments in https://github.com/rpm-software-management/dnf5/issues/919

**Comment by jrohel** [comment]
1. `[GLOBAL OPTIONS]` are expected behind `dnf5`:
`dnf5 [GLOBAL OPTIONS] advisory <COMMAND> [OPTIONS] [ARGUMENTS]`
Yes dnf5 accepts [GLOBAL OPTIONS] behind command/subcommand. It is for compatibility with old dnf. But imagine, subcommand can also define the option with the same name as global option but with different meaning. And then the position of the option will be very important.  

2. And in general `<COMMAND> [OPTIONS] [ARGUMENTS]` is also wrong. One command can have options and arguments. However, another COMMAND may have other options and arguments, but may also have no options and arguments at all. So blindly printing `[OPTIONS] [ARGUMENTS]` after `<COMMAND>` is wrong.

Examples:
`dnf5 [GLOBAL OPTIONS] cmd1 [cmd1 OPTIONS] [cmd1 ARGUMENTS] subcmd1 [subcmd1 OPTIONS] [subcmd1 ARGUMENTS]` -> usage: `dnf5 [GLOBAL OPTIONS] cmd1 [OPTIONS] [ARGUMENTS] subcmd1 [OPTIONS] [ARGUMENTS] `

But cmd2 does not have OPTIONS and ARGUMENTS. subcmd2 has only ARGUMENTS 
`dnf5 [GLOBAL OPTIONS] cmd2 subcmd2 [subcmd2 ARGUMENTS] ` -> usage: `dnf5 [GLOBAL OPTIONS] cmd2 subcmd2 [ARGUMENTS]`

And cmd3 has only OPTIONS. subcmd3 has OPTIONS and subsubCOMMANDS. And subsubcmd1 has only ARGUMENTS.
`dnf5 [GLOBAL OPTIONS] cmd3 [cmd3 OPTIONS] subcmd3 [subcmd3 OPTIONS] subsubcmd1[subsubcmd1 ARGUMENTS]` -> usage: `dnf5 [GLOBAL OPTIONS] cmd3 [OPTIONS] subcmd3 [OPTIONS] subsubcmd1[ARGUMENTS]`

And now:
`dnf5 cmd2 --help`
usage: `dnf5 [GLOBAL OPTIONS] cmd2 <COMMAND> ...`
We know that cmd2 has no OPTIONS and ARGUMENTS and expects subCOMMAND. But we don't know if the subCOMMAND has OPTIONS, ARGUMENTS until the user enters the subCOMMAND. That is why the three dots.

When the user asks for a specific subCOMMAND:
`dnf5 cmd2 subcmd2 --help`
usage: `dnf5 [GLOBAL OPTIONS] cmd2 subcmd2 [ARGUMENTS]`

I prepared a PR https://github.com/rpm-software-management/dnf5/pull/928 that generates the corresponding usage text.

**Comment by jrohel** [comment]
> I'd expect the output of dnf5 updateinfo --help similar to the related man page (especially because all subcommands' options are the same), sth like:

Just a coincidence. We have other subcommands whose options are not the same. Until the user enters which subcommand he is interested in, we do not know which options to list in help.
But in DNF5 we have bash completion which offers supported options including help.
