### ISSUE TITLE
DNF reposync Plugin

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#931]

**Comment by kontura** [comment]
- The `--source` option should be changed to `--srpm`. (We are trying to unify the options in dnf5 and we have decided to use `--srpm` everywhere. Old dnf sometimes used `--source` and sometimes `--srpm` which was confusing.)
- Related issue: https://github.com/rpm-software-management/dnf5/issues/380

**Comment by Conan-Kudo** [comment]
Any progress on this? The `reposync` command is the only way to mirror RHEL content, for example.

Here's an active use of this: https://github.com/datto/rhel-reposync-playbook/blob/main/roles/install_reposync/files/rhel-reposync.sh

**Comment by kontura** [comment]
We should also make sure to cover this issue: https://github.com/rpm-software-management/dnf-plugins-core/pull/566#pullrequestreview-2420626395
