### ISSUE TITLE
dnf download `--arch <arch>[,<arch>...]`

### ISSUE THREAD

**Issue by j-mracek** [rpm-software-management/dnf5#946]
Limit the query to packages of given architectures (default is all compatible architectures with
your system). To download packages with arch incompatible with your system use
--forcearch=<arch> option to change basearch.

**Comment by derickdiaz** [comment]
I would like to take this on after #1197 
It looks like we just have to add the option and use the filter_arch on the pkg_query. The dnf4 implementation of this does not validate if it's a valid arch specified.
