### ISSUE TITLE
Transaction Store and Load API

### ISSUE THREAD

**Issue by kontura** [rpm-software-management/dnf5#999]
Operations such as `System Upgrade`, `Offline Upgrade`, `History Replay`, `History Redo`, `History Store` and others require an API for storing and loading transactions.

- [x] Add an API to store (serialize) a transaction into a JSON data format. We will need to be able to serialize both `base::transaction` and `transaction::transaction` (history transaction).
- [x] Add API to load the JSON serialized transaction into a Goal.

The first part is done but we still need:
- [x] Fix environments handling - requires ABI break
- [x] Add groups/environments replaying without loaded repos
- [x] Verify functionality without loading repos
- [x] Enable/Add CI tests
- [x] Integrate running without loading repos into offline command (system-upgrade)

The API should support packages (RPMs), groups, environments and potentially also modules.

**Comment by kontura** [comment]
The first draft of the API is in PR: https://github.com/rpm-software-management/dnf5/pull/978

**Comment by evan-goode** [comment]
Second draft of the API is PR https://github.com/rpm-software-management/dnf5/pull/1005

**Comment by jan-kolarik** [comment]
Related issue to the mentioned ABI break: https://github.com/rpm-software-management/dnf5/issues/1025.

**Comment by kontura** [comment]
Comps and running without loading repos PR: https://github.com/rpm-software-management/dnf5/pull/1264

**Comment by jan-kolarik** [comment]
Make sure these scenarios are covered: 
- https://github.com/rpm-software-management/dnf/issues/2031
- https://issues.redhat.com/browse/RHEL-17494

Related PR in libdnf: 
- https://github.com/rpm-software-management/libdnf/pull/1644.

**Comment by kontura** [comment]
The API is finished.
